### ISSUE TITLE
Use something quicker than d3.timer for the force layout

### ISSUE THREAD

**Issue by DavidBruant** [mbostock/d3#1519]
## Context

I've been trying to use the [force-directed graph demo](http://bl.ocks.org/mbostock/4062045) for graphs of ~1000 nodes and lags starts at 300-400 nodes. A profiler told me that 80% of the time is spent on
````js
link.attr("x1", function(d) { return d.source.x; })
    .attr("y1", function(d) { return d.source.y; })
    .attr("x2", function(d) { return d.target.x; })
    .attr("y2", function(d) { return d.target.y; });
````
So I broke this down to do [partial moves on requestAnimationFrame](https://gist.github.com/DavidBruant/6489486). Now things are smooth.

## Problem analysis

Investigating potential causes of slowness, I looked at d3 code as I imagines the force layout algorithm was to blame (it isn't as far as know for 1000 nodes. Good job! :-) ). But I discovered that ````force.tick```` is [called as a d3.timer animation](https://github.com/mbostock/d3/blob/5f8056c1e4f41339c3d4d862545d7e21bf4d0e46/src/layout/force.js#L193). Looking at d3.timer, it seems to be using requestAnimationFrame under the hood. This means that no matter how fast the node positions can be recomputed, there can be at most once every ~16.6ms (I've observed that empirically looking at performance.now on each tick event) which is super-slow given how quickly the force layout code seems to run (it's just a bunch of arithmetic operations on abstract numbers which web browsers can run very VERY fast)

## Suggestion

Run ````force.tick```` in ````setTimeout(f, 0)````s. The setTimeouts will be nested, so there'll be the 4ms delay (but that's already much better than *at least* 16.6ms!). [Faster options](http://dbaron.org/log/20100309-faster-timeouts) can be explored too.

The justification is that the force layout algorithms is pure math, nothing visual is performed there, so no need to wait for the browser to tell when to display things. The visual parts are to be done on tick events and as I experienced, one has to break down for requestAnimationFrame anyway for big enough graphs.
In the end, we'll have the force layout algorithm that computes as fast as possible (and find the final positions much much faster than it does today) and people will be free to break down the visual aspects as they wish.

**Comment by minuscorp** [comment]
I'm very interested in this issue and I'd like to know more about incresing the performance of the force layout in D3. Currently, I'm generating layouts which **can have thousands of nodes** with more than one link each one.

After accepting that I never could've have a dynamic and animated layout, I tried the **"static force layout"** approach, but even doing a very short amount of ```force.tick()``` (20 ticks, to be accurate) can delay the load of the layout (and more important, blocking the main thread in the screen, disabling any further interaction with the page until the layout is totally loaded) for minutes.

I've read about Web Workers, but I had to discard them because for drawing the force layout I have to access to the DOM of the page (or am I wrong?)

Is there any approach to increase the loading times of the layout or use any other technique? (I've already tweaked all the configuration parameters to reduce the cost)

Thank you.

**Comment by blakeelias** [comment]
I have the same concern as minuscorp and would like to hear thoughts / solutions!

**Comment by jbaicoianu** [comment]
You can actually run the d3 force simulation "headless", either in a worker thread or on a remote server, and then send the positions to the UI thread for rendering and interaction via postMessage or WebSockets respectively.  

I'm currently using this technique to run a very large continuously-updated graph in node.js on the server, and then sending the positions to clients to render static graphs in their browser.  The nodes load instantly in the right position, no more waiting for ~20-30 seconds of simulation for the graph to stabilize.

In my experience though, the most expensive part is updating the attributes for large number of DOM elements.  It doesn't help that the v8 engine is unable to optimize the function which sets attribute values from functions, this seems to be slowing things down a lot according to the profiler.  Some experiments with hiding nodes outside of the bounding region are promising, but more and more I'm leaning towards rendering the graphs themselves with WebGL instead of SVG.

**Comment by minuscorp** [comment]
I actually went for one of your solutions using WebWorkers and that went pretty well... I statically do a fixed number of iterations on the thread and return the final position for each node to the main thread. That allows to keep things smooth and give the feeling of the graph works instead of getting warnings of script blocking main thread.

**Comment by SpencerCarstens** [comment]
@minuscorp 

How did you go about using WebWorkers with D3? 

Do you have a recommendation of where I should start reading?

I'm not familiar with WeWorkers, but this sounds like a performance solution to my giant hairball of a network.

Thanks!

**Comment by minuscorp** [comment]
I started with the idea proposed by this article
http://datatodisplay.com/blog/simulation/putting-web-workers-work/ and
expanded it to the force layout needs. Basically you will need to
instantiate the layout with your nodes and links, later get those elements
from the layout and communicate them to the webworker which has another
separated force layout un which you insert the data extracted before. Then
you can do de loop with the ``.tick()``` function and return again the
calculated data to the original force layout, insert the data again and
display it.

Of you have problems I can try to post the code snippets I implemented.

Regards.

**Comment by SpencerCarstens** [comment]
@minuscorp 

Thanks for the info! 

When I have some cycles I will give this a shot and see where I get. :)

**Comment by minuscorp** [comment]
I just leave this here... This would be the worker code for example. The main thread just have to create the worker and wait for the "result" message to arrive, then draw the nodes and the links with the coordinates and properties calculated by the worker... And that's it!

Give some credit if this is used in some of your projects and I think this should be fully supported **natively** by the D3.js library. What do you think, @mbostock ?
 
```Javascript

onmessage = function (event) { postMessage(simulate(event.data.data, event.data.width, event.data.height)); };

var simulate = function (data, width, height) {

    importScripts("http://d3js.org/d3.v3.js");

    var force = d3.layout.force()
    force.nodes(data.nodes).links(data.links)

    force.start();

    force.on("tick", function () { });

    for (var i = 0; i < 20; i++) { force.tick(); postMessage({kind: "progress", value: i*5}); }
    force.stop();

    postMessage( {kind: "result", nodes: force.nodes(), links: force.links() });
```

**Comment by altsheets** [comment]
@minuscorp 
I am very much interested in your faster force code. Because my [larger networks](http://altsheets.ddns.net/assetgraphs/graph07.html) are slowing down considerably.

I am new to d3, and I was not able yet to plug your changes

    "This would be the worker code for example ..."   

into the [force-directed graph demo](http://bl.ocks.org/mbostock/4062045). I tried to simply add it to the bottom of that script - but your thing doesn't get executed.

Could you please post a whole working script (perhaps as a bl.ocks.org example) so that I understand your idea better.

Thx a lot!

**Comment by SpencerCarstens** [comment]
http://bl.ocks.org/bollwyvl/b34ffe2f40d64f3aae0f

**Comment by SpencerCarstens** [comment]
I put a working web worker codepen together.

http://codepen.io/spencercarstens/pen/BoQbNw

**Comment by Agilulfo1820** [comment]
@SpencerCarstens I am really interested in your codepen about web workers but the link is broken, do you have a copy somewhere?

**Comment by SpencerCarstens** [comment]
@Agilulfo1820 

I deleted it by accident. :(

Teach me to not name my pens well so my future self knows not to go delete happy...

If I remember right, I took the example block above and then just reworked that into a pen.

Give that a shot and if you get stuck let me know and I'll try and help.

**Comment by Keuluu** [comment]
@minuscorp @SpencerCarstens 

I tried to implement your ideas using a webworker to separate calculation from display.
My objective is to use it on a force layout label placement plugin so I began from [http://bl.ocks.org/ZJONSSON/1691430] which pretty much fits my needs and that I already did set up efficiently without worker support.
As my project may use a huge amount of data, relying on the worker for label position computing is crucial, as is the ability to refresh the force layout setup whenever the item list changes.
This leads to my current problem: I managed to have the worker running and correctly transfer back calculated nodes and links on every tick. The issue happens when the list of anchors is updated many  times rapidly and (I guess) tick still gets triggered back from the worker with outdated anchor or label references...
What is finally happening is labels connecting to wrong anchors for an eye blink when updates are fast (every thing looks quite good when updating once a second), which fill the screen with random 'lazer shots' (maybe not so randomly...).

To set back computed data to real DOM world on each tick, I use:
```javascript
labels.selection[0].forEach( function (d, i) {
	if (d && d.__data__) {
		var data = d.__data__;
		d.labelPos = value.nodes[i*2+1];
		data.anchorPos = value.nodes[i*2];
		data.labelPos = d.labelPos;
	}
});
updateAnchors();
callback();
````
...where _value_ is returned from the worker and _callback_ finally handles positionning.

Could any of you tell me if I am heading in the right direction setting back computed data ?
Could this rather come from when setting force nodes and links at update time ?
I could try to provide more code but the project is quite big with many frameworks and tools and it looks very difficult from here to extract a few elements just to demo that functionnality.
Except for the worker thing, I did not deviate from the original label plugin...

I am also trying to slow down force tick frequency to have a better look in debug tools at how the whole thing is effectively sequencing. Isn't the _alpha_ value the right thing to manipulate if I want to restrict to one tick per force update ?

Thanks for reading and even more thanks if you may orient me towards some light on this...

**Comment by mbostock** [comment]
Here’s a new example, [bl.ocks.org/01ab2e85e8727d6529d20391c0fd9a16](http://bl.ocks.org/mbostock/01ab2e85e8727d6529d20391c0fd9a16), showing how to use web workers with the new [d3-force](https://github.com/d3/d3-force) module to compute a static layout:

[![screen shot 2016-04-26 at 3 19 59 pm](https://cloud.githubusercontent.com/assets/230541/14836065/5baf063e-0bc2-11e6-90f9-6898f0cac20a.png)](http://bl.ocks.org/mbostock/01ab2e85e8727d6529d20391c0fd9a16)

The new force simulation will be part of [D3 4.0](https://github.com/mbostock/d3/tree/4). You can do [static force layouts](http://bl.ocks.org/mbostock/1667139) in D3 3.x as well, though it was a little awkward since you had to call *force*.start and *force*.stop every time you wanted to tick. In D3 4.0 (in d3-force), simulations start by default upon creation, but you can call [*simulation*.stop](https://github.com/d3/d3-force#simulation_stop) to stop the automatic invocation of [*simulation*.tick](https://github.com/d3/d3-force#simulation_tic), and then just call *simulation*.tick yourself as frequently (or infrequently) as you like.

**Comment by forzeny** [comment]
mark
