### ISSUE TITLE
d3.layout.pack overlap

### ISSUE THREAD

**Issue by j0hnsmith** [mbostock/d3#1761]
I've been seeing occasional overlaps when using `d3.layout.pack()`, it seems to only happen when there are quite a lot of zero size data elements at the beginning of the dataset and the dataset is unordered.

http://bl.ocks.org/j0hnsmith/9272589

If the zero size items are removed from the start of the dataset the overlaps don't happen.

**Comment by fairglu** [comment]
This issue is still present even with non-zero values.

I have a graph with wildly varying amounts, when normalizing those in the 1..1000 range, there is no overlap, while when normalizing in the 1..10000 range, there is some overlap.

However, when using the 1..1000 the smaller circles for values of 1 appear really too large, so the 1..10000 range really is necessary (they then appear as small circles, larger than they should be, but not distractingly so, and that makes them hoverable/clickable, which is good)

**Comment by fairglu** [comment]
I have been able to isolate a rather simple case, this seems to be an algorithmic flaw rather than a collision detection issue.

http://jsbin.com/suvuporehu/1/

and the data-set that triggers the overlap (with other settings as in Bubble Chart demo at http://bl.ocks.org/mbostock/4063269)

	{
		children:[
			{value:100},
			{value:1},
			{value:1},
			{value:1},
			{value:1000},
			{value:1},
			{value:1},
			{value:1000},
			{value:1},
			{value:1000},
			{value:1000}
			]
	}

**Comment by rpinquie** [comment]
I am struggling with the same problem. Does anyone has a solution?

**Comment by arnab-dibosh** [comment]
I am facing bubble overlapping issue in pack layout when the difference between minimum and maximum value is very high. Using version-3.5.6. Is the issue resolved now? Please help.

**Comment by rpinquie** [comment]
The error was still there in the version 3.5.7 released by Mike on 8 Nov 2015 after my comment. Perhaps it has been fixed in one of the next versions but I don't think so I need to check this out with the 3.5.16.
