### ISSUE TITLE
Large Quantity Force Layout Performance

### ISSUE THREAD

**Issue by w-p** [mbostock/d3#1936]
Requesting an option to allow the force layout simulation calculations to be optimized / accelerated for large graphs consisting of hundreds or thousands of nodes.  I'm really not sure what the issues at play might but many people have them.  SVG GPU acceleration doesn't seem to help.  Perhaps a WebGL version?

**Comment by mbostock** [comment]
I’ve made some significant performance and stability improvements to the new [d3-force](https://github.com/d3/d3-force) module for D3 4.0, but I agree that you probably need something like WebCL + WebGL if you want thousands, tens of thousands of nodes, or more. (Or offline computation.) You could also use d3-force in a web worker and avoid interactive rendering, since at that scale rendering the nodes will also be expensive. At any rate, I don’t see anything that obviously doable within the confines of JavaScript and the basic velocity Verlet approach used by d3-force.

**Comment by w-p** [comment]
Thanks for reminding me about this.  I was originally thinking of developing something along the lines of:
[http://nullprogram.com/webgl-particles/](http://nullprogram.com/webgl-particles/)

Basically, encoding x, y to rgb and using a shader to push all the computation down to the GPU.  However, I'm not sure that this is really feasible in the context of d3 and it turns out I don't have the time to build a prototype.  Thanks for following up.

**Comment by Joshfindit** [comment]
Adding this as a suggestion: a method to disable continual force calculation after it's been running.

So that: once the graph is laid out and spaced 'well enough', force calculations can be disabled, freeing the CPU while the user navigates the graph.

**Comment by mbostock** [comment]
@Joshfindit See [*simulation*.stop](https://github.com/d3/d3-force#simulation_stop).

**Comment by Joshfindit** [comment]
@mbostock Most excellent, thank you. I also see that it supports '.restart' after it's been stopped.
Big performance benefit here.
