### ISSUE TITLE
Make sticky treemaps stateless.

### ISSUE THREAD

**Issue by jasondavies** [mbostock/d3#1953]
As mentioned in the [documentation](https://github.com/mbostock/d3/wiki/Treemap-Layout#sticky):

> Implementation note: sticky treemaps cache the array of nodes internally; therefore, it is not possible to reuse the same layout instance on multiple datasets. To reset the cached state when switching datasets with a sticky layout, call sticky(true) again. Since version 1.25.0, hierarchy layouts no longer copy the input data by default on each invocation, so it may be possible to eliminate caching and make the layout fully stateless.

Making the current behaviour stateless is quite simple, but would be nice to support addition and removal of nodes too, and this requires a bit more thought, particularly if the ordering is to be respected.  I think it’s reasonable to assume that the order of existing nodes does not change, but we should support nodes being inserted in between other children, rather than only being appended.

**Comment by mbostock** [comment]
The new [d3-hierarchy](https://github.com/d3/d3-hierarchy) treemap implementation is stateless. The arrangement of the treemap is stored in *node*.\_squarify. I think it might even be possible to infer the arrangement from the previous node positions directly (and generalize it to any tiling method, rather than limiting it to squarify), but my initial stab wasn’t successful, so I moved on.
