### ISSUE TITLE
Add base locales before providing dialects

### ISSUE THREAD

**Issue by dwt** [mbostock/d3#1989]
While trying to use the locales d3 provides, I noticed that there are quite some dialects (en_US, en_GB, pt_BR...) but not the base locales. I.e. it is missing en, fr, de, pt, es locales that allow you to show something even if the specific dialect is not yet localized.

Can you please change this? In my view, dialects should be the second step after a base locale has been provided, to allow to show something at least understandable to a native speaker, even if his specific locale is not yet supported.

This request comes from the fact that almost all localization frameworks are able to fall back to a more generic locale if the specifically requested locale is not available, but are unable to use a specific locale as fallback if a another specific locale is asked for.

I did provide some pull requests that add [german](https://github.com/mbostock/d3/pull/1976) and [french](https://github.com/mbostock/d3/pull/1979) base locales.

Is there a reason you would not want to provide base locales (first)?
Would you take my pull requests for more languages?

**Comment by mbostock** [comment]
I don’t want to be responsible for picking which country (or dialect) is considered the base language. For example, it’s not obvious to me that “en” should be an alias for “en-US”. This imposes a hierarchy on top of the locale definitions that, while common in other software, is not a fundamental truth of localization.

Related, as of [d3-format 0.4](https://github.com/d3/d3-format/releases/tag/v0.4.0) and [d3-time-format 0.2](https://github.com/d3/d3-time-format/releases/tag/v0.2.0), the locales are exposed as symbols rather than strings (e.g., [localeEnUs](https://github.com/d3/d3-time-format#localeEnUs) instead of `localeFormat("en-US")`). See d3/d3-shape#23 for a discussion regarding strings versus symbols, but in addition to being the natural representation, symbols enable Rollup to pull in locales selectively in custom builds.
