### ISSUE TITLE
Replace selection.attr(object) with selection.attrs(object).

### ISSUE THREAD

**Issue by zpydee** [mbostock/d3#2109]
I often use the attr getter to set attributes of one object to match another. I have now encountered a situation where I want to inherit all the attributes, and it made me think that a method attrs() would be very useful for this purpose.

so for example, this.newObject = this.group.append('rect').attrs(this.objectToClone);

Just a thought...

**Comment by mbostock** [comment]
I’ve been considering something like this for a while. Rather than overloading selection.attr(name, value) with selection.attr(object), we could introduce a new selection.attrs(object) method. This has several advantages:

* It simplifies the logic in selection.attr, since we don’t need to distinguish between selection.attr(name) and selection.attr(object).
* It allows selection.attrs(function), where the function returns a computed object for each element, allowing you to set whatever attributes you want on a per-element basis.
* It allows selection.attrs(), which returns all defined attributes on given element.

This pattern would extend to other selection methods as well (such as selection.properties and selection.styles, though note that the set of *all* computed styles and all defined properties on a given element is quite large, and perhaps not useful…).

However, this would not be a backwards-compatible change, and so would need to wait for 4.0.

**Comment by zpydee** [comment]
That was much along the lines of my thinking. For larger visualisation libraries like the one I've written it would also make for much terser, more readable code.

Sent from my iPhone

On 13 Jan 2015, at 8:42 PM, Mike Bostock <notifications@github.com<mailto:notifications@github.com>> wrote:


I’ve been considering something like this for a while. Rather than overloading selection.attr(name, value) with selection.attr(object), we could introduce a new selection.attrs(object) method. This has several advantages:

  *   It simplifies the logic in selection.attr, since we don’t need to distinguish between selection.attr(name) and selection.attr(object).
  *   It allows selection.attrs(function), where the function returns a computed object for each element, allowing you to set whatever attributes you want on a per-element basis.
  *   It allows selection.attrs(), which returns all defined attributes on given element.

This pattern would extend to other selection methods as well (such as selection.properties and selection.styles, though note that the set of all computed styles and all defined properties on a given element is quite large, and perhaps not useful…).

However, this would not be a backwards-compatible change, and so would need to wait for 4.0.

**Comment by IPWright83** [comment]
I think this would also be useful from a documentation point of view. I've seen very little use of selection.attr(object) and I think that's probably because many people don't know about it (I certainly didn't). Having a separate selection.attrs() might help with the education of that too.

**Comment by mbostock** [comment]
This is the plan for 4.0: see the [d3-selection-multi repo](https://github.com/d3/d3-selection-multi).

**Comment by mbostock** [comment]
This is underway for 4.0, so closing this issue.
