### ISSUE TITLE
Easing per element

### ISSUE THREAD

**Issue by juancampa** [mbostock/d3#2176]
Transition.ease takes a time parameter which makes it convenient to quickly setup a custom easing function. On the other hand, it doesn't allow for a different easing function per node.

The work around would be to call each() on the selection and then creating a transition for each element like this:

```
  svg.selectAll('.class')
  .each(function(d, i) {
    d3.select(this).transition().ease(/* return easing function using d and i */);
  });
```
instead of this:
```
  svg.selectAll('.class').ease(function(d, i) { /* return easing function using d and i */ });
```
I intuitively thought this would work since it follows the same pattern as delay() and duration() but it doesn't. 

So, is there any way to setup easing per element without the overhead/inconvenience of the first version?

**Comment by mbostock** [comment]
Unfortunately, no. The problem is that D3 uses JavaScript’s typeof operator to distinguish between constant values (values that are the same for every element in a selection) and function values (values that are computed on a per-element basis by invoking the function). Since easing is also defined as a function, there’s no reliable way to distinguish between an easing function and a function that returns an easing function (an easing function factory, if you will).
