### ISSUE TITLE
Random subset of a selection

### ISSUE THREAD

**Issue by sathomas** [mbostock/d3#2181]
I found the following extension helpful in some of my own projects. If you think it is generally useful, I'd be happy to create a pull request (after converting the code to use appropriate private methods, etc.). Otherwise, feel free to close the issue.

```javascript
// Extend the D3 selection object with a method that chooses a random subset of the
// selection. The method's parameter is the number of items to choose.
d3.selection.prototype.randomSubset = function(subsetSize) {
    var subgroups = [],
        subgroup,
        group,
        node;

    for (var j = 0, m = this.length; j < m; j++) {
        subgroups.push(subgroup = []);
        subgroup.parentNode = (group = this[j]).parentNode;
        d3.shuffle(d3.range(group.length)).slice(0,subsetSize).forEach(function(i) {
            subgroup.push(group[i]);                    
        })
     }

     if ({}.__proto__) {
           subgroups.__proto__ = d3.selection.prototype;
     } else {
           for (var property in d3.selection.prototype) {
               subgroups[property] = d3.selection.prototype[property];
           }
     };

     return subgroups;
}
```

**Comment by mbostock** [comment]
I’m not sure what the use case for this method is, so it doesn’t seem like something I would consider for inclusion in core, though I also don’t see any harm in releasing this as a plugin if you desire.

If you’re doing this outside of the D3 library (i.e., you don’t have access to the internal `d3_selection` constructor), I’d recommend using `d3.select(null)` to create an empty selection with a single group, and then populating the additional groups and nodes, rather than assigning \_\_proto\_\_.
