### ISSUE TITLE
d3.layout.patrition Bug on Google Chrome?

### ISSUE THREAD

**Issue by ManhQLe** [mbostock/d3#2195]
It seems like a bug on Chrome , x position is not calculated as expected. Works for other browsers....
http://codepen.io/anon/pen/myWoKp

**Comment by jasondavies** [comment]
This isn’t a bug in Chrome.  Hierarchical layouts have a sort parameter, which defaults to sorting on the value field.  In your example, all nodes have the same value.  In JavaScript, the built-in array sort is not stable, which can lead to different results in different browsers.

Your example can be fixed by turning off sorting: `.sort(null)`, or you could pick some well-defined sort order instead.

D3 could potentially use a stable sort but the built-in sort is usually very fast so I don’t think there’s a compelling reason to roll our own.
