### ISSUE TITLE
Move d3 globals from d3.js to index.js to allow clean module loading

### ISSUE THREAD

**Issue by kileras** [mbostock/d3#2219]
Recently I found out that since July d3 exposes itself as a global no matter if you use with a module system or not. I saw it there https://github.com/mbostock/d3/pull/1921 and I read all the issues related to that and I understand that some people may want to use a module system and expose it as a global anyway (barely but I do). I also saw that there is a icebox issue to disable it here https://github.com/mbostock/d3/issues/1945.

The problem is that the solution to that particular case that is implemented means that the ones that are using modules for everything still get the global, defeating the purpose of the module system an some people, like myself and the guys form the iceboxed issue, would love the have a better solution.

I don't say that we shouldn't expose as global all the time we find a module system and certainly I don't know the d3 code very well and I probably don't see all the implications but can we just move the global definition of the d3 variable to somewhere else, like inside index.js for example? That way if you want the global you have it if you compile/minify/etc with index.js but if you use your module system to load d3.js instead you won't get any global.

Again I never used d3 before and I may be missing something but that seems to be a viable solution that will give us both the global and a clean way of loading using modules. 

Any ideas, possible problems or anything?

**Comment by mbostock** [comment]
Actually, in index.js we don’t expose any globals. There’s code there to stash and restore the `d3` global. We don’t need to expose the `d3` global in index.js because this is only used by CommonJS (Node.js).

The problem is in the browser, where there is a mix of loading systems. This was discussed at length in previous issues, so I’m not going to elaborate much, but the resulting decision is that we expose a `d3` global even if AMD is detected. If you want to avoid the `d3` global, I recommend creating your own version of [src/d3.js](https://github.com/mbostock/d3/blob/master/src/d3.js), and replacing [src/end.js](https://github.com/mbostock/d3/blob/master/src/end.js) with your own implementation, and then running it through [SMASH](https://github.com/mbostock/smash) to create a custom build. (See the [Makefile](https://github.com/mbostock/d3/blob/master/Makefile) for an example.)

I agree this is an unsatisfying state of affairs. I’m hoping that ES6 modules see wider adoption soon, and then we’ll have broader agreement across JavaScript environments on how to load code. I’m also considering using Browserify as an interim measure instead of SMASH, but that probably won’t change how the default build functions in regards to AMD—it would just change how you’d make a custom build.
