### ISSUE TITLE
Use ES6 Modules (and Rollup) instead of SMASH.

### ISSUE THREAD

**Issue by mbostock** [mbostock/d3#2220]
I know this was considered previously (#1978 mbostock/smash#12), but I’ve been using Browserify for a project and I like it quite a bit. It might be time to rewrite D3 to use Browserify along with the other larger 4.0 changes.

**Comment by ericgj** [comment]
You may also want to evaluate [jspm](http://jspm.io/) / [systemjs](https://github.com/systemjs/systemjs), which implements ES6 modules as well as being backwards-compatible with commonjs, and is less tied to NPM than Browserify.

**Comment by mbostock** [comment]
I am aware of those options, but thank you for the reminder!

**Comment by srcspider** [comment]
@mbostock 

Please make it so it's possible to request individual modules and functions when working with d3.

The syntax in the following example is perfectly legal and only requires minor structuring decitions to work.

eg.

Let's say we are rendering with React and we only need some scale and the svg functions of d3.
DOM manupulation, events, xhr, etc are not a concern since we intend to handle via react and other constructs.
```js
// namespace to a d3 to avoid naming hell and keep code familiar
var d3 = {
	scale: {
		linear: require('d3/scale/linear'),
		ordinal: require('d3/scale/ordinal')
	},
	svg: require('d3/svg')
};

// the following lodash code demonstrates an alternative approach that may be
// more friendly for 3rd-party module development purposes
var _ = {
	assign: require('lodash.assign'),
	each: require('lodash.foreach'),
	map: require('lodash.map'),
};
```

The require syntax also helps when working with things such as webpack deduping so it's highly desirable. If you on the other hand were to just say use lodash something and merge the files together there would produce unnecessary bloat.

In addition, as I mentioned in the react-d3 project, having a dependency that's included in the bundles and potentially grows with each update **even though the code that's executed might not change at all**, may be (depending on your requirements/situation) be highly undesirable when there's likely a whole bunch of other dependencies asking for more and more kb.

In addition being able to explicit specify dependencies allows bundlers like webpack to cut up the d3 (that we use) into a bunch of bundles if feasible; on the other hand if we're just including the entire d3 graph each time we're using it we're forced to take the hit of the entire library even if all we want to show is a really really dumb bar chart!

**Comment by zemirco** [comment]
That sounds awesome!
Also what @srcspider said. I'd also like to require individual d3 components directly.

+100000000000

**Comment by mbostock** [comment]
@srcspider Yes, that’s the essence of this request. However you can already create custom builds today using SMASH. The only difference is we’d be using `require` instead of `import`.

**Comment by flying-sheep** [comment]
well, and that import hides what’s imported (except if you plan to `import * from 'something'` all the time)

it would be pretty cool to see `import axisY from 'd3/svg'` instead of `import 'd3/svg'' and `d3_svg_axisY` in the code.

**Comment by colinmegill** [comment]
@mbostock PRs welcome on this or is this under way?

**Comment by flying-sheep** [comment]
for reference, there’s another option: [babel](https://babeljs.io/docs/usage/modules/).

babel allows to use ES6 syntax for imports, and on build, this will be transparently converted to CommonJS/AMD/System/UMD style imports (or a custom one). then you can run browserify/webpack on the result.

alternatively, you can use babel plugins to [browserify/webpack/…](https://babeljs.io/docs/using-babel/)

**Comment by colinmegill** [comment]
+1 for https://github.com/babel/babel-loader

**Comment by srcspider** [comment]
-1 for babel

People who want to use it can use it, but D3 shouldn't use it. Not everyone wants their code to be mangled/interpreted.

You shouldn't be forced into an entire niche tool chain (much like what has happened now with SMASH) that may potentially be incompatible with your own tool chain. Supporting basic **require** syntax will work just fine and will make it easy to integrate components in all 3 of the options mentioned, and just about everything else under the sun that's ever heard of nodejs.

**Comment by mgold** [comment]
One of the features I like about SMASH is being able to remove libraries you don't use and add in plugins, which is useful for a production app. It's the sort of thing you do once, by hand, before passing off to your automated build pipeline. I don't have a preference regarding any particular technology but I'd like to see the "take what you want" option still available.

**Comment by flying-sheep** [comment]
@srcspider you haven’t read my comment: babel will simply convert the forwards-compatible syntax to any kind of module loading syntax you want.

in both cases you currently need a toolchain. something that supports CommonJS for `require` (such as node.js or browserify), and something that supports ES6 syntax for `import` (such as babel or traceur or the [System ES6 module loader](https://github.com/ModuleLoader/es6-module-loader))

in the future, you *will* need some kind of toolchain for `require` or AMD or whatnot. you *won’t* need it for `import foo from 'bar'` (since it’s standard ECMAScript 6 syntax).

**Comment by srcspider** [comment]
@flying-sheep 
> in both cases you currently need a toolchain. something that supports CommonJS for require (such as node.js or browserify), and something that supports ES6 syntax for import (such as babel or traceur or the System ES6 module loader)

That last part is not required at all. The current import syntax is not compatible with ES6, so you can just replace it all with nodejs require since you'll have to go and replace it with something else one way or another. Problem solved. 

As far as I know there's no ES6 in the project so why force everyone to *need* it? Sounds like a "Hipster Dependency"

> @srcspider you haven’t read my comment: babel will simply convert the forwards-compatible syntax to any kind of module loading syntax you want.

You make it sound too innocent for what it is.

It's essentially a meta language, that just looks very familiar but is potentially just as different as any other language of the kind (eg. dart). IT will WRITE code and logic you didn't. Minification and concatenation do not mess too much with the logic of the code, things like this do, especially if you use fancy (barely functional) concepts like ES6 classes (it wouldn't be a standard if it didn't just go against the very prototype nature of javascript).

Anyway, common problems that are to be avoided like the plague that these things bring with them: 
 - opaque runtimes
 - opaque rewriting of code
 - ton and tons of dumb encapsulation in anonymous functions (because it's easier to write it everywhere then actually anylise properly; this makes it annoying to read, debug etc, pray nobody accidentally changes the logic in any way)
 - potential backwards compatibility nightmares (your code may NEVER run with the transpiler; because the transpiler was either too helpful or the standard just changed eventually)
 - the promise of it will eventually work is a promise that will constantly get broken OR become incompatible with the real thing (neither sounds very good; the the authors have no say in it really)
 - you are now dependent on YET another standard (the transpilers support/standard, which is dependent on the standards standard that is made from the nonstandad html5? and influenced by the barely related nodejs standards? err what? might as well just throw in some draft stuff in there too, because why not)
 - a lot of the "standard" way such as "import" make no damn sense with our current tech; like many other standardized things, as the standard would put it, MAY never come and PROBABLY will be totally different eventually (because the solution that best leverages existing tech, is reliable, and gets results always wins; not the one made out of imaginary fairy dust)

**Comment by Mike-Honey** [comment]
-1 from me too. I'd rather everyone's precious time was concentrated on functionality (bugs and enhancements) rather than running on this type of treadmill.

**Comment by natevw** [comment]
What would this mean for custom builds, particularly for non-CommonJS environments? How would I get the traditional `d3` object in my window with only the things I need hung off of it (e.g. `d3.select` but not `d3.csv`)?

One special case here would be `selection.transition` — which was IIRC the main exception to the "grep codebase for d3._anything_ and include that in your custom build" rule which I encountered. If one *isn't* using transitions, they don't need all that duplicated core selection code, but somehow build process needs to handle that being there/omitted, not just for the `d3` object but also for the internal selection prototype.

I doubt supporting custom builds is any sort of show-stoppingly huge challenge (certainly not relative to all the refactoring D3 would need internally to migrate off its internal globals) but a use case to consider imo.

**Comment by flying-sheep** [comment]
@Mike-Honey you don’t get to decide how people spend their time, only to input arguments on *why* you think time is better spent doing sth. else.

@natevw browserify/webpack is exactly that: it emulates a commonjs environment in the browser by providing a require function.

usually you have a main.js or something that `require()`s the parts of your library needed and uses them. for d3.js, a browserify entry point might look like:

```js
window.d3 = require('d3')
```

and d3.js would be

```js
var arrays = require('arrays');
...

var d3 = {
	ascending: arrays.ascending,
	...
}

module.exports = d3;
```

**Comment by srcspider** [comment]
In addition to what @flying-sheep mentioned, you can avoid global index files altogether and simply get ONLY the functions you require, eg. `require('d3/src/svg/axis')` (I'm using the current dir structure, but there shouldn't really be the awkward `/src/` part there normally). 

Just by doing this you can trim something that might be 200kb of javascript to 2kb of javascript.

Also you can do all this on-demand really easily by simply changing `require` to `require.ensure`. Here is an example (you can get this to work using [webpack](http://webpack.github.io/)):

```js
require.ensure([
    'd3/src/scale/linear', 
    'd3/src/scale/bilinear'
    /* etc */ 
], function (require) {
    var scale = {
        linear: require('d3/src/scale/linear'),
        bilinear: require('d3/src/scale/bilinear')
    };

    // ...
});
```
Now the javascript required for that chart will only be dynamically loaded in as required. And if you have multiple charts, each requiring slightly different bits and pieces, you will have multiple js files that are dynamically loaded in as required. You may specify a name as 3rd parameter to `require.ensure` to bundle them together to avoid too much module dependency duplication, however even with the duplication the loading involved compared to injecting the entire library as a global is magnitudes smaller.

**Comment by mbostock** [comment]
Updated title of bug to reflect the active 4.0 strategy, which is to use ES6 modules and Rollup to produce a default build. See #2461 for details.

**Comment by srcspider** [comment]
**Proposal**

Why not support nodejs and this ES6/rollup thing? 

I mean, so long as you dont use any sophisticated syntax you can just covert the imports to one or the other. It's trivial to create a simple build pipeline that just builds a "node version" and a "es6 version" 

For people who want to do the java-like defensive programming style alongside ES6 for it's static analysis obsession, which sounds good in theory and yet to proven extensively in practice, you would have the ES6 version.

For people who want the raw control and simplicity, that also happens to *work* with practically every production tool out there, you would have the standard nodejs style version.

Simple enough, and best for everyone. Heck if someone comes with some other new hype module system X you would just need to stick another cog in the pipeline and voila, you have d3-for-X.

Probably easier from ES6 to require since ES6 is essentially been designed to be a worse require (for the sake of static checking; static check which has yet to solve anything but the problem of ES6 being a worse version of require). I would strongly prefer if the code itself wasn't ES6 since it would mean you have to pass it though transpilers, ie. bloat it up with useless guard code, unnecesarily named anonymous functions, etc everywhere and lets not forget the polyfills.

---

@mbostock why? Not sure I understand just from the title the motivation.

I honestly see no advantage. This 3rd party tool (that's apparently not even written if I'm reading the docs right) doesn't seem like it will work for anybody but very specific people's pipelines. To be exact at most single bundle, no dynamic loading, non-SPA, etc.

The author of rollup brings up directories as some cardinal sin but his approach relies completely on static analysis which he himself agrees does not work properly when you have cases where code may be dynamically loaded in.

You even have to have the analysis be aware of dynamic loading of javascript modules, otherwise it probably wouldn't work. From what I see the author is either ignoring concepts like `require.ensure` or isn't aware of them. I know ES6 advertising itself as asyncronous module loader, but as far as I'm aware it doesn't actually mean it in the sense that's useful like `require.ensure` but in the sense of it can make network calls PER FILE. Do you like making 1 network call per file or making sure all your 10,000 whatever files are accessible though the network? because keeping bundles of them is enough work as it is; don't want to worry about gzip/minification strategies per individual source file. 

Essentially, adopting rollup sounds like saying "no" to dynamic loading of bundled javascript (in favor of mass requests as the only alternative approach), ie. abandoning the one thing that can keep your javascript from exploding at the present state of things, and gives you a reasonably scalable arhitecture. The entire project seems like a early version of browserify but specifically for hyping ES6. Consider this, very recently Microsoft did a checkup on websites and found the great majority of developers out there prefer to minify and bundle their code not do the AMD thing of requiring a file for every little thing. In case it wasn't clear already, **ES6 = standardized AMD**, it's adopting "theory" that kind-of worked but not really instead of `require` which is/was blunt enough to actually work.


Bellow I'll go into detail on the various things "condemned" by `rollup`

---

*The `require('d3/svg')` style so-called "problem"*

Using sub-directories (it's actually not directories but files work too; the .js is not mandatory) is intuitive. You are in control of what is loaded in. You don't have to worry about how the static analysis tool isn't smart enough to know what it needs to do, you've explicitly told it what it needs to do; and if you do it everywhere it is equivalent to it deciding the ideal path only you know what its doing and you can easily follow the steps (much like you can easily follow the steps to determine where `require('something')` is loaded from). 

---

*The problem with static analysis...*

You can't half ass it. The language is just really good for it or it's guessing. Javascript isn't good for it, and some people trying to make their code extremely defensive and statically analyzable (at the expense of pretty much everything) doesn't mean it can be accepted as a solution for everyone else too.

**Both npm and webpack have deduping functionality** (ie. in the same vein as static analysis implied by rollup here) and how well does it work? *...it doesn't*. The problem lies in tools. Minification + Source Maps + Dynamic Loading of Code is not simple, once you add deduping/dynamic code analysis, it gets ugly. Javascript itself is not exactly very strongly typed so a lot of the time static analysis is bluffing and/or randomly guessing (and spitting warnings at you like thats normal).

In the case of webpack, for example, the very nice error that happens when things go wrong is that webpack upon dynamically loading a module blows up (this will happen most often on watch; change a single character, boom), since the deduping + module loading + minification somehow got it wrong or failed to keep up. And believe me I tried to fight errors like that, but when what you have to look at is minified code (ie. with simple optimizations based on static analysis) that has gone though a algorithmic process you need a wall to just conceptualize. Its not feasible to fix most of the time and for the best if avoided entirely. 

Node has pretty much build its entire ecosystem on this notion of "keep it stupid", and while I don't necessarily agree all the time with how node does things, dammit it works, and it doesn't blow up in production.

---

*With regard to requiring private parts of the code*

 First off, you can force your way into any object in javascript, it's pretty hard to keep per instance private bits outside of static variables that you declare before a type; just drill into prototype. That being said, it's not particularly hard to keep things private if you really want to either; if you stick something under a `src` folder it's nobody's business what goes in there, and if someone tries to grab a file directly from there that's their problem. 

I honestly don't buy this argument from rollup that directories are somehow less clear. How is it less clear when it's in the user's control and not some tool that does it behind your back?

---

*Specifically with regard to ES6*

Okey so there are a few ES6 I like (arrow functions, promises, generators; that's about it I think), but  most of it is still a lot of hype and yet to be proven in any way (other then having a lot of fans). 

This is a table of bleeding edge browser support...

https://kangax.github.io/compat-table/es6/

It's still sad. Not even the transpilers get it. 
When you consider supporting old browsers, it's not exactly safe to use yet.

ES6 is at the same level as coffeescript, just with more hype and publicity around it. And if it's any indication coffeescript is slowly going into the grave as the hype behind it subsides. What will happen when the hype behind ES6 subsides; in particular from people writing articles and not projects. We've had so many hype trains crash it's not even funny. Local storage has gone though how many iterations now for example? each one, the "definitive" bestest version.

I would recommend exercising caution. There's absolutely nothing wrong with vanilla javascript. In fact it's only flavor you can reliably say "it works exactly as I wrote it." In the current state of ES6 you can barely say that about the standard much less the transpilers.

**Comment by mbostock** [comment]
A few points.

1. I’m not adopting all of ES6; I’m only adopting ES6 Modules as a way of structuring the code, replacing SMASH. Other than the `import` and `export` statements, the code will remain ES5. See [d3-color](https://github.com/d3/d3-color) for an example.

2. Use of Rollup is optional, for two reasons:

  2A. Each D3 module exports a “precompiled” UMD build in addition to the ES6 modules. This means you have multiple options for how you consume the code (e.g., CommonJS for Node, RequireJS, Browserify, vanilla script tags).

  2B. Since the code is written according to the ES6 modules standard, any tool that supports ES6 modules can access the ES6 modules directly. (That’s the individual files within the D3 modules, i.e., the files within `src/` in each git repository.) This means you’ll be able to use [SystemJS](https://github.com/systemjs/systemjs) to similar to do dynamic loading of ES6 modules if you want.

  The main reason to use Rollup is that it can be more selective about which parts of the code are pulled in. If you don’t mind pulling in the entire D3 module (and they are generally fairly small), then you can use another tool.

3. I’m planning on building a point-and-click web interface for creating custom builds. It will almost certainly use Rollup internally, but the user shouldn’t care. They’ll be able to download a UMD build (or perhaps IIFE / CommonJS if desired), with just the parts they need, either minified or not.

**Comment by srcspider** [comment]
> I’m not adopting all of ES6; I’m only adopting ES6 Modules as a way of structuring the code

Thank you.

> I’m planning on building a point-and-click web interface for creating custom builds. It will almost certainly use Rollup internally, but the user shouldn’t care. They’ll be able to download a UMD build (or perhaps IIFE / CommonJS if desired), with just the parts they need, either minified or not.

I see. Looking forward to that. Though "downloading commonjs" sounds a bit wierd since that's not exactly how it's suppose to work (it's suppose to be `npm install`)

**Comment by flying-sheep** [comment]
that was what i proposed, happy to see it being adopted!

i didn’t know of rollup but other than the EXPERIMENTAL: DO NOT USE warning, it seems to do exactly what this project needs.

@srcspider i can’t really understand why you have such irrational reservations against ES6 modules.

e.g. the syntax is *better* for static analysis (dedicated statement instead of function calls)

and it IS the future. the standard is finalized. nothing will change, no matter if the changes were “proven in the wild” or not. the stuff is here to stay.

the “why” is also easily explained: SMASH will pollute the global namespace. simple module-level constants will be available to *everything* if you happen to load that module, and `(function() { ... })()` hackery to circumvent it sucks.

**Comment by srcspider** [comment]
@flying-sheep my hate for ES6 is simple, your are not **using** ES6, you are writing ES6 but you are actually using [insert-transpiler-here]. Also, ES6 modules don't provide equivalent for `require.ensure`.

So I write perfectly reasonable ES5, go though every possible way to save space, and then watch as sticking ES5 in a ES6 transpiler makes it to spit out larger code! Because they add their opinionated nonsense logic which is minifiable (because its logic). 

There's no value to saying "its static analyzable" when none is involved in the transpilers. You called `(function () {})()` hackery but that's what happens with transpilers along with a lot of `$` gobly goop everywhere. Even turning on loose mode in something like babel still will convert ES5 to more complicated ES5.

**Comment by Rich-Harris** [comment]
@srcspider Author of Rollup here. Let me try and clarify one or two things:

> you are writing ES6 but you are actually using [insert-transpiler-here]

@mbostock already clarified that D3 doesn't use ES6 syntax other than the module syntax, so no transpilation actually takes takes, only bundling - exactly the same as if you used Browserify or Webpack (without which you obviously can't use `require`), except considerably more efficient. If you like, I can go into more detail about why it's more efficient. 

> Also, ES6 modules don't provide equivalent for `require.ensure`

`System.import` is what you're looking for. The spec *may* change before it's implemented natively in browsers, but there is a production-ready polyfill called [System.js](https://github.com/systemjs/systemjs).

ES5 doesn't provide `require.ensure`. It's in a draft of CommonJS, but is basically only implemented by Webpack. By using it in your code your are therefore creating a tight coupling between your code and your tooling. The point of standards, such as ES6 modules, is to free us of that problem.

The good news is that since ES6 is easy to transpile to other formats, and since each D3 module will have a UMD build, nothing will stop you from continuing to use Webpack and `require.ensure`.

Rollup *is* in early development, but it's self-hosting, bundles several other libraries, and passes the test suite from the (extremely well battle-tested) [es6-module-transpiler](https://github.com/esnext/es6-module-transpiler) project. Having said that if you encounter bugs please feel free to raise them on the Rollup issue tracker.

**Comment by mbostock** [comment]
@Rich-Harris Thank you for work on Rollup and for supporting this effort!

**Comment by colinmegill** [comment]
So long as there is a story for every module having an `index.js` file and being published to `npm`, no issue... the online custom build creator should be secondary to that.

**Comment by srcspider** [comment]
@Rich-Harris 
> @mbostock already clarified that D3 doesn't use ES6 syntax other than the module syntax, so no transpilation actually takes takes, only bundling - exactly the same as if you used Browserify or Webpack (without which you obviously can't use require), except considerably more efficient. If you like, I can go into more detail about why it's more efficient.

Would be more interesting in overal workflow integration, a single tool can't really sell anything even if its better if it doesn't work in a complete pipeline. How good it is on a simple watch workflow; is it faster then webpack eval? The performance when it comes to building for production is not that relevant, you're gonna have a lot of other tooling involved including minification etc so its acceptable even if it were to longer so long as the end result is better (smaller bundles, better resolution of dependencies, etc).

> System.import is what you're looking for. The spec may change before it's implemented natively in browsers, but there is a production-ready polyfill called System.js.

I have seen it before, but unless I'm mistaken I don't believe it does more then loading in manually created bundles; which works for certain use cases (such as loading entire libraries) but is a very big no-no if you want the system to do very micro-optimized level loading (ie. resolve everything to the absolute minimum per bundle).

*Just so we're not comparing apples to oranges here is a example I would use to measure implementations competence...*

## Example

Let's consider a isomorphic SPA with nodejs server rendering (api implementation irrelevant; can be done in anything), multiple pages (we'll consider there are 3 for the example). If its of any relevance let's say all actions are implemented though action functions and rendering is done though React, since that's one of the "good design" flows right now. To keep the example simple we'll ignore fallback cases.

To achieve isomorphic page rendering we'll need to have a entry point for each page, and we'll also need a page changing action for each one. This is how it might look,

*entry point Page1*
```js
// common crud
var client = require('client');
client(require('ui/Page1'));
```

*page change action for Page1*
```js
// we'll pretend our router is the entity to which all entites capable of handling page 
// change events attach to; in our example this might be a Root element, created by 
// the client function when rendering it's page input, that hosts pages as it's children
var dispatcher = require('ctrl/dispatcher');

module.exports = function () {
	require.ensure([
		'ui/Page1'
	], function (require) {
		dispatcher.changePageTo(require('ui/Page1'));
	});
}; 
```

The other two pages would be exactly the same only with `Page2` and `Page3` instead of `Page1`.

*Now for the problematic part,*

Let's assume the dependencies for the entry points look something like this, note these are the dependencies for the pages, not the actions, nor the entry points.

*ui/Page1*
```
ui/Page1
ui/Field/Input
ui/Field/Dropdown
lib/merge
lib/each
lib/map
```

*ui/Page2*
```
ui/Page2
ui/Field/Dropdown
lib/map
lib/reduce
lib/d3/svg
lib/d3/axis
```

*ui/Page3*
```
ui/Page3
ui/Field/Input
lib/reduce
lib/each
lib/d3/svg
lib/d3/axis
lib/d3/color
```

The webpack workflow with `require.ensure`, with out any more configuration then pointing to the entry point file (ie. the 2-liner in the example) will generate 3 entry point files and generally 3 chunk files, each chunk bringing in the extras required for the entry points. Which is to say since it's safe to assume React will be in every entry point by default that won't be bundled in the chunks (as an example). This example is simplified but the effect is the same if we add complex 3rd party dependencies to the mix.

The result is extremely small partials for optimal loading on page change. Obviously you don't need to use this only on page change, any sort of complex in-page action will do as well, but it's sufficient for the purposes of the example.

---

It's to my understanding (and if I'm reading `System.import` wrong or it's undocumented please correct me) to archive the same will require you to do it yourself by hand. ie. literally analyse the dependency tree yourself and write the bundles, then manually write the import of those bundles.

This is unlikely to happen, so what I see as the only usable workflow for System.import (at the moment at least) is to bundle your tooling into major bundles (ie. use all of lodash even if you use only merge, each, reduce, etc) and then require those major bundles; which is far more inefficient (orders of hundreds of kilobytes more inefficient), and a lot more work for you as well.

Again if there's some workflow that does it the correct way, with out ignoring the modularity, in favor of being biased towards only monolithic library bundles then I'm more then happy to switch to `System.import`, but right now it doesn't seem to address today's architectural hurdles.

---

*I've seen in the docs some reference to `http2` somehow being the final solution, so before that gets thrown out, let me just clarify the issues with that as well.*

 `http2` requires both server and client support and as far as I'm aware only `nginx` (which also offers support for `SPDY `) has announced supporting it any time soon (ie. sometime Q4 this year). I know there are servers for `http2` already (eg. `H2O`), however there are also a lot of applications out there that require more then a `.htaccess` file to work optimally so switching servers can be as feasible as someone completely entranced in the apple ecosystem switching to android. Server side aside, if you need to support any legacy browsers you can't just switch your entire system to sending single source files on mass as that is virtually suicide for the performance of your legacy users.

But lets say you only need to support chrome users, just as an example. Even then it's troublesome. Unfortunately javascript it not a pre-compressed format like jpeg, png, etc, so gzip has to happen on trasfer to achive reasonable speeds. The difference between gziping and not gziping is too high. It's unclear right now how well `http2` and servers supporting it can handle automatic bundle/gziping of files. If gzipping has to happen per file it would be essentially unfeasible, since (a) small files have too few repeating patterns for the gzip to gain much, or rather bundles are too advantageous for gzip (b) anything under `200B` will generally result in negative savings (eg. `200B` raw, `240B` gziped), and you can easily get a lot of smile files. As an example, a lot of `lodash` functions are actually a collection a ton of smaller functions that themselves include a lot of other smaller functions; I don't particularly like this since the multiple-layer wrapping results in what should be a 300B function gzipped being a 1kB+ function gziped, but that's how they're written and it's worse case for single-file gzipping strategy.

In the end, the most consistent (and http1 friendly) method is still to bundle your scripts into a single script and minify it before passing it on. `http2` was specifically designed to pass the connection/cdn spamming and 2/6/8 items per connection limit. Its probably for the best to limit it at that, at least until the standard and technologies around it (servers/browsers) are more mature; and support for http1-only browsers is dead.

**Comment by Rich-Harris** [comment]
@srcspider The basic question seems to be 'can System.js do everything Webpack can?' The answer is no (that's not it's job), and ES6-native tooling comparable to Webpack doesn't currently exist, but I'll reiterate what I said before - *you can continue to use Webpack* - the UMD builds will work out of the box, and if you want to require individual files, there are plenty of tutorials available that will help you configure Webpack to work with ES6 modules with negligible performance impact.

**Comment by Rich-Harris** [comment]
@mbostock you're very welcome - thank you for blazing a trail for other library authors!

**Comment by flying-sheep** [comment]
@srcspider 

> So I write perfectly reasonable ES5, go though every possible way to save space, and then watch as sticking ES5 in a ES6 transpiler makes it to spit out larger code!

this is a *complete* non-issue, as you can obviously use something like `babel --whitelist es6.modules` and *bam* it’s guaranteed to not mangle anything.

**Comment by srcspider** [comment]
@flying-sheep it doesn't make a difference,

*example 3rd-party library*
```js
// module0.js
export const sqrt = Math.sqrt;

export function square (x) {
	return x * x;
}

export function diag (x, y) {
	return sqrt(square(x) + square(y));
}
```

*example usage*
```js
// test.js
import { square } from 'module0';
var x = square(2);
```

*babel output*
```sh
babel --whitelist es6.modules test1.js
```
```js
var _module0 = require('module0');

var x = (0, _module0.square)(2);
```
All the functions of `module0` are still included (might as well just use a cdnjs version if thats what it's gonna do honestly). The code is still very much mangled as well.

---
For comparison,

```js
// module0/square.js
module.exports function square (x) {
	return x * x;
};
```
```js
// test.js
var square = require('module0/square');
var x = square(2);
```

Only the code for square has been included. You can just have a `index.js` version that exports a object with all the functions for people who want to do `require('module0')` out of laziness.

---
@Rich-Harris I find most tutorials to fall into the same problems I just explained to @flying-sheep above. They take the standard's "idealized theory" as actually existing and being a pro, when its very much a case of "the standard only says it should work like that" but implementations/tools don't actually do it; and who knows if they ever will.

**Comment by Rich-Harris** [comment]
@srcspider Once again, **no-one is stopping you from continuing to work as you currently do**. The comparison you draw is incorrect. No-one is suggesting that all the functions of a D3 module will live in its index file - if you look at the D3 4.0 source code, the functions don't live in the index file (which is exactly that - an [index](https://github.com/d3/d3-arrays/blob/master/index.js) to where the various parts of the public API are defined), they live in the `src` folder.

So you can continue (or rather, start, since this isn't possible in D3 3.x anyway) to write CommonJS app code like this...

```js
var interpolateNumber = require( 'd3-interpolate/src/interpolateNumber' );
```

...and you only need configure Webpack to convert the `d3-interpolate` source files, which ought to be trivial.

(Your example does show that ES6 modules free library authors of the need to structure code for that usage pattern. Rollup has no problem discarding `sqrt` and `diag` from its output.)

**Comment by srcspider** [comment]
@Rich-Harris
> @srcspider Once again, no-one is stopping you from continuing to work as you currently do. The comparison you draw is incorrect. No-one is suggesting that all the functions of a D3 module will live in its index file - if you look at the D3 4.0 source code, the functions don't live in the index file (which is exactly that - an index to where the various parts of the public API are defined), they live in the src folder.

Me being free to use an older (eventually no longer supported) version, fork, create a specialized hack just for it or completely rewrite the project has nothing to do with the problem and is hardly a "solution."

How is it that I'm wrong to point out nothing actually seems to work when it comes to generating minimal code in combination with current ES6 tools. There's no point in modularizing if no tool exists that can take advantage of the feature.

> Your example does show that ES6 modules free library authors of the need to structure code for that usage pattern

You can spin that both ways: "ES6 modules tempts authors into creating monolithic single file libraries that are a nightmare to send though the network in small chunks and require sophisticated tools (that dont exist) to work"

> Rollup has no problem discarding sqrt and diag from its output.

Given the example from before (which is [the canonical use case](http://www.2ality.com/2014/09/es6-modules-final.html)) I add the following steps...

```sh
echo "{}" > package.json
npm i -D rollup
```
*build.js*
```js
var rollup = require('rollup');

rollup.rollup({
	entry: './test1.js'
}).then(function (bundler) {

	var bundle = bundler.generate({
		format: 'cjs',
		// included only in case
		// they're required parameters:
		exports: 'auto',
		moduleId: 'm0',
		moduleName: 'example'
	});

	console.log(bundle.code);

});
```

Running `node build.js` yields nothing.
This is based on the example here: https://www.npmjs.com/package/rollup

I imagine that example may be out of date, can you provide the updated version?

**Comment by flying-sheep** [comment]
@srcspider you took what i wrote out of context. i referred to your assertion that “transpilers” always mangle your code. which they don’t necessarily, depending on their scope and configuration.

and the comparison you made is wrong!

that’s dishonest. i neither come along and claim that you can write this ES6 code

```js
// module0/square.js
export default function square (x) {
    return x * x
}
```

```js
// test.js
import square from 'module0/square'
var x = square(2)
```

while being *forced* to write this CommonJS code:

```js
// module0.js
module.exports = {
	sqrt = Math.sqrt,
	function square (x) {
		return x * x
	},
	function diag (x, y) {
		return sqrt(square(x) + square(y))
	},
}
```

```js
// test.js
var square = require('module0').square
var x = square(2)
```

**Comment by Rich-Harris** [comment]
@srcspider You probably have a filename or path wrong somewhere, it works fine for me. I've packaged up the example for you: https://github.com/Rich-Harris/rollup-example-for-srcspider.

Honestly, this conversation has become a bit tiresome, so I'm going to bow out. No-one is obliged to write libraries in a manner that happens to suit your preferred way of working (you preferring to require individual files from within packages puts you in a tiny minority) as opposed to authoring in the most flexible and future-proof way.

ES6 modules prevent exactly zero current use cases, and are the standard that everyone will be using in the future. If the tooling isn't yet where you'd like it to be, there are far more constructive ways to contribute.

**Comment by srcspider** [comment]
@Rich-Harris
> @srcspider You probably have a filename or path wrong somewhere, it works fine for me. I've packaged up the example for you: https://github.com/Rich-Harris/rollup-example-for-srcspider.

Thanks for the example. That is indeed very nice output, much nicer then I expected it to be.

> ES6 modules prevent exactly zero current use cases, and are the standard that everyone will be using in the future. If the tooling isn't yet where you'd like it to be, there are far more constructive ways to contribute.

I'm still not convinced on code that would require transpilers, **but** ES6 modules + your tool do seem to make sense and be usable in production. I still need to look into creating `require.ensure` behavior with it but it does a very clean conversion so no complaints on what it currently does. Props for keeping things clean.

**Comment by mbostock** [comment]
This migration is well under way. Closing this issue as it is now being tracked by #2461.
