### ISSUE TITLE
Plugin directory

### ISSUE THREAD

**Issue by balint42** [mbostock/d3#2243]
Just a quick question to the d3 developers: is there an official repos or listing for plugins? I was trying to add the humble [comic.js](https://github.com/balint42/comic.js) to [this](https://github.com/d3/d3-plugins) repos but it seems dead.

**Comment by bhollan** [comment]
Did you ever get this issue resolved?  The repo looks dead to me too, but @mbostock will know more.

**Comment by mbostock** [comment]
Currently there is this:

https://github.com/d3/d3-plugins

As part of the 4.0 restructuring, I am probably going to break apart the plugins into lots of repos under the D3 organization here, allowing separate teams to own each plugin as desired:

https://github.com/d3

Another thing we could do is make a page on the Wiki that lists plugins, so that people individuals can host their own repositories if they don’t want to put them under the D3 organization.

**Comment by bhollan** [comment]
I think both of those are good ideas.  Is there a way I can close this issue?

**Comment by mbostock** [comment]
Sure. Here’s the wiki page: https://github.com/mbostock/d3/wiki/Plugins
