### ISSUE TITLE
LinearGradient broken in Chrome when using groups

### ISSUE THREAD

**Issue by acostaf** [mbostock/d3#2262]
I have being using LinearGradient on IE9/IE11 where everything work fine but as soon as I test the sample on chrome found that the linearGradient is not being rendered, managed to reproduced the issue when I wrap the shape that use the LinearGradient on a group 
Working version with not groups http://jsfiddle.net/v3127wmp/1

	var width = 300,  height = 300;
	var svg = d3.select('#div').append('svg').attr('width', width).attr('height', height);
	//var g = svg.selectAll('g').append('g');

	var gradient = svg.append("defs")
		.append("linearGradient").attr("id", "gradient")
		.attr("x1", "0%").attr("y1", "0%").attr("x2", "100%")
		.attr("y2", "100%").attr("spreadMethod", "pad");

	 gradient.append("stop").attr("offset", "0%")
		.attr("stop-color", "#a00000").attr("stop-opacity", 1);

	gradient.append("stop").attr("offset", "100%")
		.attr("stop-color", "#aaaa00").attr("stop-opacity", 1);

	var gradient2 = svg.append("defs")
		.append("linearGradient").attr("id", "gradient2")
		.attr("x1", "0%").attr("y1", "0%").attr("x2", "100%")
		.attr("y2", "100%").attr("spreadMethod", "pad");

	 gradient2.append("stop").attr("offset", "0%")
		.attr("stop-color", "#a00000").attr("stop-opacity", 1);

	gradient2.append("stop").attr("offset", "100%")
		.attr("stop-color", "#aaaa00").attr("stop-opacity", 1);

	var circle = svg.append('circle')
		.attr('cx', width / 2)
		.attr('cy', height / 2)
		.attr('r', height / 3)
		.attr('fill', 'url(#gradient)');

Broken version with groups http://jsfiddle.net/u1zs2oqo

    	var width = 300,  height = 300;
	var svg = d3.select('#div').append('svg').attr('width', width).attr('height', height);
	var g = svg.selectAll('g').append('g');

	var gradient = svg.append("defs")
		.append("linearGradient").attr("id", "gradient")
		.attr("x1", "0%").attr("y1", "0%").attr("x2", "100%")
		.attr("y2", "100%").attr("spreadMethod", "pad");

	 gradient.append("stop").attr("offset", "0%")
		.attr("stop-color", "#a00000").attr("stop-opacity", 1);

	gradient.append("stop").attr("offset", "100%")
		.attr("stop-color", "#aaaa00").attr("stop-opacity", 1);

	var gradient2 = svg.append("defs")
		.append("linearGradient").attr("id", "gradient2")
		.attr("x1", "0%").attr("y1", "0%").attr("x2", "100%")
		.attr("y2", "100%").attr("spreadMethod", "pad");

	 gradient2.append("stop").attr("offset", "0%")
		.attr("stop-color", "#a00000").attr("stop-opacity", 1);

	gradient2.append("stop").attr("offset", "100%")
		.attr("stop-color", "#aaaa00").attr("stop-opacity", 1);

	var circle = g.append('circle')
		.attr('cx', width / 2)
		.attr('cy', height / 2)
		.attr('r', height / 3)
		.attr('fill', 'url(#gradient)');

**Comment by jasondavies** [comment]
This isn’t a bug in D3, so strictly speaking GitHub isn’t the right place for this (try [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js Google group](https://groups.google.com/d/forum/d3-js) in future).

It does seem like a bug in Chrome, since the order of elements shouldn’t matter.  A simple workaround would be to ensure that your `<defs>` elements appear before any references to them.  In other words, you can move `var g = svg.selectAll('g').append('g');` so that it comes after appending the `<defs>` elements (just before you add the circle).

**Comment by acostaf** [comment]
@jasondavies g is happening before, also it is working fine on IE9/IE11 but the same code fails on chrome, also taken the generated svg code directly on the html also work, the problem is creating from d3, so it seem that may be related with d3

**Comment by jasondavies** [comment]
Maybe I wasn’t clear: the workaround for the bug in Chrome is to ensure that `<g>` occurs *after* `<defs>`:

```svg
<svg>
  <defs>…</defs>
  <g>…</g>
</svg>
```

This can be achieved by moving `var g = svg.append("g")` so it comes *after* you’ve appended `<defs>`.  At the moment, you have the following:

```svg
<svg>
  <g>…</g>
  <defs>…</defs>
</svg>
```

**Comment by Sergio747** [comment]
I figured out, that the problem goes away if you remove all the hyphens from the linearGradient element's IDs. Simple as that. It words with groups too. 
I would be glad, if that helps somebody...

**Comment by sean-mystyle** [comment]
Man.... there is definitely bugs in Chrome with this still.  If I just use inspector to edit the SVG without touching the gradient which doesn't show up (added after dom loaded / rendered with JQUERY), and just apply a change, it somehow triggers a re-render and the gradient shows up.  For example I can add an arbitrary attribute or change a value with something minor and when I press "enter" it shows up.  Then I can remove that change, reverting back to original, and it shows even though when applied it does not.  linearGradient  shows lowercase when it's not working, and magically corrects to camel caps when it starts working.... very strange.

**Comment by sean-mystyle** [comment]
**Update:**  

By using Snap SVG to apply the gradient rather than writing a valid gradient code and appending it to the SVG thru the DOM, it does solve whatever rendering race condition bug there seems to be with updating the SVG in certain ways after render... even if the gradient code is identical in the SVG document in both cases.

**Comment by ariyankhan** [comment]
The main problem is your misunderstanding about `d3` library. It's not any bug of `d3` or any browsers.

It does not matter where you add the `<defs> ` element in your `<svg>` root, it may be after `<circle>` or before `<circle>`, both works on every browsers.

Let me explain,
For the first case when you do not use any `<g>` element then everything is well.
but for the second case when you are trying to add a wrapper i.e. `<g>` element,
then you used `var g = svg.selectAll('g').append('g')` to add a `<g>` wrapper.
but actually it is wrong and even no `<g>` element will be added to `<svg>` root,
because `svg.selectAll('g')` returns an empty selection (as there was no `<g>` element added previously) and also `svg.selectAll('g').append('g')' returns an empty selection.
so when you use `g.append('circle')` to add a `<circle>` then no circle is added because here `g` is an empty selection. that's why no linearGradient will be shown in any browser.

So the correct version for the second code snippet is below:

 ```javascript
 var width = 300,  height = 300;
var svg = d3.select('#div').append('svg').attr('width', width).attr('height', height);
var g = svg.append('g');  // Only changed here, now g is a selection of one <g> element


var gradient = svg.append("defs")
    .append("linearGradient").attr("id", "gradient")
    .attr("x1", "0%").attr("y1", "0%").attr("x2", "100%")
    .attr("y2", "100%").attr("spreadMethod", "pad");

 gradient.append("stop").attr("offset", "0%")
    .attr("stop-color", "#a00000").attr("stop-opacity", 1);

gradient.append("stop").attr("offset", "100%")
    .attr("stop-color", "#aaaa00").attr("stop-opacity", 1);

var gradient2 = svg.append("defs")
    .append("linearGradient").attr("id", "gradient2")
    .attr("x1", "0%").attr("y1", "0%").attr("x2", "100%")
    .attr("y2", "100%").attr("spreadMethod", "pad");

 gradient2.append("stop").attr("offset", "0%")
    .attr("stop-color", "#a00000").attr("stop-opacity", 1);

gradient2.append("stop").attr("offset", "100%")
    .attr("stop-color", "#aaaa00").attr("stop-opacity", 1);


var circle = g.append('circle') // now one <circle> will be added. 
    .attr('cx', width / 2)
    .attr('cy', height / 2)
    .attr('r', height / 3)
    .attr('fill', 'url(#gradient)');
```
