### ISSUE TITLE
d3.layout.force: frozen nodes jerk when unfrozen

### ISSUE THREAD

**Issue by kalenedrael** [mbostock/d3#2347]
In 5390ac3, charge and gravity forces were changed to update px/py instead of x/y for improved stability. This causes the steady state values of px/py to be different from x/y. Because x/y are set equal to px/py on frozen nodes, they will jerk when unfrozen (e.g. when mousing over and then off). This is somewhat annoying for interactive visuals.

Would it make sense to accumulate using px/py throughout, instead of modifying x/y?

**Comment by mbostock** [comment]
This is closely related to #1357. But I think this specific issue is fixed in the new [d3-force](https://github.com/d3/d3-force) for [D3 4.0](https://github.com/mbostock/d3/tree/4), which uses velocity Verlet instead of position Verlet, and offers [improved stability](https://twitter.com/mbostock/status/725009039038402560).
