### ISSUE TITLE
line interpolation error

### ISSUE THREAD

**Issue by SamWhitby** [mbostock/d3#2348]
When using the line generator with the interpolation mode set to monotone, i have noticed an error where the line on the x axis actually extends beyond the next point and curves back towards it.
You can see an example of this here http://jsfiddle.net/SamWhitby/enpqsua1/ on the line between the  second and third data point.
Any suggestions for a potential workaround would be greatly appreciated.
Thanks,
Sam.

**Comment by dcleao** [comment]
Probably related to this issue, I was trying to understand the monotone tangents calculation code, at https://github.com/mbostock/d3/blob/master/src/svg/line.js#L421, and I'm not getting it.

The cited derivatives calculation algorithm uses a non-parametric curve formulation. However, the function `d3_svg_lineHermite` uses a parametric curve formulation and, thus, requires tangent vectors, not only their slopes. The code that determines the tangents from the slopes says: "Compute the normalized tangent vector from the slopes". Normalized tangent vector?

I'd expect to see `sqrt(1 + mi^2)`, the _norm_ of a tangent vector built from `mi`, but I see `1 + mi^2`alone.
Then there's the divide by 6 — I guess this is 2*3: the hermite function is not dividing tangents by 3 as it probably should, because of the hermite to bézier transformation. The, 2, I guess, is for accounting for half of `dx`.
Could you please explain how this is derived?

**Comment by mbostock** [comment]
Related #2516.

**Comment by mbostock** [comment]
I’m planning on doing a complete rewrite of the interpolator code, and cubic interpolation in particular, for 4.0. That implementation was contributed early on in D3’s life, and upon closer inspection it looks like it’s doing some dubious things. (I also think we should provide [natural cubic spline](http://bl.ocks.org/mbostock/9bd540de6728a1fb9343) interpolation as `"cubic"`.) Going to punt on this for 3.5.7.

**Comment by mbostock** [comment]
I made a quick attempt at re-implementing cubic monotone in 222a32c3614e4c44f59ce7dc6af1b0be78b9e8b0 (the fix-monotone branch), but it’s a rough cut that will require greater review and testing.

**Comment by mbostock** [comment]
FYI, this is fixed in the new 4.0 monotone implementation by @jviide; see d3/d3-shape#38.

<img width="630" alt="screen shot 2015-11-29 at 6 53 07 pm" src="https://cloud.githubusercontent.com/assets/230541/11462542/bb4e8b9a-96ca-11e5-8510-e8254de275fa.png">

See [bl.ocks.org/8b9d3ce715cfaaa24fb4](http://bl.ocks.org/mbostock/8b9d3ce715cfaaa24fb4) for another example.

**Comment by dcleao** [comment]
Great news :-) Thanks.

**Comment by wayx** [comment]
Great!

**Comment by mbostock** [comment]
Closing as fixed for 4.0.
