### ISSUE TITLE
Brushing breaks down when using stroke-dasharray

### ISSUE THREAD

**Issue by derrickpelletier** [mbostock/d3#2388]
Primarily seeing this in Chrome, but happens to a lesser extent in Safari. (OSX)

I forked some other random example to show this:
http://bl.ocks.org/derrickpelletier/be6f4b5d378287ffc266

Seems like when you begin to drag for brushing, it ***appears*** to just lockup, but if you wait a bit, the brush window will appear to where you dragged. At this point dragging the window works fine. But if you drag it smaller, reducing the window, it starts to break down again.

So the issue seems to only be related to a small brush context/window while using dasharray...

I wouldn't know where to begin debugging this one, personally.

**Comment by mbostock** [comment]
Unfortunately this isn’t something D3 can fix directly.

The problem is with the general approach here is that if you use the brush to select a very small region of your data, you’re zooming into that small region and effectively magnifying the total area (or length) of the path. Even though most of that path is offscreen, the browser has to do a fair amount of work in order to render it.

So, I would recommend trying two things.

First, you could apply a clip path to the path. It looks like you might already be doing that, so assuming it’s working as intended this may not help. But my hope was that it might trigger a more efficient render path because the browser could avoid effort on offscreen path. However, due to the complexity of rendering dashed strokes, it’s conceivable that clipping can only be done after rendering the full dashed stroke, in which case it won’t improve performance.

Second, you could clip the data prior to rendering the path, so that the browser doesn’t waste time rendering parts of the path that are offscreen. Since you understand the nature of the path, it’s much easier for you to do this than for the browser to solve the general case: you just need to filter the data based on it’s *x*-value. You probably want to include a few extra points outside of the clip region to make sure that the data truncation isn’t visible.

If those don’t work, you could try using a pattern rather than a dashed stroke to produce a similar appearance. Otherwise you’ll just have to give up on dashed strokes. Which might be advisable anyway, as they can sometimes introduce visual vibration into your graphic.

**Comment by derrickpelletier** [comment]
Thanks for the detailed response.

I was already clipping the path, yeah, which is sort of necessary for the brushing—I would expect.

I'll give the data-clip a try though at a later date, but for now just going to give up. I would expect it wouldn't be very efficient as the clipping would have to happen on the fly for each mousemove event. I'll post any findings here if i ever get to it.
