### ISSUE TITLE
selection.data should modify the current selection, not return a new one.

### ISSUE THREAD

**Issue by mbostock** [mbostock/d3#2402]
It’s already the case that selection.data modifies the selected elements (by binding them to data). And that we use four-space indentation by convention for selection.data, even though it returns a new selection.

I’ve realized this is because conceptually, I think of selection.data as modifying the current selection, rather than returning a new selection. I can’t think of any instance where I’ve run selection.data and wanted to preserve the original selection prior to the data join.

In fact, in cases where I want to rebind data to a selection, it’s actually kind of a pain because you have to reassign that `var` after rebinding data. If selection.data modifies the selection, you don’t need to remember the reassignment. And this works nicely with enter.append modifying the selection, too!

**Comment by cool-Blue** [comment]
It's also handy for polymorphism on the selection, if you want to add some custom members to store state or add behaviour for example, currently you loose them after .data().  Not a good idea I guess, but it could provide a platform for more generalisation of transitions and selections internally.  
I also looked at jQueery for a bit of benchmarking and a fresh object is also returned there (like the way d3 currently does).  Interesting idea though...

**Comment by SeanMGonzalez** [comment]
This sounds like it might be addressing an issue I've had to work around with my custom forcegraph, but I'm not sure. The standard format for giving nodes to a force directed layout (http://bl.ocks.org/mbostock/4062045) is an array of objects, which can be linked to the DOM elements D3 creates by a parameter of those objects with code that looks something like:

force_data = yourSVG.selectAll('selector').data(nodes,function(return n.id));

This is great because if you remove a node from the input data "nodes", D3 will recognize that "id" is gone and via the enter() function will remove it from the DOM. However, if we update other parameters about that object, such as "value" that determines the size of each node using:

.append('circle').attr('r',function(d) {return d.value})

then the enter() function will not recognize it and and the subsequent code for styling it will not be called. This is currently handled by creating listeners or events which call a function that updates the attributes, but I wish I could rewrite the above data binding like this:

force_data = yourSVG.selectAll('selector')
    .data(nodes,function(d) {return {"id":n.id, "volume":n.volume}});

which I imagine could have a new function .update() be used instead of .enter() in certain situations.

I've pulled the d3 code and found where these binding are created, but before I attempt to make these changes and submit a pull request, I'd love to know if I'm misunderstanding something, if other people have run into this issue, if they prefer the current architecture, or anything that will help ensure that going down this path of forking the d3 code will bear fruit in the end.

**Comment by cool-Blue** [comment]
Why not do this?...
```javascript
    .data(nodes, function(d) { return d.id + "_" + d.volume})
```

**Comment by Rarirar** [comment]
Xhiş edirəm yerləşdirəsiniz.                                                                                                                                    http://github.com - automatic!
[GitHub](http://github.com)

**Comment by Rarirar** [comment]
# This is an <h1> tag*This text will be italic*
_This will also be italic_# This is an <h1> tag
## This is an <h2> tag
###### This is an <h6> tag


**This text will be bold**
__This will also be bold__

*You **can** combine them*

## This is an <h2> tag
###### This is an <h6> tag

**Comment by Rarirar** [comment]
*This text will be italic*
_This will also be italic_

**This text will be bold**
__This will also be bold__

*You **can** combine them*

**Comment by Rarirar** [comment]
* Item 1
* Item 2
  * Item 2a
  * Item 2b

**Comment by Rarirar** [comment]
1. Item 1
2. Item 2
3. Item 3
   * Item 3a
   * Item 3b

**Comment by Rarirar** [comment]
![GitHub Logo](/images/logo.png)
Format: ![Alt Text](url)

**Comment by Rarirar** [comment]
http://github.com - automatic!
[GitHub](http://github.com)

**Comment by Rarirar** [comment]
As Kanye West said:

> We're living the future so
> the present is our past.

**Comment by Rarirar** [comment]
I think you should use an
`<addr>` element here instead.

**Comment by Rarirar** [comment]
```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }

**Comment by Rarirar** [comment]
function fancyAlert(arg) {
      if(arg) {
        $.facebox({div:'#foo'})
      }

**Comment by Rarirar** [comment]
def foo():
    if not bar:
        return True

**Comment by Rarirar** [comment]
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

**Comment by Rarirar** [comment]
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

**Comment by Rarirar** [comment]
16c999e8c71134401a78d4d46435517b2271d6ac
mojombo@16c999e8c71134401a78d4d46435517b2271d6ac
mojombo/github-flavored-markdown@16c999e8c71134401a78d4d46435517b2271d6ac

**Comment by Rarirar** [comment]
#1
mojombo#1
mojombo/github-flavored-markdown#1

**Comment by cool-Blue** [comment]
please stop spamming this thread... selection.data should modify the current selection, not return a new one. · Issue #2402 · mbostock/d3
|   |
|   |  |   |   |   |   |   |
| selection.data should modify the current selection, not ...It’s already the case that selection.data modifies the selected elements (by binding them to data). And that we use four-space indentation by convention for selecti... |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |

  


     On Friday, 1 May 2015, 16:48, R.B.Muradov <notifications@github.com> wrote:
   

 function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }—

**Comment by Rarirar** [comment]
First Header | İkinci Header ------------ | ------------- hüceyrə 1 Content | Ilk sütun hüceyrə 2 məzmun

**Comment by Rarirar** [comment]
16c999e8c71134401a78d4d46435517b2271d6ac mojombo @ 16c999e8c71134401a78d4d46435517b2271d6ac mojombo / github ətirli-markdown @ 16c999e8c71134401a78d4d46435517b2271d6ac

**Comment by Rarirar** [comment]
# 1 mojombo # 1 mojombo / github ətirli-markdown # 1

**Comment by Rarirar** [comment]
(Kimi hər hansı bir URL http://www.github.com/ ) avtomatik olaraq tıklanabilir link çevrilir olunacaq.

**Comment by SeanMGonzalez** [comment]
Won't that just delete the previous node and add a new one? There are fields for each node that are computed, such as xy position of the node as well as related links, which would have to be transferred to the new node instead of just updating the fields of the existing one. This could be as simple as transitioning colors based on a user action, or transitioning from a circle to a star inside a g element.

**Comment by cool-Blue** [comment]
Hmmm, OK, I think maybe I don't understand you...
Your talking about removing nodes via the `enter()` (not `exit()`) function which I don't get...  
And then your using `n.id` when I thought it should be `d.id` maybe?

If your talking about exiting and entering nodes when either of a number of different values have changed, then you can make a multi-dimensional key (but you have to allow for the two phases of the data binding) like this...
```javascript
function key(d, i, j) {
	return d.name + "_"
		+ (Array.isArray(this) ? d.value.toPrecision(6) : d3.select(this).select("circle").attr("r"))
}
```  

But yes, its a new object and has to be re-initialised as per normal in the general update pattern.  I would have thought that was manageable with the `enter` and `exit` methods.

Is that different from what you are saying?  Or are you talking about a _soft_ update that acts only on specified attributes maybe?

**Comment by mbostock** [comment]
As of [d3-selection 0.7](https://github.com/d3/d3-selection/releases/tag/v0.7.0) selections are immutable and *selection*.data returns a new selection. There’s also a *selection*.merge method for combining enter and update after appending.
