### ISSUE TITLE
Click events don't work in Chrome 

### ISSUE THREAD

**Issue by nileshtrivedi** [mbostock/d3#2404]
Check this URL in both Firefox 37.0.1 and Chrome 41.0: https://www.qplum.co/d3.html

Mousehover events work fine in both browsers. But in Firefox, you can click on a circle and that asset gets selected over all 6 charts. This does not work in Chrome. No JS errors are thrown, and no message is printed in the console.

**Comment by mbostock** [comment]
This is not enough information for me to investigate (without dissecting your code to extract a smaller example that demonstrates the problem), so you should try Stack Overflow if you want help. I suspect that the problem may be related to your blur/focus handlers. Clicking and cause items to change focus, and perhaps that’s interfering with a reliable click. Also, I would make sure that the circles that you want to click on have the pointer-events: all style on them so that they are clickable even if they are only stroked and not filled.
