### ISSUE TITLE
X-axis transition logging NaN-error in console

### ISSUE THREAD

**Issue by leonhooijer** [mbostock/d3#2406]
When I transition the X-axis a error is logged at the console (*translation might be a bit incorrect because it is logged in my own language*):
```
Unexpected value "translate(NaN, 0)" when parsing transform-attribute
```

The error seems to originate from [axis.js:154](https://github.com/mbostock/d3/blob/master/src/svg/axis.js#L154). Although an error is logged, everything works fine.

I have debugged the problem and found that at line 154 `d` is `undefined`. This results in the following:
```javascript
var v0 = x0(d); //v0 = NaN
isFinite(v0) //false
x1(d) //NaN
(isFinite(v0) ? v0 : x1(d)) // false ? NaN : NaN -> Always returns NaN
return "translate(" + (isFinite(v0) ? v0 : x1(d)) + ",0)" //Always returns "translate(NaN, 0)" for d = undefined
```

I use version 3.5.5 of D3 and my code is as follows (only relevant parts):
```javascript
var x = d3.scale.linear().range([0, getWidthWithoutMargin()]);

var xAxis = d3.svg.axis();
xAxis.scale(x);
xAxis.orient("bottom");
xAxis.tickFormat(formatFunction);
xAxis.ticks(1);

x.domain([0, getMaxPercentagePrediction()]);

//The chart is created after this

//When updating I do this:

xAxis.tickValues([0, getMaxPercentagePrediction()]);

var xAxisElement = d3.select(".chart g").select(".x.axis");
    xAxisElement.call(xAxis);
```

I hope anyone can help me with this issue.

Thanks in advance!

**Comment by ameyms** [comment]
:+1:

**Comment by mbostock** [comment]
If `d` is undefined here, it means that one or more of the selected ticks does not have bound data, or that the bound data is the value `undefined` rather than the expected numeric value from the scale’s domain, such as a value returned by [linear.ticks](https://github.com/mbostock/d3/wiki/Quantitative-Scales#linear_ticks).

This suggests that `getMaxPercentagePrediction()` may be returning undefined in your code. Is that possible? Like, maybe it returns `undefined` before your chart is created due to an initialization ordering problem? Another less-likely possibility is that you are inserting tick elements (an element with the class “tick”) into the axis G element, and those elements don’t have bound data.

Without a standalone example that demonstrates this issue, it’s difficult for me to investigate further. I’m not able to reproduce this error based solely on your code. See [bl.ocks.org/91f879ec5eaca9bb8266](http://bl.ocks.org/mbostock/91f879ec5eaca9bb8266).
