### ISSUE TITLE
zoom Behavior, dblclick does not provide an event

### ISSUE THREAD

**Issue by langdonx** [mbostock/d3#2411]
Was removing the event on `dblclick` in the Zoom behavior intentional here?

https://github.com/mbostock/d3/commit/60df29662570a7d454b2f709226a8db19c0c5e76#diff-8a5d2f6d536a2448e970d4de069dc30a

I've been on 3.4.8 for a while, but just upgraded to 3.5.5.  My code was checking d3.event.sourceEvent and doing something based on the type, but the sourceEvent is null now when double click is used as opposed to mouse wheel.

    // causes Uncaught TypeError: Cannot read property 'type' of null
    if (wheelEvent.type === 'wheel' || wheelEvent.type === 'mousewheel') {

**Comment by mbostock** [comment]
Yes. The sourceEvent went away because the double-click now triggers a zoom transition rather than an immediate zoom. (And I don’t believe it makes sense for these delayed events to have a source event, given the source event happened in the past. All other source events occur within the lifecycle of the source event, so that you can, for example, prevent default behaviors.)

You can still listen to dblclick events yourself, optionally with capture, and stop propagation to prevent the zoom behavior from responding to them.

I’m not sure what exactly you’re trying to do, but feel free to reply if you have more questions.
