### ISSUE TITLE
Ticks without svg

### ISSUE THREAD

**Issue by rbhalla** [mbostock/d3#2445]
I'm attempting to use d3's time scale methods to do some date range calculations but I'm struggling to find any documentation past using it with svg.

Given a certain date range I'd like to output an array of intervals along that date range. From my cursory reading of the documentation I assumed something like this:

```
var ticks = d3.time.scale()
      .domain(["2015-05-07T02:22:29.000Z", "2015-05-21T12:38:57.000Z"])
      .ticks(d3.time.days, 1);
```

should work, but it only outputs an empty array. Is this possible with d3? If so how would I approach this problem?

**Comment by mbostock** [comment]
If you just want an array of dates, you probably want to use the [time intervals](https://github.com/mbostock/d3/wiki/Time-Intervals). For example:

```js
var start = new Date("2015-05-07T02:22:29.000Z"),
    end = new Date("2015-05-21T12:38:57.000Z");
console.log(d3.time.days(start, end));
```

If you want a time scale (for visualization purposes—scales map data to visual encodings, such as dates to pixel positions), then you need to invoke [scale.ticks](https://github.com/mbostock/d3/wiki/Time-Scales#ticks) with no arguments to have it compute the ticks. If you call scale.ticks with arguments, you’re telling it what type of ticks you want, but those ticks aren’t actually computed until you call scale.ticks without arguments. (And often the latter happens automatically when you use a scale in conjunction with [an axis](https://github.com/mbostock/d3/wiki/SVG-Axes).)

If you want more help, I’d recommend Stack Overflow tag d3.js. I often don’t reply to support requests here, as these issues are intended for bug reports and feature requests.

**Comment by rbhalla** [comment]
@mbostock Thanks for your response. I would have normally, my intention was if this feature was missing I would have used this issue to reference a PR.

I'm still slightly confused though, what is `scale` equal to exactly? Is it not `d3.time.scale()` with domain values so ticks can be calculated across the domain as in my initial question?

**Comment by mbostock** [comment]
The immediate problem is that you are using strings to represent dates when you need to be using Date objects. (You can also use UTC milliseconds since epoch, but Date objects are preferred.) The problem is easy to see if you look at the scale’s domain:

```js
var scale =  d3.time.scale()
    .domain(["2015-05-07T02:22:29.000Z", "2015-05-21T12:38:57.000Z"]);

scale.domain(); // [Invalid Date, Invalid Date]
```

You can use the Date constructor to parse these dates:

```js
var scale =  d3.time.scale()
    .domain([new Date("2015-05-07T02:22:29.000Z"), new Date("2015-05-21T12:38:57.000Z")]);

scale.ticks();
```

But slightly more reliable is to use d3.time.format.iso, since not all browsers support parsing ISO 8601 timestamps in the Date constructor:

```js
var scale =  d3.time.scale()
    .domain([
      d3.time.format.iso.parse("2015-05-07T02:22:29.000Z"),
      d3.time.format.iso.parse("2015-05-21T12:38:57.000Z")
    ]);

scale.ticks(d3.time.days);
```

Using a scale just for the purpose of computing ticks is a bit overkill (scales are primarily intended for mapping data to visual encodings, such as dates to pixel positions in a time series chart). That’s especially true in this case because you are explicitly specifying the time interval you want: days.

So if you just want an array of dates, you probably want to use a [time interval](https://github.com/mbostock/d3/wiki/Time-Intervals) instead. For example:

```js
var start = d3.time.format.iso.parse("2015-05-07T02:22:29.000Z"),
    end = d3.time.format.iso.parse("2015-05-21T12:38:57.000Z");

d3.time.days(start, end);
```

If you want more help, I’d recommend Stack Overflow tag d3.js. I often don’t reply to support requests here, as these issues are intended for bug reports and feature requests.

**Comment by rbhalla** [comment]
@mbostock Thank your for your help, and apologies for turning this into a support request. That response was extremely helpful.
