### ISSUE TITLE
Initialize a color through an object like d3.rgb({r:1, g:2, b:3})

### ISSUE THREAD

**Issue by e-** [mbostock/d3#2457]
Hello,

I am working on a JSON dataset whose color values are encoded with an object like this:

```js
{
	"car": [
		{
			"name": "abc",
			"color": {
				"r": 10,
				"g": 20,
				"b": 30
			}
		},
		...
	]
}
```

When I create an instance of color, I wrote something like this:
```js
d3.rgb(car.color.r, car.color.g, car.color.b);
```

I think it would be better If I could do that like this:
```js
d3.rgb(car.color);
```

This can be also applied to other color schemes such as HCL or Lab. What do you think about this?

Thanks.

**Comment by mbostock** [comment]
Unfortunately, I think this would make an already messy task messier. The problem is that color constructors already have to deal with a variety of overloaded arguments: a typical constructor such as d3.rgb can either be called in three-argument form (`d3.rgb(r, g, b)`) or be in one-argument from. In the latter case, the argument is either a string or a color instance. If it’s a string, it has to be parsed (and possibly converted from HSL). If it’s a color instance, the instance can be in any colorspace, and the appropriate conversion needs to happen.

D3 checks what colorspace an instance is in by using the `instanceof` operator. For example, `x instanceof d3.hsl` will tell you whether `x` is an HSL color. If we allow arbitrary objects to be passed to the constructor, we need some other way of determining what colorspace the input object is in. (Or maybe we just assume that it’s the same colorspace as the constructor, but that seems like a half-measure that could easily confuse callers.) I suppose you do something like this:

```js
if (("r" in x) && ("g" in x) && ("b" in x)) {
  console.log("x is an RGB color);
}
```

But that’s a bit more cumbersome than saying:

```js
if (x instanceof d3.rgb) {
  console.log("x is an RGB color);
}
```

Plus, it’s nice that the color constructors are consistent with d3.interpolate, which looks for strings that represent colors and instances of d3.color. (Of course, d3.interpolate can also interpolate arbitrary objects, so you can pass an `{r, g, b}` object and it will do what you expect. But it won’t automatically convert an `{h, s, l}` object to RGB colorspace before interpolating, as it does with things it knows are colors.)
