### ISSUE TITLE
transition.transition() documentation may need updating for version 3.5

### ISSUE THREAD

**Issue by Chris-Andrews** [mbostock/d3#2460]
Hi, I've been struggling with something that may actually be working as intended, but doesn't seem consistent with the current documentation. I can't get transitions to chain properly using transition.transition(). When I run: 

```javascript
var transition = d3.transition('first')
  .delay(0)
  .duration(200)
  .each('start',function(){
    console.log('parent transition starts');
  })
  .each('end',function(){
    console.log('parent transition completed');
  })
  .each('interrupt',function(){
    console.log('parent transition interrupted');
  })
  .transition('next')
  .delay(100)
  .duration(0)
  .each('start',function(){
    console.log('next transition starts');
  })
  .each('end',function(){
    console.log('next transition completed');
  })
  .each('interrupt',function(){
    console.log('next transition interrupted');
  });
```
I am expecting the second (*next*) transition to start after the first is completed, based on the documentation:
> # transition.transition()

> Creates a new transition on the same selected elements that starts when this transition ends. The new transition inherits this transition’s duration and easing. This can be used to define chained transitions without needing to listen for "end" events.

However, my console is logging out:
>parent transition starts
>parent transition interrupted
>next transition starts
>next transition completed

I am wondering if the documentation is out of date, since version 3.5 seems to have introduced named transitions. I get this behavior with or without the transition names.

When I make a small change to the code:
```javascript
var transition = d3.transition('first')
  .delay(0)
  .duration(200)
  .each('start',function(){
    console.log('parent transition starts');
  })
  .each('end',function(){
    console.log('parent transition completed');
  })
  .each('interrupt',function(){
    console.log('parent transition interrupted');
  });
d3.transition('next')
  .delay(100)
  .duration(0)
  .each('start',function(){
    console.log('next transition starts');
  })
  .each('end',function(){
    console.log('next transition completed');
  })
  .each('interrupt',function(){
    console.log('next transition interrupted');
  });
```
My console logs out:
>parent transition starts
>next transition starts
>next transition completed
>parent transition completed

Is this the intended behavior? I can't seem to do anything to get transition.transition() working in what seems to be the old way, where the second transition will begin after the first ends. The named transition method should work fine, but then I'm not sure about how timing synchronization works. Is it possible to synchronize two named transitions on a single element without seeing any clock drift?

Thanks,
-Chris

**Comment by mbostock** [comment]
The issue is that you are setting the delay of 100ms: this time is relative to the *first* transition in a chain, so your second transition interrupts the first.

The way transition.transition works is that it initializes the delay of the new transition based on the previous transition’s delay and duration. So, if you explicitly set the delay, you are changing how the chained transitions are scheduled, and in this case causing the transitions to overlap.

If you want to have a 100ms gap between the chained transitions, I recommend using a no-op transition of duration 100ms, and then scheduling you transition:

```js
var start = Date.now();

d3.transition()
    .duration(200)
    .each("start", function() { console.log("transition 1 started", Date.now() - start); })
    .each("end", function() { console.log("transition 1 ended", Date.now() - start); })
  .transition()
    .duration(100)
  .transition()
    .each("start", function() { console.log("transition 3 started", Date.now() - start); })
    .each("end", function() { console.log("transition 3 ended", Date.now() - start); });
```

This generates the following output when I tested:

```
transition 1 started 11
transition 1 ended 211
transition 3 started 311
transition 3 ended 410
```

(Note that transition 3 inherits transition 2’s duration of 100ms.)

I’ll leave this bug open as a documentation request. Please feel free to edit the wiki to clarify the behavior if the above description made sense!

**Comment by mbostock** [comment]
As for the reason in your second example the “next” transition does not interrupt the “first”: it is because you gave the transitions distinct names (“first” and “next”). Transitions only interrupt other transitions on the same element at the same time with the same name. (See the [named transitions example](http://bl.ocks.org/mbostock/5d8039fb983a29e2ad49).)

The reason this doesn’t apply when you used [transition.transition](https://github.com/mbostock/d3/wiki/Transitions#transition) is that this method doesn’t take a name argument, so the “next” name you specified is being ignored.

I suppose it would be possible for transition.transition to take a name, although it doesn’t make much sense to chain transitions with different names. Chaining implies the transitions should be sequential, while naming implies the transitions should be parallel.

**Comment by Chris-Andrews** [comment]
Thanks for the great explanation. What you described is how I initially thought everything would work, except that I didn't understand that a delay is always relative to the first transition in a chain. There were a minor points of confusion related to the named transitions, because some of the older documentation states things like:
>Only one transition may be active on a given element at a given time. However, multiple transitions may be scheduled on the same element; provided they are staggered in time, each transition will run in sequence. If a newer transition runs on a given element, it implicitly cancels any older transitions, including any that were scheduled but not yet run. 

It seems like this was the behavior before named transitions, whereas now the behavior is that only one transition of a given name may be active on a given element at a given time. I will try my hand at editing the wiki to hopefully clarify some of these details based on this discussion.

**Comment by Chris-Andrews** [comment]
I edited the wiki based on this discussion. I hope the edits are helpful and accurate. This issue can be closed unless there is a problem with my edits.

**Comment by mbostock** [comment]
:+1:
