### ISSUE TITLE
Bubble Chart #4063269 cannot combine on.click with bubbles

### ISSUE THREAD

**Issue by FRadice1977** [mbostock/d3#2506]
I would like to make the SVG circles clickable to a HTTP address. I believe that the code must changed in the JSON like this. 

{"name":"Research", "address": "http://github.org"}

In the index file I have added the on.click method to an address. However the address is never called. It only opens to an un titled blank new web page. 

What would one have to add to the index.html file other than, 

.on("click", function (d, i) {window.open(d.address); --- to get the nodes to click to a URL?

**Comment by tristanreid** [comment]
Hi there.  I think you're on the right track - your problem is that in the bubble chart there is a transformation of the nodes - the original properties are renamed in the new hierarchical structure.  You can fix your example by simply adding your address property (I used 'url' instead of address, simply because I wasn't paying attention, please ignore/change as you see fit).  This is the code from the bottom of the bubble chart example, with the url property added:

```
// Returns a flattened hierarchy containing all leaf nodes under the root.
function classes(root) {
  var classes = [];

  function recurse(name, node) {
    if (node.children) node.children.forEach(function(child) { recurse(node.name, child); });
      else classes.push({packageName: name, className: node.name, url: node.url, value: node.size});
  }

  recurse(null, root);
  return {children: classes};
}
```

Here's a fiddle with a working example:  http://jsfiddle.net/tristanreid/3svp3eyj/

**Comment by tristanreid** [comment]
I believe this issue should be closed - it's not an issue with D3 and it's also resolved.
