### ISSUE TITLE
Axis data shows problem when I rescale it?

### ISSUE THREAD

**Issue by hijiangtao** [mbostock/d3#2514]
I use data like this format to generate my svg chart, at first the axis shows normally. The follow is a single part in dataset:

    {time: '10:01', used: 200, extra: 500, total: 1000}

Then I use a random algorithm to generate more data into exist dataset, but I control the length of data not larger than 60:

    data.push({time: '10' + ":" + mAxis, used: Math.random()*1000, extra: Math.random()*1000, total: 1000});
    // console.log(tAxis);
    mAxis++;
    if (Object.keys(data).length === 60) data.shift();

I use following method to redraw the axis:

    x.domain(d3.extent(data, function(d) { 
        return d['time']; 
    }));

    svg.select(".axis")
         .transition()
         .duration(500)
         .ease("sin-in-out")
         .call(xAxis);

I am wondering where are the problems that cause the axis problem in a few time later?
The following pic is the normal axis and the problem axis. The problem shows that the axis could add to 11:35 at most, then couldn't push more.
Thanks a lot!

<img width="838" alt="screen shot 2015-08-06 at 17 34 28" src="https://cloud.githubusercontent.com/assets/4990015/9108657/41d42170-3c62-11e5-811d-0469aaa38135.png">

<img width="847" alt="screen shot 2015-08-06 at 17 34 20" src="https://cloud.githubusercontent.com/assets/4990015/9108662/46a99306-3c62-11e5-97a8-f48ce6fa4bcd.png">

<img width="809" alt="screen shot 2015-08-06 at 17 39 21" src="https://cloud.githubusercontent.com/assets/4990015/9108664/4b3e3bba-3c62-11e5-93ce-da5fc54b4e6c.png">

**Comment by mbostock** [comment]
This looks like a support issue rather than a bug report, so you might try Stack Overflow or the d3-js Google group for help. My guess is that your transitions are getting interrupted. If you create a new transition before the old transition ends, it will interrupt the old transition and may prevent the removal of exiting elements. For example, if you use a setInterval with a delay of 500, that probably won’t be enough time for a 500ms transition to finish. Better is to listen to the transition end event, and then start a new transition. (Or use a chained transition.)

Alternatively, if you want a realtime chart, use d3.timer instead of transitions, and continuously refresh the domain based on the current time.
