### ISSUE TITLE
zoom.event transition initial state

### ISSUE THREAD

**Issue by cool-Blue** [mbostock/d3#2521]
I'm sure there is a very good reason but I'm wondering why the zoom state is crashed back to {x: 0, y: 0, k: 1} at the start of the first zoom event.  This causes the view to jump back to zero before transitioning to the target.  It only happens on the first transition when `__chart__` is not yet established but its not what you want to happen really.  

### Current code ###
```js
  zoom.event = function(g) {
    g.each(function() {
      var dispatch = event.of(this, arguments),
          view1 = view;
      if (d3_transitionInheritId) {
        d3.select(this).transition()
            .each("start.zoom", function() {
              view = this.__chart__ || {x: 0, y: 0, k: 1}; // pre-transition state
              zoomstarted(dispatch);
            })
```

Would it be ok to get the current state of the zoomed element (`this`) and initialise the first transition with that state?

### Suggested patch ###
```js
		zoom.event = function(g) {
			g.each(function() {
				var dispatch = event.of(this, arguments), view1 = view;
				if (d3_transitionInheritId) {
					d3.select(this).transition().each("start.zoom", function() {
						var t = d3.transform(d3.select(this).attr("transform"));
						view = this.__chart__ || {
								x: t.translate[0],
								y: t.translate[1],
								k: t.scale[0]
							};
						zoomstarted(dispatch);
					})
```

My hacked solution currently is to do the exact same thing on the `zoomstart` event but it's a bit wasteful (although not hot code admittedly).  I could hack my way down to `__chart__` but it's not really part of the API so I don't bother.  
### Current work-around ##
```js
	function onZoomStart(){
		// zoom translate and scale are initially [0,0] and 1
		// this needs to be aligned with the container to stop
		// jump back to zero before first jump transition
		var t = d3.transform(container.attr("transform"));
		zoom.translate(t.translate); zoom.scale(t.scale[0]);
	}
```

**Comment by mbostock** [comment]
Right, the zoom behavior assumes the identity transform if it’s uninitialized. Trying to infer the state by parsing the transform attribute wouldn’t work—this attribute isn’t guaranteed to represent the zoom state accurately, since the listener can do whatever they want in the zoom event callback (such as setting a CSS transform style rather than the SVG transform attribute).

You should be able to use `selection.call(zoom.event)`, though, to initialize the zoom state. Like in [this example](http://bl.ocks.org/mbostock/9656675).
