### ISSUE TITLE
d3.rgb() incorrectly parses hex string values when used as a map() callback

### ISSUE THREAD

**Issue by clayzermk1** [mbostock/d3#2534]
#### Context
I wanted to make a custom color scale, so I used [`d3.scale.category10()`](https://github.com/mbostock/d3/blob/5b981a18db32938206b3579248c47205ecc94123/src/scale/category.js#L29) as an example. `category10()` uses `d3_rgbString()` as a map callback. Not having access to that function directly, I figured I would use `d3.rgb()` since it seems like an ideal iterator and [the documentation for a color string](https://github.com/mbostock/d3/wiki/Colors#d3_rgb) doesn't explicitly say it shouldn't be used as such.

For reference, my code looks like this:
```javascript
['#b3dbf4', '#2894cf'].map(d3.rgb);
```

#### Problem
[`Array.map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Parameters) passes three arguments to its callback function. `d3.rgb()` does [a check for `arguments.length < 2`](https://github.com/mbostock/d3/blob/5b981a18db32938206b3579248c47205ecc94123/src/color/rgb.js#L11) which in this case will always be `false`, which in turn causes `d3.rgb()` to return a new instance of itself with incorrect RGB values. Note that `g` is set to the map index parameter.

Previous example with output:
```javascript
['#b3dbf4', '#2894cf'].map(d3.rgb); // [ {"r":0,"g":0,"b":0}, {"r":0,"g":1,"b":0} ]
```

#### Expected
I expect the map function to return the correct RGB values for the array elements.

Previous example with expected output:
```javascript
['#b3dbf4', '#2894cf'].map(d3.rgb); // [ {"r":179,"g":219,"b":244}, {"r":40,"g":148,"b":207} ]
```

---

Once I figure out why the arguments length check is being performed, I'll try to whip up a PR.

Thank you for such a killer visualization package! :beers:

**Comment by tristanreid** [comment]
I think you want rgbString?

**Comment by clayzermk1** [comment]
@tristanreid Thank you for the response. My apologies though, I'm not looking for a solution (I'm fine just returning the hex strings for my purposes). I just noticed this while playing with the color scales and thought it odd / a shame and figured I would report it. If nobody cares, this case may be closed.

**Comment by mbostock** [comment]
Thanks for raising this issue. I don’t consider this behavior a bug but an ambiguity caused by the overloaded signature of d3.rgb. Specifically:

* d3.rgb(*r*, *g*, *b*) constructs a color for *r*, *g* and *b* channel values
* d3.rgb(*string*) constructs a color from the specified color specifier *string*

(I’m simplifying slightly: d3.rgb can also accept a single argument that is another color, which is then coerced to a string if it is not already RGB, for conversion from other color spaces.)

The two versions of d3.rgb are disambiguated by the number of arguments. If you call d3.rgb with three arguments you get the first version; if you call it with one argument you get the second version; anything else has undefined behavior. This is implied by the [d3.rgb documentation](https://github.com/mbostock/d3/wiki/Colors#d3_rgb), but things are always going to be a little vague given the nature of JavaScript.

Now note that [array.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) invokes the specified callback with three arguments: an array *element*, the corresponding array *index*, and the *array* itself. Thus, this form is interpreted as d3.rgb(*r*, *g*, *b*) and not d3.rgb(*string*).

You could argue that we should use type inference (`typeof r === "string"`, e.g.) rather than argument length checking to disambiguate. However, I prefer argument length checking because it is less ambiguous: it can be determined statically by looking at the code, rather than needing to know the runtime type of a value. Also, note that it’s easy for values to be strings unexpectedly in JavaScript—for example when loading data from a CSV file. Coercing values to numbers is desirable in these cases.

At any rate, you can’t always disambiguate perfectly. I like the argument length strategy, and I think it’s also good to apply that strategy consistently rather than try to special-case the method behavior for array.map.

**Comment by clayzermk1** [comment]
@mbostock Thanks for the official word. I played around with type checking but ran into edge cases (as you point out) in the tests. Seeing as you prefer the argument length checking, I'll just leave it be. Thank you for your time :smile:
