### ISSUE TITLE
d3.time.format "everything larger than minutes displayed as hours"

### ISSUE THREAD

**Issue by ccoenen** [mbostock/d3#2535]
I would like to display *time ranges*. They will usually be a few minutes to a few hours, but in some cases those ranges may span across more than a day. In that case, I would prefer to display **26:59** (as in 26hours 59min) instead of *1day 2:59*.

I have two (similar) use cases:

* Displaying the duration of something on a dashboard
* Summarizing work-hours for a report (in this case I would REALLY like to avoid displaying days, as it would be confusing to distinguish between 24h days and 8h workdays).

I am not sure if this is too rare a case to be included in an api, I'd be happy with a workaround, too.

**Comment by ccoenen** [comment]
my current workaround is this, but it does not do all that i want:

```
		var timeformat = d3.time.format.utc.multi([
			["%Ss", function (d) {return (+d) < 60*1000;}],
			["%M:%Smin", function (d) {return (+d) < 60*60*1000;}],
			["%H:%Mh", function (d) {return (+d) < 24*60*60*1000;}],
			["1d %H:%Mh", function (d) {return (+d) < 48*60*60*1000;}],
			["2 days or more", function (d) {return true;}]
		]);
```

**Comment by mbostock** [comment]
Well, d3.time.format is for formatting dates: specific, absolute moments in time. You’ll want a different API for formatting durations.

And then there’s the question of whether you want to represent durations in terms of irregular human time intervals (such as “1 day” which may or may not be precisely 86,400,000 milliseconds depending on your time zone and daylight saving) or as a precise number of milliseconds. The latter is certainly simpler since you can use a number, but it might not be what you mean. In either case a JavaScript Date is probably not appropriate for representing a duration.

So… It might be reasonable to add some new API for this purpose, but it would be separate from d3.time.format.

In the interim, you might also consider using [Moment.js’s durations](http://momentjs.com/docs/#/durations/).

**Comment by ccoenen** [comment]
thanks for your suggestion. I didn't consider moment so far, as I thought it was doing basically the same thing. But durations are almost what i want. I have now settled for

```
function durationFormat(duration) {
	var m = moment.duration(duration);
	var hours = Math.floor(m.asHours());
	var minutes = m.minutes();
	var seconds = m.seconds();
	return "" + (hours > 0 ? hours+"h " : "") + minutes + 'm ' + seconds + 's';
}
console.log(durationFormat((+end) - (+start))); // "79h 12m 17s"
```

(just in case i'll turn up here via google in a year or two :o) )
