### ISSUE TITLE
transition.text is not tween

### ISSUE THREAD

**Issue by ming-codes** [mbostock/d3#2557]
Looking at the source shows this seems to be on purpose.

Any particular reason for this?

**Comment by mbostock** [comment]
Generally speaking, it’s because it’s not possible to smoothly transition displayed text, and doing so by default would be distracting. You can interpolate the numbers in the text, but that’s not perceived as a smooth transition in the same way as interpolating position or color is. So, D3 simply replaces the text at the start of the transition.

You can still interpolate text using transition.tween, if you want.
