### ISSUE TITLE
How to use the function of timescale.tickFormat(count)

### ISSUE THREAD

**Issue by tianxuzhang** [mbostock/d3#2560]
What's the meaning of the input param:count?

in WIKI https://github.com/mbostock/d3/wiki/Time-Scales#tickFormat this method is:
scale.tickFormat(count) 

but in the source code of d3 V3.5.5 this method is:
scale.tickFormat = function() {
      return format;
};
Why is different? Can you give me an example about how to use this method?

**Comment by Wooyol** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

neolaocoon@naver.com 님께 보내신 메일 <[d3] How to use the function of timescale.tickFormat(count) (#2560)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by mbostock** [comment]
The tickFormat method on a time scale doesn’t take a count; that was a copy-and-paste error from linear scales, which do. In the case of a linear scale, it corresponds to the suggested number of ticks, and affects the precision of the resulting format. However, time scales are formatted independent of precision—the format depends only on the time being formatted.

(Side note: this was already fixed in the [d3-time documentation](https://github.com/d3/d3-scale#time-scales) for 4.0.)
