### ISSUE TITLE
Bug with svg marker-end(url) and html BASE tag

### ISSUE THREAD

**Issue by Daijobou** [mbostock/d3#2563]
All libraries with d3 as backbone have the same problem with arrows:
~~~~~
<path marker-end="url(#arrowhead12)">
~~~~~
With BASE tag in HEAD this will cause that arrows not appear.

I found this answer in stackoverflow:
http://stackoverflow.com/questions/18259032/using-base-tag-on-a-page-that-contains-svg-marker-elements-fails-to-render-marke

Its possible to add "location.href" directly in d3 for solving this problem?
hint: "location.href" without a possible (#)fragment part. => http://domain.tld/folder/file.html#fragment ;)

**Comment by mbostock** [comment]
As painful as this is, I don’t see a good way of masking this problem in D3. It would complicate the logic of selection.attr significantly to detect when such a URL-type attribute was being set, and then you’d need to parse and reformat the attribute value safely. And even this wouldn’t mask the problem entirely, since if you were statically authoring SVG inline within HTML (without using D3), you’d still have to remember to format your URLs absolutely. Part of the design philosophy of D3 is that it is not a compatibility layer, so that means the underlying representation is apparent, warts and all.

Probably best to avoid BASE tags if you want to avoid this problem… :frowning:
