### ISSUE TITLE
automatic ceiling error for large numeric values in d3.scale.linear() (and/or d3.svg.axis)

### ISSUE THREAD

**Issue by sunwoosf** [mbostock/d3#2570]
```
...
var xscale = d3.scale.linear()
                      .domain(d3.extent(my_data, function(d) { 
                                                           console.log("my_val " + d.my_val); 
                                                           return d.my_val })
                                    )
                     .range([0, width]);
```
The above code produces the following output.
     my_val 34200007505 
     my_val 34200007507
     my_val 34200007601
     my_val 34200007875
     my_val 34200008702
     ...
However, the following code produces 
    !!! fmt_val ===> 34200100000
    !!! fmt_val ===> 34200200000
    !!! fmt_val  ===> 34200300000
    !!! fmt_val  ===> 34200400000
    ...
As you can see,   
   34200007505  is converted 34200100000.
How can I prevent this kind of automatic rounding problem ?
```
 var fmtVal = function(d) {
                        console.log("!!! fmt_val ===> " + d);
 }
var xaxis = d3.svg.axis().scale(xscale).orient("bottom").ticks(10).tickFormat(fmtVal);
var focus = svg.append ("g")
                        .attr("class", "focus")
                        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");
focus.append("g")
                .attr("class", "x axis")
                .attr("transform", "translate(0," + height + ")")
                .call(xaxis);

**Comment by mbostock** [comment]
In the first case, when using [d3.extent](https://github.com/mbostock/d3/wiki/Arrays#d3_extent), your accessor function is passed each element in your data array (e.g., `my_data[0]`).

In the second case, when using [axis.tickFormat](https://github.com/mbostock/d3/wiki/SVG-Axes#tickFormat), your tick format function is passed each generated tick value. If the axis’ scale (`xscale`) is a linear scale, then these will be approximately ten evenly-spaced round values within the scale’s extent, which is the highest and lowest value in the scale’s domain. (In the simplest case where the domain only has two values, the scale’s extent and domain are the same.)

So, if your data has values like `[3.2, 8.1, 9.5, 1.2, 1.4]`, then the domain and extent would be `[1.2, 9.5]`, since 1.2 is the smallest value and 9.5 is the largest value. If you ask for ten ticks in this domain, you get this:

```js
d3.scale.linear().domain([1.2, 9.5]).ticks(10) // [2, 3, 4, 5, 6, 7, 8, 9]
```

Note that fewer than ten ticks are returned (because the argument to [linear.ticks](https://github.com/mbostock/d3/wiki/Quantitative-Scales#linear_ticks) is merely a hint) and that they are rounded to the nearest integer value.

The values passed to the tick format function are rounded because ticks are rounded. If you don’t want rounded ticks, you can use [axis.tickValues](https://github.com/mbostock/d3/wiki/SVG-Axes#tickValues) to specify your own custom tick values. (You can also provide your own scale implementation, but that’s more work.)

Since this is more of a support question than a bug report or feature request, I’m closing this issue, but please respond if I haven’t answered your question. Out of curiosity, why do you not want rounded tick values?

**Comment by ajgreenb** [comment]
We're charting a time series and we want our X-Axis to reflect the precise microseconds for which we have data. Thanks for answering this!

**Comment by mbostock** [comment]
Makes sense. Thanks.
