### ISSUE TITLE
'jsdom' breaks on `npm install` on 3.5.x version

### ISSUE THREAD

**Issue by iyogeshjoshi** [mbostock/d3#2578]
I cloned the master repo which seems to be on '3.5.6' version, when I tried installing node dependencies using `npm install` it is failing throwing this error: [npm install console log](https://gist.github.com/iyogeshjoshi/d9fa6840754a284922ff).

But if I install jsdom manually using `npm install jsdom@latest` it's getting installed properly. So if there are no restriction of using the specific jsdom can we upgrade to jsdom's latest version or as you mentioned on other issues can remove jsdom dependency completely but for time being if upgrading to latest version is possible can we just update *package.json* file accordingly?

**Comment by mbostock** [comment]
It looks like you’re trying to install an older version of D3, specifically, 3.4.1.

In the latest version, JSDOM has been demoted to a devDependency rather than a dependency, which typically means you don’t have to install JSDOM and all its dependencies (the most error-prone of which is Contextify, since it requires compiling native code) if you only depend on D3.

The install should look like this:

```
$ npm install d3
d3@3.5.6 node_modules/d3
$
```

The JSDOM dependency is declared as `"3"`, which means we depend on the latest version of JSDOM that has the major version 3. Incrementing the major version is not backwards-compatible, so that’s the most aggressive we should be about using the latest version of JSDOM.

We could upgrade to a more recent version of JSDOM, but that would require everyone to use a newer version of Node (4+). I’m not sure that’s a good idea.

But at any rate, the issue here appears to be you are installing an old version of D3, and assuming you switch to a more recent version, you shouldn’t need to install any version of JSDOM.

**Comment by iyogeshjoshi** [comment]
@mbostock As I mentioned in my last comment I'm not installing D3 using any package manager either `npm` or `bower`, all I did was cloned master branch of D3 repo, which seems to be on `3.5.6` version precisely according to `package.json` file, and as you said yes the JSDOM is under the devDependency in `package.json` file, but when I do `npm install` it throws the error provided in my last comment.

PS: I'm using Node's latest version viz `v4.1.2` on my Mac which is running `OS X El Capitan (10.11)`

**Comment by mbostock** [comment]
Okay, sure, if you’re cloning the repo and running `npm install` then yes you still need JSDOM because it’s a development dependency.

**Comment by iyogeshjoshi** [comment]
So is there anything we can do? or is this all depends on JSDOM module to fix the Contextify issue?
