### ISSUE TITLE
Interrupting transition starts at the next step of the interrupted transition

### ISSUE THREAD

**Issue by cool-Blue** [mbostock/d3#2581]
### expected ###
 1. Transition is running, evolving an attribute value
 1. Compute a new attribute value and set it on the node and schedule a new transition
 1. Verify that the attribute value is updated on next d3.timer tick
 1. The interrupt event fires
 1. The new transition starts with the new attribute value

2015-10-12 18:29:58.946 index.html:519 current x: 252.11081223300786 new x: 80.5697041483292
2015-10-12 18:29:58.946 index.html:538 marker interrupted	80.5697041483292
2015-10-12 18:29:58.951 index.html:200 tick: current x: 80.5697041483292
2015-10-12 18:29:58.952 index.html:533 marker started 80.5697041483292
2015-10-12 18:29:58.962 index.html:200 tick: current x: 81.02723883894973

### observed ###
 1. Transition is running, evolving an attribute value
 1. Compute a new attribute value and set it on the node and schedule a new transition
 1. Verify that the attribute value is updated on next d3.timer tick
 1. The old transition runs for one more tick and overwrites the attribute
 1. The interrupt event fires
 1. The new transition starts with the incorrect attribute value

2015-10-12 18:08:19.801 index.html:519 current x: 238.27018241486485	new x: 157.23999861057627
2015-10-12 18:08:19.810 index.html:200 tick: current x: 157.23999861057627
2015-10-12 18:08:19.812 index.html:538 marker interrupted	240.09128519917357
2015-10-12 18:08:19.812 index.html:533 marker started	240.09128519917357

### workarround ###
This can be fixed by calling `selection.interrupt` before setting the new transition on `selection` but (to me anyway) this is far from obvious.

**Comment by mbostock** [comment]
This is the expected behavior. It might be non-obvious, but I don’t see a good way of changing it without something heavy-handed like an explicit run loop instead of native event handlers.

The issue is that your code runs first, such as in response to a setTimeout or event handler callback. Your code then schedules a transition. But since any transition is instantiated without concurrently specifying a delay (the delay is set by transition.delay after selection.transition returns) or likewise tweens, the transition cannot start immediately; it has to wait until the first tick, so that you have time to configure the transition before the transition starts.

Furthermore, if you schedule multiple transitions, we want the transition callbacks to run in the order they were specified while they are active, for simplicity’s sake. And thus since your new transition was scheduled after any active transition, its first tick occurs afters the active transition’s last tick, giving the active transition a chance to overwrite whatever else your code may have done before the new transition starts. If this transition is ending on this tick and a new transition is starting, we want the active transition to end normally and not be considered interrupted.

So, this is why you must call selection.interrupt: to make it clear that your code pre-empts any active transition that is running. You can’t just rely on your new transition pre-empting the active transition. Perhaps we could add a few more special cases to control the ordering of ticks, but I think minimizing the number of special cases will ultimately be easier to understand than a black box that tries to handle the common cases but is essentially inscrutable.

**Comment by cool-Blue** [comment]
Yes, thank's for explaining, that makes perfect sense now: my "expected behaviour" is not altogether sane.   

I tried to add a little more explanation around this in the wiki, hopefully, it's ok.

**Comment by mbostock** [comment]
Thanks. I made some further changes… hope it helps.
