### ISSUE TITLE
d3 arc startAngle / endAngle

### ISSUE THREAD

**Issue by inctor** [mbostock/d3#2586]
Hey,

I'm trying to move the "startAngle" to be at the bottom, instead of at the top.
I've seen that startAngle(0) is top, and startAngle(50) seems to be the bottom of the arc.

But then the endAngle is calculated wrong, not sure if there is any easy fix for this, to just "rotate" the svg 180 degrees around, or it's able to be solved with the plugin itself?

This is what i have currently:
```
<script>
    $(function () {
        var $container = $('.chart-container-{{ $name }}'),
                τ = 2 * Math.PI,
                width = $container.width(),
                height = $container.height(),
                outerRadius = Math.min(width, height) / 2,
                innerRadius = (outerRadius / 5) * 4,
                fontSize = (Math.min(width, height) / 4);

        var arc = d3.svg.arc()
                .innerRadius(innerRadius)
                .outerRadius(outerRadius)
                .startAngle(0);

        var svg = d3.select('.chart-container-{{ $name }}').append("svg")
                .attr("width", '100%')
                .attr("height", '100%')
                .attr('viewBox', '0 0 ' + Math.min(width, height) + ' ' + Math.min(width, height))
                .attr('preserveAspectRatio', 'xMinYMin')
                .append("g")
                .attr("transform", "translate(" + Math.min(width, height) / 2 + "," + Math.min(width, height) / 2 + ")");

        var circle = svg.append("circle")
                .attr("width", '150px')
                .attr("height", '150px')
                .attr("cx", 0)
                .attr("cy", 0)
                .attr("r", innerRadius + 2)
                .style("fill", "#303942");

        var text = svg.append("text")
                .text('0%')
                .style("fill", '#fff')
                .attr("text-anchor", "middle")
                .style("font-size", fontSize + 'px')
                .attr("dy", fontSize / 3)
                .attr("dx",0);

        var background = svg.append("path")
                .datum({endAngle: τ})
                .style("fill", "#eee")
                .attr("d", arc);


        var foreground = svg.append("path")
                .datum({endAngle: 0 * τ})
                .style("fill", "#2dad00")
                .attr("d", arc)
                .transition()
                .duration(750)
                .call(arcTween, {{ $arcPercent / 100 }} * τ);

        function arcTween(transition, newAngle) {

            transition.attrTween("d", function (d) {
                var interpolate = d3.interpolate(d.endAngle, newAngle);

                return function (t) {

                    d.endAngle = interpolate(t);

                    text.text('{{ prettyNumbers(str_replace(",",".",$value),1) }}');

                    return arc(d);
                };
            });
        }
    });
</script>
```

I have tried a few things, but didn't really work out the way i expected.

**Comment by mbostock** [comment]
In this case you’ve set the startAngle accessor of the d3.svg.arc instance to the constant 0, so the start angle will always be at zero. If you want to have a variable startAngle, then you probably want the default accessor, which will use the startAngle property of the object you pass the arc generator (`d.startAngle` and `d.endAngle`). Then if you want to rotate the arc, you need to change the value of `d.startAngle` and `d.endAngle` accordingly (maintaining a constant value for `d.endAngle - d.startAngle`, so that the angular length of the arc remains constant and thus the arc appears to be rotating).

That said, this appears to be a support question rather than a bug in d3.svg.arc or a feature request, so please use Stack Overflow or the d3-js Google group to followup if you want further assistance. I also recommend that rather than including a partial snippet of non-functional code, you create a standalone example that reproduces the problem, such as by [bl.ocks.org](http://bl.ocks.org) or [JSFiddle](https://jsfiddle.net/). Running code that demonstrates the problem is often necessary to diagnose the problem and will be more conducive to garnering responses from helpers.

Good luck!
