### ISSUE TITLE
Normalize d3.layout.histogram by area (instead of sum)

### ISSUE THREAD

**Issue by bas-rustenburg** [mbostock/d3#2593]
Could an option be added to normalize the output from d3.layout.histogram by area? If I interpret [the implementation](https://github.com/mbostock/d3/blob/4616c1d55c676cd51377bc6e1d12de037b872cdd/src/layout/histogram.js#L22) correctly, when `frequency` is false, normalization occurs by using the sum of the histogram (dividing by the total count).

For it to be a probability density, the integral of the histogram should be 1 (see also [this helpful post](http://stackoverflow.com/a/5321546)), so it should be normalized by area, not the sum. 

As a workaround, I map this function onto my bins but it may be a helpful feature to add:

```javascript
function normBydX(bin) {
    bin.y /= bin.dx
    return bin;
}
```

**Comment by mbostock** [comment]
Sure. Currently, the histogram layout currently computes probabilities per bin (when `frequency` is false), not probability densities. If the bins are all equal width, as in the common case, then the shape of the histogram is the same (although the y-values obviously may be different).

Here’s an example of an irregular histogram that normalizes by area. It doesn’t use the histogram layout, though, because the bins were pre-computed (not dynamically computed from samples):

[![screen shot 2015-10-22 at 8 42 09 pm](https://cloud.githubusercontent.com/assets/230541/10684043/703fbb3c-78fd-11e5-8b46-a3da589b9b1c.png)](http://bl.ocks.org/mbostock/1624660)

It’s trivial to replace `bin.y` with `bin.y / bin.dx` outside of the histogram layout, so it’s not exactly pressing to have the histogram do this for you automatically… but at the same time, it would be nice to support probability densities as output, and we should perhaps even discourage the “probability” mode.

Also, we shouldn’t refer to probabilities as density in the documentation, because that’s misleading. I can fix that.

**Comment by mbostock** [comment]
The new [d3.histogram API](https://github.com/d3/d3-array#histograms) in [d3-array](https://github.com/d3/d3-array) for [D3 4.0](https://github.com/mbostock/d3/tree/4) removes the frequency / probability mode flag, and just serves as a binner: the histogram returns an array of bins, each bin being an array of the elements in that bin. If you want a frequency histogram, you use *bin*.length; if you want a probability histogram, you have to normalize this value accordingly.
