### ISSUE TITLE
Log-scale layout for chords?

### ISSUE THREAD

**Issue by vessenes** [mbostock/d3#2604]
I am working with large graph datasets that can have many edges, in the millions. 

As part of an effort to visualize them, we are aggregating some data into on average one hundred datapoints and dumping them into a matrix, then rendering with chord diagrams. 

Unfortunately, our aggregations have a wide range of values, from, say, 0.01 to 200,000. This makes the current (linear) layout for chords not so great; a huge part of the circle is taken up with one or two aggregated data points, and the rest are all jammed into a tiny box.

It struck us that a log scale for sizing the arcs would be great, but I'm a little mystified as to where we'd do that. On review of the chord code, it's not immediately obvious where we should be changing the chord lengths. 

Any thoughts on this, or pointers?

**Comment by mbostock** [comment]
The simplest way to do this would be to iterate over your matrix and replace every value *x* with *y = Math.log(x)* before you pass it to the chord layout. Then, if you want to get the original value back out (say to display a tooltip), you use *x = Math.exp(y)*.

The problem with this approach is that a log transform doesn’t really make sense for a length (or area) encoding, which is how they are used in a chord diagram since the matrix value determines the angular width of the chord. If your value *x* is less than 1, then the log will be negative. Sure, you could pick an arbitrary multiplier to avoid this for some values, but what if one of your values is zero? The log is negative infinity. So it doesn’t really make sense, just like it doesn’t make sense to use a log scale with a bar chart since you can’t display the zero axis.

Log scales are more appropriate for position encodings, such as in scatterplots, where you don’t need them to be capable of representing zero values. (In such a scatterplot, the zero value is infinitely far away, but that doesn’t matter because you don’t care how far away the points are from zero. With a length encoding you *do* care about how far away zero is, because that determines the relative magnitude of the length and the basis for comparison.)

You could use a power transform for this (see d3.scale.sqrt and d3.scale.pow). Similarly you could transform the data yourself before passing it to the chord layout: replace *y = Math.sqrt(x)* and then to invert, *x = Math.pow(y, 2)* or *x = y \* y*.

**Comment by vessenes** [comment]
This is depressingly obvious, just to transform the data upfront. Thanks for the comments.

In our use case, log, maybe with an offset would make sense, but I agree there are many circumstances where it wouldn't.
