### ISSUE TITLE
Use a named, not anonymous, UMD.

### ISSUE THREAD

**Issue by maxyeg** [mbostock/d3#2606]
See this line: https://github.com/mbostock/d3/blob/master/d3.js#L9501
`define(d3)` is not the proper way if use requirejs.
Look at its the code: 
https://github.com/jrburke/requirejs-bower/blob/master/require.js#L2019

To summarize define d3 module should look like this:
`define("d3", [], function(){ return d3; });`

**Comment by mbostock** [comment]
It’s defined as an anonymous module, and this is intentional: it allows the consumer to specify whatever name they want. So, it is *a* proper way to specify a UMD which is compatible with requirejs, and if you read through the code you linked closely, you can see it handles this case. (It also treats a missing `deps` array as zero dependencies, and a non-function `callback` as the defined value rather than a function which returns that value.)

Arguably we could define it as a module named “d3”, which is closer to what jQuery does:

```js
if ( typeof define === "function" && define.amd ) {
  define( "jquery", [], function() {
    return jQuery;
  });
}
```

Related: [discussion of named and unnamed modules](https://stackoverflow.com/questions/19720646/named-module-vs-unnamed-module-in-requirejs) on Stack Overflow.

In any case, I believe changing this behavior would not be backwards-compatible for 3.x. In 4.0+ I’m using Rollup to generate UMD bundles. It looks like Rollup doesn’t currently support generating named modules in the UMD format, but I can file an issue for that.

**Comment by mbostock** [comment]
Okay, as of d3-bundler 0.4.1 we now use a named export and a define call style similar to jQuery.
