### ISSUE TITLE
AXIS:  Invalid value for <g> attribute transform="translate(NaN,0)"

### ISSUE THREAD

**Issue by Tibicenas** [mbostock/d3#2607]
Hello, i got this problem when i try to modify my xAxis values

```javascript
      var xAxis = d3.svg.axis()
          .scale(xScale)
          .orient('bottom')
          .tickValues([1,2,3,65,0]);
       
      var xGuide =  d3.select(".chart--browsers")
                      .append("g")
                        .attr("class", "axis--x");


      xAxis(xGuide);
      xGuide.attr('transform', 'translate(' + margin.left + ', ' + (contentHeight + margin.top) + ')');
      xGuide.selectAll('path')
          .style({fill: 'none', stroke: axisColor});
      xGuide.selectAll('line')
          .style({stroke: axisColor});
```
```console
Error Invalid value for <g> attribute transform="translate(NaN,0)" 
```
The error is located here

```javascript
   xAxis(xGuide);
```

If i use ticks(5); instead of tickValues everything works (but i want specific values, no 0,1,2,3,4), so ... i don't know what the hell is happening :S

**Comment by mbostock** [comment]
Works for me? I had to guess at a few of the referenced variables. See [bl.ocks.org/710691967362c7cde7a5](http://bl.ocks.org/mbostock/710691967362c7cde7a5):

[![screen shot 2015-11-05 at 7 17 10 am](https://cloud.githubusercontent.com/assets/230541/10972258/449d5fee-838d-11e5-9b0a-5388c5190f0d.png)](http://bl.ocks.org/mbostock/710691967362c7cde7a5)

I can reproduce the error if I use a log scale rather than a linear scale, but that’s the expected behavior since a log scale can’t represent 0: log(0) = -∞.

**Comment by Tibicenas** [comment]
Oh i see now, that ****** zero :) thank you
