### ISSUE TITLE
Time scale & daylight saving

### ISSUE THREAD

**Issue by ocombe** [mbostock/d3#2610]
Hello,

I have a graph representing some data on a time scale. We get the dates from mysql as mysql timestamps in the form of "2015-09-21 13:45:45". I then transform them to javascript dates, and inject the data in my D3js graph.

When the daylight saving occurred, D3 added an extra hour in the graph causing a visual glitch with the interpolator:

![d3js daylight saving bug](https://cloud.githubusercontent.com/assets/265378/10998049/9325c1aa-8492-11e5-8c6b-d50f33d8b6e2.JPG)

I tried to change the x scale from `d3.time.scale()` to `d3.time.scale.utc()` but it didn't fix the problem. Since my dates are mysql timestamps, I have no way to differentiate my points between the first 02:00 to 03:00 and the second one. I would like to ignore this second hour. Is there a way to do that ?

**Comment by mbostock** [comment]
For the purposes of explanation, let’s assume that you are in California. (The explanation will apply to any timezone that uses daylight savings, but it’s simpler to explain by picking a specific timezone.)

Now let’s consider the timestamp “2015-11-01 01:45:45”. If this represents the *local* timezone, and you’re not also storing the timezone along with the timestamp, then you have no way of distinguishing 2015-11-01 01:45:45 PDT from 2015-11-01 01:45:45 PST. The former is Sun, 01 Nov 2015 08:45:45 GMT while the latter is Sun, 01 Nov 2015 09:45:45 GMT. You’ve lost information.

So, any data you have between Sun, 01 Nov 2015 08:00:00 GMT and Sun, 01 Nov 2015 10:00:00 GMT is effectively lost because you don’t know whether it occurred in the first 2 AM (PDT) or the second 2 AM (PST).

If you convert these timezone-less timestamps to JavaScript Date objects, the runtime likely assumed PDT. Thus the behavior for the first hour is correct, but for the second is not. This explains the incorrect rendering of the graph: the data is not in monotonic chronological order because the data for the second 2 AM is overlaid on top of the first 2 AM.

(It’s possible that you’re also seeing a bug with the monotone interpolator, #2348, but that’s secondary to the data problem.)

The only way to fix this is by fixing how you store data. I recommend storing timestamps in UTC rather than local time, and then using d3.time.format.utc to parse them (or equivalently [utcFormat](https://github.com/d3/d3-time-format#locale_utcFormat) in 4.0).

**Comment by ocombe** [comment]
Thanks for your quick (and thorough answer).

I was afraid that this was the only solution. Now it's time to find some dirty hack to fix this because I cannot change the data that we already have :-/

**Comment by humphrt** [comment]
Same problem :-/
