### ISSUE TITLE
d3 global now missing in electron

### ISSUE THREAD

**Issue by zz85** [mbostock/d3#2615]
First of all, thank you for this awesome library! I've learn lots of stuff under its hood and I was able to write a [disk space visualization app](https://github.com/zz85/space-radar) fairly thanks to d3.

However, in the last npm updates, the d3 global is no longer defined in Electron. I currently include d3 in electron like

```html
<script src="node_modules/d3/d3.js"></script>
```

I believe the change was caused by commit 1fad2e0cf7fba217eba0eadf3cae17c15090f1dd.
Of course this could be Electron specific (it having both browser and node properties), and one workaround for me is to write
```html
<script> var d3 = require('d3') </script>
```

Just checking if the current d3 behaviour is correct and whether you think my solution is sound.

**Comment by mbostock** [comment]
Thanks for the report. What you are seeing sounds correct. Here’s the intended behavior for the `d3` global:

1. If in an AMD environment (`typeof define === "function" && define.amd`), YES.
2. If in a CommonJS environment (`typeof module === "object" && module.exports`), NO.
3. Otherwise, YES.

It sounds like Electron is a non-AMD, CommonJS environment. In this case you should never have seen the `d3` global because the package.json defined the main entry as [index.js](https://github.com/mbostock/d3/blob/v3.5.6/index.js), *not* d3.js. However, since you were explicitly loading the d3.js file directly, you were seeing the global. In 3.5.7 and later, the index.js was removed to simplify the definition and so you are now seeing the intended (global-less) behavior.

**Comment by idubinskiy** [comment]
@mbostock It seems we had a similar issue. d3 was available to c3 as a global, and so c3 did not need to be parsed by browserify. With this change, d3 doesn't expose itself and therefore c3 must be parsed so that browserify properly shims the `require`.

**Comment by mbostock** [comment]
@idubinskiy I took a peek at your code, and I think you want to structure it a bit differently. Currently when you `define` c3, you list d3 as a dependency, but you don’t pass the loaded d3 module to the factory when you create c3:

```js
if (typeof define === 'function' && define.amd) {
  define("c3", ["d3"], function () { return c3; });
} else if ('undefined' !== typeof exports && 'undefined' !== typeof module) {
  module.exports = c3;
} else {
  window.c3 = c3;
}
```

Instead you `require` it internally:

```js
$$.d3 = window.d3 ? window.d3 : typeof require !== 'undefined' ? require("d3") : undefined;
```

The problem with the above is that it duplicates the environment logic at define and require time. You could unify that logic by instead doing something like this:

```js
!function(global, factory) {
  if (typeof define === 'function' && define.amd) {
    define('c3', ['d3'], factory);
  } else if ('undefined' !== typeof exports && 'undefined' !== typeof module) {
    module.exports = factory(require('d3'));
  } else {
    global.c3 = factory(global.d3);
  }
}(this, function(d3) {
  var c3 = { version: '0.4.11-rc4' };

  // initialize c3 here

  return c3;
});
```

**Comment by idubinskiy** [comment]
Haha, bit of a misunderstanding. c3 is not my code, just a library we're using. For some reason, the interplay between browserify, c3, and the updated d3 caused an issues for us. Hard to pinpoint exactly why, though. It seems as though previous versions of d3 (before today's updates) were leaking into the global scope and allowing c3 to access it via `window`.

I might suggest this change to the c3 maintainer however, for the future.

**Comment by thomassuckow** [comment]
Seems like a non-semver change. Should have probably been 3.6

**Comment by mbostock** [comment]
> Seems like a non-semver change. Should have probably been 3.6

If you’re arguing that this was backwards-incompatible, then it should have been 4.0. But my take is that loading the d3.js file (meaning `node_modules/d3/d3.js`) directly in a CommonJS environment was unsupported—the supported case was using the defined main entry in the package.json.

**Comment by idubinskiy** [comment]
As far as I can tell, that's what we were doing. However, it also seems that d3 was still leaking into `window` when used that way (at least through browserify),  and we were inadvertently relying on that behavior.

It's an interesting exercise to consider whether a change that fixes unexpected behavior that was being inadvertently relied on is backwards-compatible. Obviously we would've been oblivious to the issue had the change been part of a 4.0 rather than a 3.x, but that's not necessarily a good thing.

**Comment by thomassuckow** [comment]
Touché 4.0

I'll agree this is a grey area. I would even go so far as to say I don't see any documentation that d3 even supports CommonJS, just AMD.

My team got bit by this because another library we use apparently just assumed it was on the global object and it always "just worked". We've now pinned the version back and made tickets to resolve the global issue. So, the upside to this breaking is many people will probably fix their builds, downside is the d3 issue tracker may get a lot of noise over the next few months as people slowly notice.

**Comment by albertosantini** [comment]
My use case is a bit different.

I have an express app: it works like a web app and an electron one.

When I start the app in electron environment, the global d3 object is not available.
That is due to `typeof module === "object" && module.exports` is `true`.

`main.js`
```
...
require("./src/server/app"); // start the express app
...
mainWindow.loadUrl("http://localhost:8000");
```

`index.html`

```
...
<script src="https://cdn.rawgit.com/mbostock/d3/master/d3.min.js"></script>
...
```

As workaround I need to add the following line to the `index.html`

```
...
<script src="https://cdn.rawgit.com/mbostock/d3/master/d3.min.js"></script>
<script>if (typeof module === "object") { window.d3 = module.exports; }</script>
```

I suggest to add also `this.d3 = d3` if `window` is defined in module part:

```
  if (typeof define === "function" && define.amd) 
      this.d3 = d3, define(d3); 
  else if (typeof module === "object" && module.exports) 
      module.exports = d3; 
      if (typeof window === "object") // new line
          this.d3 = d3; // new line
  else 
      this.d3 = d3;
```
or changing the condition for module case to enter in the last `else` part:

```
  else if (typeof module === "object" && module.exports && typeof window === "undefined") 
```

Does it make sense?

**Comment by albertosantini** [comment]
At last, for my use case, I added `"node-integration": false` to `BrowserWindow` options, as suggested in https://github.com/electron/electron/issues/254

Now `<script src="node_modules/d3/d3.js"></script>` works nice in the usual browser env and electron one.

**Comment by westside** [comment]
Maybe it might be trivial case, but using after document loading event works fine.

```
    angular.element(document).ready(function () {
        // custom d3 function
        d3.selection.prototype.moveToFront = function() {
            return this.each(function() {
                this.parentNode.appendChild(this);
            });
        };
```
