### ISSUE TITLE
error occurs when tree's root node has only one child

### ISSUE THREAD

**Issue by vylan** [mbostock/d3#2646]
Hi,

I'm using d3 to generate a radial tree, I found it can't be shown when the root node's children has only one item. The error message is like: 

Error: Invalid value for <path> attribute d="MNaN,NaNCNaN,NaN NaN,NaN NaN,NaN"a @ d3.v3.min.js:1
d3.v3.min.js:1 Error: Invalid value for <g> attribute transform="rotate(NaN)translate(0)"a @ d3.v3.min.js:1
d3.v3.min.js:1 Error: Invalid value for <g> attribute transform="rotate(NaN)translate(360)"

see here for detail: http://plnkr.co/edit/0fhh6B?p=preview

**Comment by mbostock** [comment]
Probably a bug but I haven’t investigated yet.

**Comment by mbostock** [comment]
The issue isn’t the tree layout *per se*, but the specified separation function and how the tree layout determines the left-most and right-most node in this degenerate case.

The left-most node is defined as the node with the smallest *node*.x value, while the right-most node is defined as the node with the greatest *node*.x value. In this degenerate case, the initial layout gives the two nodes the same *node*.x value of zero; so, either node could be considered both the left- and right-most node, but the implementation happens to choose the root node.

Once the left- and right-most nodes are determined, the *x*-distance between the two nodes plus their separation determines the overall width of the tree. Now note how the separation function depends on the *node*.depth:

```js
function separation(a, b) {
  return (a.parent === b.parent ? 1 : 2) / a.depth;
}
```

So what happens when *a* is the root node? Then *a*.depth is zero, and the returned separation is Infinity! Thus the overall width of the tree is NaN, and all the coordinates are set to NaN. A trivial workaround to avoid the divide by zero:

```js
function separation(a, b) {
  return (a.parent === b.parent ? 1 : 2) / Math.max(1, a.depth);
}
```

Of course, it doesn’t make sense to compute the separation in this degenerate case because the left-most and right-most nodes are the same. I’ll fix the tree layout, but probably only in D3 4.0 in the [d3-hierarchy module](https://github.com/d3/d3-hierarchy).
