### ISSUE TITLE
leading zeros in URL are cut off when using style() in selectAll().transition()

### ISSUE THREAD

**Issue by arjenvanoostrum** [mbostock/d3#2647]
Hi, 

It appears that when using selectAll().transition() and setting the CSS fill property with style("fill", "<full path"), leading zeros in the path are cut off. 

See http://jsfiddle.net/kw2v217w/5/ for an example

select().style() and selectAll().style() are OK. 

I would expect the style() function not to alter the path.

**Comment by mbostock** [comment]
While surprising, this is the expected and intended behavior for the default [string interpolator](https://github.com/d3/d3-interpolate#interpolateString) which searches for numbers in the starting and ending string, and then interpolates between them.

The starting value for transition.style is the computed style property value which is normalized according to the CSS specification as `rgb(r, g, b)` where `r`, `g` and `b` are numbers in the range [0,255]. In your example, since you haven’t specified a fill style, the default is `rgb(0, 0, 0)`. You can test this yourself with the following code:

```js
getComputedStyle(element).getPropertyValue("fill"); // "rgb(0, 0, 0)"
```

The destination value you’ve specified likewise contains numbers: `url(http://example.com/index/0/1/01)`, so the first 0 (`r`) is paired with the first number in the URL, and so on.

Obviously, you don’t want to actually interpolate these values: I assume you intended to just set the style to the new value at the start of the transition. Here are two ways to do that. You could listen for the transition *start* event and set the style.

```js
transition.each("start", function() {
  d3.select(this).style("fill", "url(http://example.com/index/0/1/01)");
});
```

Equivalently:

```js
transition.each("start", function() {
  this.style.fill = "url(http://example.com/index/0/1/01)";
});
```

Or, you could define a custom tween that sets the fill style during initialization (and then returns undefined so that the tween doesn’t run for the remainder of the transition). This is the technique used by [transition.text](https://github.com/mbostock/d3/blob/master/src/transition/text.js).

```js
transition.tween("style.fill", function() {
  this.style.fill = "url(http://example.com/index/0/1/01)";
});
```

(The name of the tween doesn’t really matter, but for clarity I used the same name that transition.style would use.)

**Comment by arjenvanoostrum** [comment]
Hi,

Thanks for your comprehensive response to this issue, or as it turns out, question! The effort you take in answering questions is huge and highly appreciated. 

It was indeed not my intention to interpolate the IRI string. AngularJS requires the base path to be set for routing, which then forces me to set the new full path reference to the pattern. 

What triggered me to file this as an issue was that setting the fill with <code>transition.attr()</code> did not interpolate the string. I can now understand why as this one does not assume a css value to interpolate from, so probably doesn't take an empty value as the <code>rgb(0,0,0)</code> and hence does not find a corresponding number to interpolate from. 

Anyway, Thanks for the suggestions for fixing the code. I'll change it accordingly!

**Comment by mbostock** [comment]
Glad my response was helpful. It is a bit awkward that transition.attr behaves differently, but then attributes don’t cascade like styles, so there’s no concept of the “computed” attribute value as being different from the set attribute value. Cheers.
