### ISSUE TITLE
stacked bar chart can't handle 205 layers

### ISSUE THREAD

**Issue by pulkitnandan** [mbostock/d3#2651]
I'm trying to use d3js to create a stacked bar chart by extracting stacked chart from .http://bl.ocks.org/mbostock/3943967

It works very good if layers are less than 5 but fails very badly if layers are like 205 and significant layers are hardly 13. Significant means layers that have some non-zero y values.

Here goes the plunk for it http://plnkr.co/edit/2oed4UI6D3aSGEd6rCW1?p=preview

This plunk have four divs, all do look ok but try to zoom the page and focus @ bottom-right div's chart.

It will show that stacks have white space between them which is certainly not expected and I can't deduce why. 

Top-Left chart:  2 layers 
Top-Right chart:  2 layers 
Bottom-Left chart: 205 layers 13 significant.
Bottom-Right chart: 205 layers 13 significant.

And if I increase the samples for these bottom charts then a much much space can be seen between stacks.

**Comment by mbostock** [comment]
The issue is that the stack layout expects your data to be homogenous, but your data is inconsistently ordered by its x-value. For example, the Huawei data looks like this:

```js
[
  {"x": 0, "y": 0, "d": 9, "text": "0.00% Huawei"},
  {"x": 2, "y": 0, "d": 11, "text": "0.00% Huawei"},
  {"x": 1, "y": 1, "d": 10, "text": "2.17% Huawei"}
]
```

But the Nokia data looks like this:

```js
[
  {"x": 0, "y": 1, "d": 9, "text": "1.82% Nokia"},
  {"x": 1, "y": 2, "d": 10, "text": "3.85% Nokia"},
  {"x": 2, "y": 2, "d": 11, "text": "4.35% Nokia"}
]
```

It looks to me like maybe you’re inserting zeroes into the data, but you’re inserting those zeroes in the wrong order. You could fix how you insert the zeroes (say, using array.splice to put them in the right place), or you could just sort the data by its *x*-value before computing the stack layout:

```js
data.forEach(function(d) {
  d.sort(function(a, b) {
    return a.x - b.x;
  });
});
```

**Comment by pulkitnandan** [comment]
:+1:

Thanks it worked flawless.
