### ISSUE TITLE
Scientific Notation on Y Axis

### ISSUE THREAD

**Issue by ironsides24** [mbostock/d3#2652]
When I have a line graph that has a return value of -0.007 I am getting scientific notations for the values on the y axis. I have included my json model as well as the javascript controller that is creating the line charts. All other values that I have tested seems to work but -0.007. 

[reports-performance-summary-controller.txt](https://github.com/mbostock/d3/files/42928/reports-performance-summary-controller.txt)
[reports-performance-summary-model.txt](https://github.com/mbostock/d3/files/42927/reports-performance-summary-model.txt)

**Comment by mbostock** [comment]
Without a live example (say on <http://bl.ocks.org> or <https://jsfiddle.net>), I cannot investigate. I briefly looked at your code, but I do not have the resources to investigate your issue in detail, especially since the code you included is not runnable due to it being part of a larger application.

I cannot tell, in particular, whether what you are describing is a bug in [d3.format](https://github.com/mbostock/d3/wiki/Formatting#d3_format) or a bug in your code (say, *not* using d3.format to format human-readable numbers, or using the wrong specifier). The default behavior of JavaScript is to use exponent notation for values smaller than 1e-6. If you aren’t using a number format, you may also experience precision problems (such as 0.30000000000000004) due to the nature of floating point.

You might try Stack Overflow if you want help diagnosing your issue. Please also make use of the API reference to verify that you are using scales, axes and number formats correctly. If you still think this is a bug in D3, please provide a small example that demonstrates the issue, and I will take another look.
