### ISSUE TITLE
csv header row not extracted in order of file

### ISSUE THREAD

**Issue by JoostvDoorn** [mbostock/d3#2653]
The `d3.keys()` does not give the same key order when loading a csv file with numerical field names.

For example this csv file gives a problem:
```
Name,0,1
a,1,3
b,6,6
```
and also:
```
d3.keys({"test":0, "0":3, "1":3})
```
returns:
```
["0", "1", "test"]
```

It is desirable to be able to get the correct key order.

This issue is related to #858.

**Comment by mbostock** [comment]
JavaScript does not guarantee any particular iteration order with `for…in`, so by extension, the iteration order of [d3.keys](https://github.com/mbostock/d3/wiki/Arrays#d3_keys) is undefined.

If you need to know the exact order of the columns, you must use [d3.csv.parseRows](https://github.com/mbostock/d3/wiki/CSV#parseRows) rather than [d3.csv.parse](https://github.com/mbostock/d3/wiki/CSV#parse). You can use [d3.text](https://github.com/mbostock/d3/wiki/Requests#d3_text) to load the contents of the CSV file and then parse it.

**Comment by mbostock** [comment]
That said: it’s easy to change the result of csv.parse so that the returned array has a `columns` property. I’ve filed d3/d3-dsv#13 to track that, and will implement it shortly for 4.0.
