### ISSUE TITLE
Touch Event doesn't work in Edge of Windows 10

### ISSUE THREAD

**Issue by ChristyFei** [mbostock/d3#2664]
Touch event isn't trigger in Edge. Please check the following example.
http://bl.ocks.org/mbostock/770ae19ca830a4ce87f5
http://jsfiddle.net/b9u0mb04/1/

Microsoft Edge isn't official supported by D3 right now. Do you have any plan to fix them?
Thank you.

**Comment by mbostock** [comment]
D3 is not a compatibility layer. If the browser doesn’t support touch events, D3 does not magically enable them. In Microsoft Edge on Windows 10, you need to use pointer events rather than touch events.

That said, various components and behaviors in D3 should support pointer events in the future. See these related issues:

* Zoom behavior #1439
* Drag behavior #2556
* Brush component #2446
