### ISSUE TITLE
Ability to offset tick lines

### ISSUE THREAD

**Issue by priikone** [mbostock/d3#2670]
With a candlestick chart the candles are typically rendered between ticks instead of on the ticks, so that grid lines don't pierce the candles.  Is there a way to offset the tick lines themselves currently in d3js and if not maybe such a thing could be added?

There's plenty examples to offset tick labels around but how about the tick lines themselves?

**Comment by mbostock** [comment]
Are you using a quantitative scale or an ordinal scale?

For a quantitative scale, offsetting the tick lines implies that the ticks are not being drawn at their actual values, which doesn’t make much sense. You can of course select the ticks after rendering the axis and change their positions or whatever else you fancy. This is sometimes called *post-selection*; see the [custom axis example](http://bl.ocks.org/mbostock/4323929). I wouldn’t use a quantitative scale (such as a time scale) for a candlestick chart because you presumably want one candle per day, and the days to be uniformly spaced (and you may want to skip weekends and holidays).

Assuming you’re using an ordinal scale, then, yes the ticks are typically offset by half the rangeBand by the axis. (See [axis.js](https://github.com/mbostock/d3/blob/master/src/svg/axis.js#L75).) So, you could just translate the axis group (`g`) element horizontally to shift the ticks by the same amount, or you could select the ticks individually and achieve the same result.

If you want further assistance, please try Stack Overflow or the d3-js Google group. These issues are for feature requests and bug reports. Good luck!
