### ISSUE TITLE
Missing Y ticks with log scale

### ISSUE THREAD

**Issue by mgalloue** [mbostock/d3#2677]
Some times ticks are missing with log scale, as you can see on the following picture.
![capture 5](https://cloud.githubusercontent.com/assets/6142727/11779390/15f882e4-a25b-11e5-8b09-837346503778.PNG)

On d3 sources, if I add a 1e-16 tolerance, putting `return d / pow(f(log(d) + e)) <= k + 1e-16 ? format(d) : "";` instead of `return d / pow(f(log(d) + e)) <= k  ? format(d) : "";` on `scale.tickFormat` function, it works well. Is it the good approach?

**Comment by mbostock** [comment]
Related #1971 d3/d3-scale#15, in that you probably don’t want to render that many ticks if you have such a huge log domain (30 orders of magnitude).

A simple way to workaround this for now is to manually generate the tick values for your axis:

```js
function logTicks(start, stop) {
  if (stop < start) { var t = start; start = stop; stop = t; }
  start = Math.floor(Math.log(start) / Math.LN10);
  stop = Math.ceil(Math.log(stop) / Math.LN10);
  return d3.range(start, stop).map(function(x) { return Math.pow(10, x); });
}
```

Pass the result to axis.tickValues.

But, it’s still a bug if the scale is dropping powers-of-base (powers-of-ten) ticks. Adding a tolerance is probably a bad idea since this can introduce other problems, but it might be unavoidable if there’s isn’t a more robust solution.
