### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by sfwinners2014** [mbostock/d3#2682]
Uncaught SyntaxError: Unexpected token <
ia	@	d3.js:3
u	@	d3.js:1

Tried specifying <meta charset="utf-8">
doesn't work
 also tried in <script charset="utf-8" src="d3.js" ></script>  
  doesn't work
  check out: http://blueflametechpartners.com/fone.html

**Comment by mbostock** [comment]
You’re trying to load a file that doesn’t exist ([flare.json](http://blueflametechpartners.com/flare.json)), so rather than being a JSON file, it’s an HTML error page. So when you try to JSON.parse it, you get a SyntaxError: Unexpected token <.

Please use Stack Overflow or the d3-js Google group to ask for help. These issues are for bug reports and feature requests only.
