### ISSUE TITLE
Sunburst chart zooming incorrectly in Linux based Chrome

### ISSUE THREAD

**Issue by wholevinski** [mbostock/d3#2685]
Chrome: Version 46.0.2490.86 (64-bit) on Centos 6

Fiddle: https://jsfiddle.net/wholevinski/twxv8g2d/

Steps:

1. Click first level purple arc near the top: ![1st arc](http://imgur.com/CdwNZni.png)
2. Expected: ![Firefox](http://imgur.com/aoWWaJp.png)
    Actual (notice the pink arc at the top): ![Centos Chrome](http://imgur.com/oHpVBcE.png)
3. Clicking into the next level in Chrome (Arc with name TYPE_12) takes me down a completely unrelated zooming path as well: ![Bad next level zoom](http://imgur.com/oftZBrm.png)

I was unsure where to go with this at first, but these threads gave me clues:

https://groups.google.com/forum/#!topic/d3-js/nAYlH4PmY8E -- has no responses, but he's correct. The example is broken in linux chrome.

http://stackoverflow.com/questions/33648644/nvd3-sunburst-zooming-into-wrong-section -- Using NVD3, but is D3 backed, so it looks like the same problem. Only in Linux chrome; comments mention it's broken in ubuntu and mint as well.

Also, verified that it works in Windows Chrome.

**Comment by mbostock** [comment]
I don’t have a Linux box, so it’s difficult for me to reproduce this bug. (I could setup a VM, but I have a lot of other equally-worthy tasks to do, and it’s just me supporting D3, for no pay…) I’m planning on building a Linux workstation in the near future, but it’ll be a while before that happens, not the least of which is due to the parts I want being sold out due to the holiday. ;)

What would help most is if you could isolate the problem. I see three prime candidates for the bug:

1. This could be a bug in the layout. One of the quirks I noticed about TYPE_12 is that it has an empty children array, rather than no children array. Normally leaf nodes have no children array, since the presence of a children array implies that the node is internal rather than a leaf. I believe the code is intended to treat these conditions equivalently (e.g., using `children && children.length` to test the presence of children), but it’s possible there’s a bug. Try deleting the empty children array from your data and see if that fixes it:

```json
{
  "size": 97067,
  "name": "TYPE_12",
  "children": []
}
```

2. This could be a bug in transitions. Can you reproduce this bug without transitions, say by initializing the display state to rendering the second image above, on load?

3. This could be a browser rendering bug with arcs. Can you reproduce this bug with just static SVG (e.g., copy-and-paste from the developer tools)? If it’s a browser rendering bug, the best way to get this fixed will be to file a Chromium bug

**Comment by mbostock** [comment]
(Also, for future reference, it’d be easier if you posted test cases to <http://bl.ocks.org> rather than JSFiddle. JSFiddle prevents you from loading the result frame directly, so you can’t use the console to debug the problem.)

**Comment by mbostock** [comment]
I’ve reposted the test case here:

[![screen shot 2015-12-16 at 9 05 26 am](https://cloud.githubusercontent.com/assets/230541/11847840/384d4792-a3d4-11e5-920f-abbf256ada70.png)](http://bl.ocks.org/mbostock/f72035fe64f8c60f022a)

I used a fixed size for each leaf:

```js
var partition = d3.layout.partition()
    .value(function() { return 1; });
```

The problematic parts of the sunburst (pink) appears to be TYPE_13. But I’m not sure why.

**Comment by wholevinski** [comment]
So when determining which children to display, it looks like it's a precision issue when determining which to display. If you change arcTween to look like this (nasty hack included) it will fix it:

            function arcTween(d) {
                var xd = d3.interpolate(x.domain(), [d.x, d.x + d.dx]),
                    yd = d3.interpolate(y.domain(), [d.y, 1]),
                    yr = d3.interpolate(y.range(), [d.y ? 20 : 0, radius]);
                return function(dd, i) {
                    return i
                        ? function(t) { return arc(dd); }
                        : function(t) {
                            var xdomain = xd(t);
                            xdomain[0] += .00000001;
                            xdomain[1] -= .00000001;
                            x.domain(xdomain);
                            y.domain(yd(t)).range(yr(t));
                            return arc(dd);
                        };
                };
            }

**Comment by mbostock** [comment]
Thanks. It sounds like there’s a precision problem when the angular span of the arc is near 0°, where it renders a complete circle rather than an empty arc.

Can you quickly check this version using the [new d3-shape](https://github.com/d3/d3-shape)?

[![screen shot 2015-12-16 at 9 22 34 am](https://cloud.githubusercontent.com/assets/230541/11848359/c75c9d0a-a3d6-11e5-9f53-f9eb51b84601.png)](http://bl.ocks.org/mbostock/27293b582e4fb057f62b)

This version has a [special check for collapsed arcs](https://github.com/d3/d3-shape/blob/v0.2.0/src/arc.js#L168-L169), so it might be more robust.

**Comment by wholevinski** [comment]
That one's showing the same behavior too

**Comment by mbostock** [comment]
That’s quite surprising. For me, TYPE_13 renders as a line:

```
M-4.670611695596016e-14,-254.2562584220407L-2.8022675436976468e-14,-152.54833995939046Z
```

What path do you see when you inspect the element?

**Comment by mbostock** [comment]
Also, do the errant pink arcs display during the transition from the first to the second image above? Or do they just suddenly appear at the end of the transition?

**Comment by wholevinski** [comment]
From the untouched view, TYPE_13's path:
    
    M-1.044337200031198,-294.4467852767502A294.44863728670913,294.44863728670913,0,0,1,-0.2481601456221697,-294.4485327124965L-0.20262191042302818,-240.4162202189391A240.41630560342617,240.41630560342617,0,0,0,-0.8526977531611079,-240.41479344362685Z

The errant arcs come in after the transition has completed, not with the transition.

**Comment by wholevinski** [comment]
*which is easier to view if I slow the transition down, btw

**Comment by mbostock** [comment]
Yeah, that’s what I see, but I’m more interested in TYPE_13’s path for the second view.

```
M-1.044337200031198,-294.4467852767502
A294.44863728670913,294.44863728670913,0,0,1,-0.2481601456221697,-294.4485327124965
L-0.20262191042302818,-240.4162202189391
A240.41630560342617,240.41630560342617,0,0,0,-0.8526977531611079,-240.41479344362685
Z
```

**Comment by wholevinski** [comment]
Ah, sorry, I misunderstood. Here's after clicking DS_2 which looks like it matches yours:

    M-4.670611695596016e-14,-254.2562584220407L-2.8022675436976468e-14,-152.54833995939046Z

**Comment by wholevinski** [comment]
So here are some more findings using this example (which I like, since it eliminates any sort of data normalization rounding errors): http://bl.ocks.org/wholevinski/529de42f0cc697174736

DS_2, the culprit, is now bottom left quadrant and purple. It's d.x, d.dx, and d.x + d.dx are as follows:

    d.x
    0.26717557251908397
    d.dx
    0.2213740458015267
    d.x + d.dx
    0.48854961832061067

The bad leaf node that sneaks in is COUNTRY_24 (green, beginning of bottom left quadrant). Its d.x + d.dx is 0.267175572519084

For comparison:

    DS_2 (d.x [start]):             0.26717557251908397
    COUNTRY_24 (d.x + d.dx [end]) : 0.267175572519084

So the end of COUNTRY_24 overlaps DS_2's beginning X, and is included in the leaf nodes to pull in.

**Comment by mbostock** [comment]
Can you attach a screenshot of the bad behavior in the new example?

**Comment by wholevinski** [comment]
![Bad green leaf snuck in](http://imgur.com/pSeEEpv.png)

**Comment by mbostock** [comment]
This is helpful. It does appear that COUNTRY_24 isn’t quite collapsed, when it should be. After clicking on DS_2, it has the following angles:

```js
startAngle = Math.max(0, x(d.x)) // 0
endAngle = Math.max(0, x(d.x + d.dx)) // 1.5755543904797615e-15
```

This is greater than zero, so it’s being rendered as an arc. We could switch to an epsilon check, but I was hoping to avoid that.

**Comment by mbostock** [comment]
How’s this?

http://bl.ocks.org/mbostock/27293b582e4fb057f62b/1e64aff63b23683e584f082b09ef94e01bf6cb72

**Comment by wholevinski** [comment]
Works! Thanks!

**Comment by mbostock** [comment]
Thank you! I wouldn’t have been able to debug this on my own. Cheers.

**Comment by wholevinski** [comment]
FYI, the problem popped up again in a different spot on the same graph...BUT, I increased epsilon to 1e-10 and it seemed to fix it.

**Comment by mbostock** [comment]
This is still most likely a browser rendering bug in Chromium, so it would be good of you to isolate the small arc that’s being rendered incorrectly and file a Chromium bug. We’re just working around it by avoiding rendering very small arcs. Increasing epsilon is a possible workaround, but it’s not a great solution since SVG (Scalable Vector Graphics) are intended to be arbitrarily scalable.

**Comment by mbostock** [comment]
You could also change the sunburst code so that it doesn’t render tiny arcs (say returning null for the d attribute and possibly setting the display style to none).

**Comment by wholevin** [comment]
Agreed. The difference in rendering bothers me anyway, so I'll probably keep investigating when I can and keep the epsilon workaround until I can nail it down. Just wanted to keep you informed. Thanks again!

**Comment by wholevinski** [comment]
Agreed. The difference in rendering bothers me anyway, so I'll probably keep investigating when I can and keep the epsilon workaround until I can nail it down. Just wanted to keep you informed. Thanks again!
