### ISSUE TITLE
stack layout 'wiggle' offset mode cannot generate right results

### ISSUE THREAD

**Issue by gracelinmumu** [mbostock/d3#2691]
I'm using stack layout, and I cannot understand why with the same code I can generate plots using as offset zero, expand and silhouette while using the same dataset and the same stack layout the wiggle offset does not produce anything.  While I using wiggle mode, I get results with NaN y0.

**Comment by mbostock** [comment]
It’s probably because you haven’t set an *x*-accessor, and the wiggle offset in 3.x requires it. It turns out the *x*-values actually cancel out in the calculation so this accessor will be removed in 4.0, but you’ll need to specify one to use it in 3.x. (Alternatively, you could pull in [d3-shape](https://github.com/d3/d3-shape) and use the prerelease 4.0 version, but that’s probably not worth the hassle.)
