### ISSUE TITLE
proposal: selection map function

### ISSUE THREAD

**Issue by fogfish** [mbostock/d3#2696]
I think d3.selection is usable to read properties of DOM. The library supports `each()` function where you can inject whatever logic. However, it would be good to have a `map` that transfer a selection to array domain 

e.g.
```javascript
var titles = d3.select('h1')
   .map(function(d){return this.text()})
   .filter(function(x){return x.length > 5});
``` 
 
possible implementation
```javascript
d3.selection.prototype.map = function(fun) {
    var list = [];
    this.each(function(x) {list.push( fun.apply(d3.select(this),[x]))});
    return list
  };
```

**Comment by mbostock** [comment]
Related #878.

If you don’t mind flattening the selection (ignoring grouping and null elements), then it’d probably be fine to have a selection.map operator that invokes a function in the same manor as selection.each, and then builds an array accumulating the result. The proposed selection.nodes in 4.0’s d3-selection module does something like this (returning an array of nodes), but it’d be reasonable to generalize it. Alternatively, you could chain it:

```js
d3.selectAll("h1")
    .nodes()
    .map(function() { return this.textContent; })
    .filter(function(text) { return text.length > 5; });
```

Note that selection.map should set the `this` context as the node, not a single-element selection of the node, for consistency with the other methods (and because it’s better for performance).

The 4.0 API is still being designed, so… I’ll think about this.

**Comment by mbostock** [comment]
Seems like chaining *selection*.nodes in 4.0 with *array*.map is sufficient, so closing this.
