### ISSUE TITLE
port to Java(FX)

### ISSUE THREAD

**Issue by lyrachord** [mbostock/d3#2697]
An ... idea:
What is the points to port D3 to Java, current target is JavaFX?

Thanks

**Comment by mbostock** [comment]
D3 is heavily reliant on the W3C DOM API. You could take the concepts behind D3 (such as the selection and data-join) and apply them to a different scenegraph, but it wouldn’t be so much a “port” as a conceptual cousin. At any rate, I have no plans on porting D3 to other environments, so that would be a project for someone else. :grin:
