### ISSUE TITLE
Set timeout for d3.xhr requests

### ISSUE THREAD

**Issue by fholzer** [mbostock/d3#2703]
Either it's not possible to set timeouts for xhr reqeusts, or it isn't documented at all. IMHO this is a very important feature, especially for projects with many concurrent connections. In case there's an issue with one or more web services your project depends on, sending xhr requests to services that simply don't respond will block a connection slot. As browsers have only a small number of connection slots per server (http://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser), other xhr connection may not come through at all, rendering some or all features of your project unusable.

**Comment by fholzer** [comment]
At the moment I'm taking care of aborting long-running requests myself using setTimeout, but having to do that in all places I'm using d3.xhr is quite cumbersome.

**Comment by mbostock** [comment]
It’s possible using the *beforesend* event and then accessing the underlying XMLHttpRequest object:

```js
d3.xhr(url)
    .on("beforesend", function(xhr) { xhr.timeout = 2000; xhr.ontimeout = xhr.onload; })
    .get(callback)
```

The unfortunate part is that you have to register an ontimeout listener if you want to be notified of the timeout. Here, I’m recycling the onload listener that’s registered by d3.xhr, such that when the timeout fires an error is passed to the callback.

That said I think it’s worth adding this to [d3-request](https://github.com/d3/d3-request), so that you can just set the timeout and it will work automatically. I’ll do that now.

**Comment by mbostock** [comment]
Added [*request*.timeout](https://github.com/d3/d3-request#request_timeout) in [d3-request 0.2.5](https://github.com/d3/d3-request/releases/v0.2.5).
