### ISSUE TITLE
Possible CHROME BUG with Foreign Object content

### ISSUE THREAD

**Issue by Hanor** [mbostock/d3#2704]
Hello, I'm using d3 to build a bpmn software and I found a possible problem.

The D3.js has any INTERNAL event associated to CTRL + Z ? Because, when I changed the html text from a div inside one foreign object and I TYPED ctrl + z my function don't works. When I changed the event for ctrl + b for example my function works. This means the D3 is making something in this scenario..

**Comment by Hanor** [comment]
This happen only in CHROME.

**Comment by mbostock** [comment]
D3 has no internal event handlers of any kind. And, even if you register you own event listeners for ⌃Z, D3 wouldn’t do anything with that event other than pass it along to your listener. So anything wonkey happening during ⌃Z would either be due to browser functionality or something in your code. Sorry!
