### ISSUE TITLE
.click() event not working on <path> element

### ISSUE THREAD

**Issue by avipersin** [mbostock/d3#2726]
Here is the jsfiddle: https://jsfiddle.net/ojadbpsa/2/

Targeting the hover event works fine--If you hover over the legend lines, you will see the corresponding line light up.

Targeting the click event doesn't work at all. Clicking the legend lines should print "here" to the console.

You can find these (hover and click) functions at the bottom of the file with these declarations:
``` 
$(this).hover(function () {
...
})
```
and
```
$(this).click(function () {
   console.log("here");
});
```
Hopefully I'm not missing something really simple here.

**Comment by mbostock** [comment]
Looks like you’re using jQuery to register the click handler; this is the D3 repository. Also, there’s a lot going on in this example, rather than being an isolated bug report, and I’m afraid I don’t have time to investigate exactly what’s going wrong here. There could be a variety of issues (such as another element on top of the path that is intercepting the event). You might try Stack Overflow tag d3.js if you want help, or the d3-js Google group. Good luck.

**Comment by Bango1999** [comment]
For others with this specific problem, a mousedown instead of click event is confirmed working in this particular case.

**Comment by avipersin** [comment]
@mbostock Here it is using pure D3, I've removed the JQuery: https://jsfiddle.net/ojadbpsa/7/
>
For others with this specific problem, a mousedown instead of click event is confirmed working in this     particular case. Because there is already a mousedown event for path elements in d3, which is overriding the click functionality.
>

If mousedown is overriding click, how am I supposed to use click?

**Comment by mbostock** [comment]
If you would like me to investigate, you’ll have to isolate the problem further to demonstrate that this is indeed a bug in D3. I suspect the problem most likely lies elsewhere, as I previously stated. Sorry! Please try Stack Overflow tag d3.js or the d3-js Google group if you want debugging.
