### ISSUE TITLE
Chrome 48 - After Mermaid / Dagre update

### ISSUE THREAD

**Issue by cooljig89** [mbostock/d3#2734]
Hi, 

I am using d3, to render graph. Data is passed through mermaid. 
They recently fixed the issue due to chrome 48
https://github.com/knsv/mermaid/issues/281  so as Dagre.

updating mermaid page, resolved the issue in 1st place, but have introduced an error in d3. I downloaded the new d3, but still the issue persist. 

From Firefox : 
TypeError: e is null
	

...de();return n=ta.ns.qualify(n),n.local?e.getAttributeNS(n.space,n.local):e.getAt...

From Chrome : 

Error: Invalid value for <svg> attribute viewBox="0 0 -Infinity -Infinity"u @ d3-3.5.5.min.js:1
d3-3.5.5.min.js:3 Uncaught TypeError: Cannot read property 'getAttribute' of null

Any help/guidance would be appreciated.

**Comment by mbostock** [comment]
Sorry, but this sounds like a bug in your code—perhaps you’re trying to access an attribute value on empty selection? For example, this reproduces your error:

```js
d3.selectAll(".does-not-exist").attr("href");
```

The viewBox error is different, but it’s probably a bug in how you set the value. :)

Please use Stack Overflow tag d3.js or the d3-js Google group to ask for help, and I recommend making a minimal demonstration of the issue so that people can help you investigate. It’s nearly impossible to investigate without seeing the code. And, I’m afraid I don’t have time to that investigation for you! Good luck.
