### ISSUE TITLE
Bar Chart with Negative Values Y-Axis Not Showing

### ISSUE THREAD

**Issue by boucains** [mbostock/d3#2738]
Hi Mike - thanks for creating and sharing D3!

I am a noob, so please forgive me if my request is incorrect.

At http://bl.ocks.org/mbostock/raw/2368837/, the example chart does not include a y-axis to display the data. In my case, I added the following code, duplicated from the x-axis:

```
  var yAxis = d3.svg.axis()
    .scale(y)
    .orient('right');

  svg.append('g')
    .attr('class', 'y axis')
    .call(yAxis);
```

I'm sure there is a better way, but that is for the experts to decide. Thanks for reviewing this request.

**Comment by mbostock** [comment]
The reason I didn’t put a y-axis in there is that the tick labeling is a bit awkward. One decent option is to alternate the tick orientation so that the ticks are on the right for negative bars and the left for positive bars. I feel like including that logic distracted from the point of the example (which was just to show to draw bars in both positive- and negative-orientations), but here’s a new example that includes it:

[<img width="960" alt="bar-chart-negative2" src="https://cloud.githubusercontent.com/assets/230541/13134732/a2643732-d5be-11e5-9ec2-d6073d1a8ba7.png">](http://bl.ocks.org/mbostock/79a82f4b9bffb69d89ae)

I suppose it’s not so bad to include a basic y-axis in the original example. If you make the negative bars a little lighter in color then you can just overlap the labels, like so:

[<img width="960" alt="2368837" src="https://cloud.githubusercontent.com/assets/230541/13134741/bcccf438-d5be-11e5-93cb-cef2bebf080b.png">](http://bl.ocks.org/mbostock/2368837)

**Comment by boucains** [comment]
Many thanks, Mike. Really appreciate the expanded examples.
