### ISSUE TITLE
https pages are not loading some examples

### ISSUE THREAD

**Issue by nihey** [mbostock/d3#2750]
D3 is surely a great project, thanks for putting it all up.

I'm not sure if this is the best place to report this, but the `https` pages of `bl.ocks.org` is not loading some examples.

[https://bl.ocks.org/kerryrodden/raw/477c1bfb081b783f80ad/](https://bl.ocks.org/kerryrodden/raw/477c1bfb081b783f80ad/) cannot load `d3` from [http://d3js.org/d3.v3.min.js](http://d3js.org/d3.v3.min.js) (because a `https` page cannot load scrips from `http` pages).

![screenshot from 2016-02-25 10 50 30](https://cloud.githubusercontent.com/assets/5278570/13321420/a5215050-dbad-11e5-9326-43ca61b3c078.png)

the [http example](http://bl.ocks.org/kerryrodden/raw/477c1bfb081b783f80ad/) works fine.

A simple fix for this would be to load d3 from the [https d3js.org url](http://d3js.org/d3.v3.min.js)

**Comment by mbostock** [comment]
bl.ocks.org is available over HTTP and HTTPS. I don’t have control over who publishes blocks or their contents since bl.ocks.org is just a viewer of [GitHub Gist](https://gist.github.com). So, you’ll need to contact the author of the respective gist if you notice something broken; in this case, @kerryrodden.

You can also load the example by visiting the HTTP rather than HTTPS URL:

http://bl.ocks.org/kerryrodden/477c1bfb081b783f80ad/

**Comment by kerryrodden** [comment]
Fixed the example, thanks!

**Comment by mbostock** [comment]
Thank you!
