### ISSUE TITLE
Strange issue week interval range

### ISSUE THREAD

**Issue by UlTriX** [mbostock/d3#2753]
Using D3 3.5.15

`d3.time.week.utc.range(scale.domain()[0],scale.domain()[1],10)`

With 
scale.domain()[0] = Mon Jul 01 2013 00:00:00 GMT+0100 (WEST)
scale.domain()[1] = Mon May 04 2015 00:00:00 GMT+0100 (WEST)

I get equal spaced dates by 10 weeks except at the end of year

![screenshot 2016-02-29 21 22 18](https://cloud.githubusercontent.com/assets/1927118/13409359/93f4216a-df2a-11e5-90da-7d0e274344eb.png)

**Comment by mbostock** [comment]
This is the expected behavior of D3 3.x. Per the documentation for [*interval*.range](https://github.com/mbostock/d3/wiki/Time-Intervals#interval_range) (emphasis added):

> If step is specified, then every step'th interval will be returned, **based on the interval number** (such as day of month for d3.time.day).

In the case of the week interval, the interval number is the week-of-year number. The first Sunday is zero, the second Sunday is one, and so one. If the *step* is 10, you’ll get the first Sunday of the year, the 11th Sunday of the year, the 21st Sunday of the year, and so on. Because a year is not an exact multiple of ten weeks, the returned times are not uniformly-spaced across year boundaries.

The reason for this behavior is to make the filtering by step independent of the *start* and *end* dates passed to *interval*.range. This way, overlapping ranges are always consistent. (Imagine if you were panning around a [time-series chart](https://bl.ocks.org/mbostock/3883245); you wouldn’t want axis ticks popping in and out randomly as your panned.)

In D3 4.0’s [d3-time](https://github.com/d3/d3-time), there are two ways of constructing periodic time intervals. If you use [*interval*.range](https://github.com/d3/d3-time#interval_range), the first time boundary greater than the *start* is returned, and then *step* boundaries are skipped for each subsequent date. The result is probably closer to what you want:

```js
d3.timeWeek.range(new Date(2013, 6, 1), new Date(2015, 4, 4), 10);
// Sun Jul 07 2013 00:00:00 GMT-0700 (PDT)
// Sun Sep 15 2013 00:00:00 GMT-0700 (PDT)
// Sun Nov 24 2013 00:00:00 GMT-0800 (PST)
// Sun Feb 02 2014 00:00:00 GMT-0800 (PST)
// Sun Apr 13 2014 00:00:00 GMT-0700 (PDT)
// Sun Jun 22 2014 00:00:00 GMT-0700 (PDT)
// Sun Aug 31 2014 00:00:00 GMT-0700 (PDT)
// Sun Nov 09 2014 00:00:00 GMT-0800 (PST)
// Sun Jan 18 2015 00:00:00 GMT-0800 (PST)
// Sun Mar 29 2015 00:00:00 GMT-0700 (PDT)
```

The other way is to create a filtered time interval with [*interval*.every](https://github.com/d3/d3-time#interval_every). With this approach, the dates are filtered by interval number as in D3 3.x. However, the behavior is still different because d3-time defines the week number as weeks since UNIX epoch rather than weeks since start of the year, and thus the returned dates are more uniformly-spaced:

```js
d3.timeWeek.every(10).range(new Date(2013, 6, 1), new Date(2015, 4, 4));
// Sun Sep 08 2013 00:00:00 GMT-0700 (PDT)
// Sun Nov 17 2013 00:00:00 GMT-0800 (PST)
// Sun Jan 26 2014 00:00:00 GMT-0800 (PST)
// Sun Apr 06 2014 00:00:00 GMT-0700 (PDT)
// Sun Jun 15 2014 00:00:00 GMT-0700 (PDT)
// Sun Aug 24 2014 00:00:00 GMT-0700 (PDT)
// Sun Nov 02 2014 00:00:00 GMT-0700 (PDT)
// Sun Jan 11 2015 00:00:00 GMT-0800 (PST)
// Sun Mar 22 2015 00:00:00 GMT-0700 (PDT)
```

If you really wanted the behavior of D3 3.x (unlikely!) you could also filter the array manually:

```js
d3.timeWeek.range(new Date(2013, 6, 1), new Date(2015, 4, 4)).filter(function(d) {
  return d3.timeWeek.count(d3.timeYear(d), d) % 10 === 1;
});
// Sun Aug 04 2013 00:00:00 GMT-0700 (PDT)
// Sun Oct 13 2013 00:00:00 GMT-0700 (PDT)
// Sun Dec 22 2013 00:00:00 GMT-0800 (PST)
// Sun Jan 05 2014 00:00:00 GMT-0800 (PST)
// Sun Mar 16 2014 00:00:00 GMT-0700 (PDT)
// Sun May 25 2014 00:00:00 GMT-0700 (PDT)
// Sun Aug 03 2014 00:00:00 GMT-0700 (PDT)
// Sun Oct 12 2014 00:00:00 GMT-0700 (PDT)
// Sun Dec 21 2014 00:00:00 GMT-0800 (PST)
// Sun Jan 04 2015 00:00:00 GMT-0800 (PST)
// Sun Mar 15 2015 00:00:00 GMT-0700 (PDT)
```

Or equivalently using [*interval*.filter](https://github.com/d3/d3-time#interval_filter):

```js
d3.timeWeek.filter(function(d) {
  return d3.timeWeek.count(d3.timeYear(d), d) % 10 === 1;
}).range(new Date(2013, 6, 1), new Date(2015, 4, 4));
// Sun Aug 04 2013 00:00:00 GMT-0700 (PDT)
// Sun Oct 13 2013 00:00:00 GMT-0700 (PDT)
// Sun Dec 22 2013 00:00:00 GMT-0800 (PST)
// Sun Jan 05 2014 00:00:00 GMT-0800 (PST)
// Sun Mar 16 2014 00:00:00 GMT-0700 (PDT)
// Sun May 25 2014 00:00:00 GMT-0700 (PDT)
// Sun Aug 03 2014 00:00:00 GMT-0700 (PDT)
// Sun Oct 12 2014 00:00:00 GMT-0700 (PDT)
// Sun Dec 21 2014 00:00:00 GMT-0800 (PST)
// Sun Jan 04 2015 00:00:00 GMT-0800 (PST)
// Sun Mar 15 2015 00:00:00 GMT-0700 (PDT)
```

**Comment by UlTriX** [comment]
All makes sense. Thank you very much for your time and explanations. Will migrate to 4.x asap
