### ISSUE TITLE
d3 origin not working properly

### ISSUE THREAD

**Issue by klinki** [mbostock/d3#2768]
Hi, 
I'm trying to use d3 drag behavior, but I'm having hard time with origin() function.

Documentation https://github.com/mbostock/d3/wiki/Drag-Behavior#origin describes using 

    origin(function(d) { return d; })
as the identity function and often used variant for drag behavior. I have found also examples using `origin(Object)`
instead.

Here http://stackoverflow.com/questions/32982289/drag-function-not-working-for-d3 is also suggestion of using 

    origin(function(d) { return this; })

but this is not working either.

Here are jsfiddles which I tried:

 1. Identity function https://jsfiddle.net/klinki/njp9198e/
 2. Object https://jsfiddle.net/klinki/d0z96o03/
 3. return this https://jsfiddle.net/klinki/ezh8ywro/

first one is throwing these errors:

> Uncaught TypeError: Cannot read property 'x' of undefined(anonymous function
> Uncaught TypeError: Cannot read property '0' of undefined

and other two this one:

> Error: Invalid value for <rect> attribute x="NaN"

Finally after some time I have found one which works:
 https://jsfiddle.net/klinki/u3zwv96t/

Is using the identity function obsolete in current version of d3? (3.5.16) Or is it just some bug? 
Could you please fix it or update documentation or explain me how to use it properly? Thanks!

**Comment by mbostock** [comment]
You can only use the identity function when the element’s data is an object with x and y properties (e.g., `{x: 1, y: 2}`. As the documentation says:

> This is suitable when the datum bound to the dragged element is already an object with x and y attributes representing its current position.

In your case there is no data bound to the element, so `d` is undefined, and the code then throws an error.

You can use Object in place of `function(d) { return d; }` and it should be equivalent. I recommend the latter because it is more obvious. In the past I used Object as shorthand, but I no longer advocate that approach since it leads to the sort of confusion shown here.

I can’t think of a good reason to use `function() { return this; }`. That would mean that the element itself is the origin object, and elements don’t typically have meaningful x and y properties. It’s better to use data to store the drag coordinates.
