### ISSUE TITLE
.tickValues throws error

### ISSUE THREAD

**Issue by heavyhorse** [mbostock/d3#2770]
[Line 670](https://github.com/mbostock/d3/blob/master/d3.js#L670 )

### using .tickValues to display everything 7th value of an ordinal scale
```
var xAxis = d3.svg.axis()
            .scale(x)
            .orient('bottom')
            .tickValues(data.map(function(d,i) {
                if(i % 8 == 0) {
                    return d.date;
                }
                //else {
                //    return data[0].date;
                //}
            }));
```

### console output
```
d3.js:670 Error: Invalid value for <g> attribute transform="translate(NaN,0)"
```

### incoming arguments
```
/* x =  "translate(NaN,0)", arguments = [undefined, 1, 0] */
function attrFunction() {
      var x = value.apply(this, arguments); 
      if (x == null) this.removeAttribute(name); else this.setAttribute(name, x);
}
```

No error is thrown when the "else" statement is uncommented. Is this an issue or a mis-use of `.tickValues`?

**Comment by mbostock** [comment]
Your tickValues contain undefined because when i % 8 is not zero, you don’t return anything. This is then coerced to NaN, resulting in translate(NaN,0), which is an invalid transform.

You probably want to do something like this instead:

```js
xAxis.tickValues(data
    .filter(function(d, i) { return !(i % 8); })
    .map(function(d) { return d.date; }));
```

In the future, please use Stack Overflow tag d3.js or the d3-js Google group to ask for help.
