### ISSUE TITLE
d3.layout.histogram frequency callback

### ISSUE THREAD

**Issue by tj** [mbostock/d3#2775]
This is a bit of a weird use-case. I already have computed histograms (from elasticsearch), however you cannot specify a number of bins in ES, so I need to do it in js-land.

Because of this I have to re-bin and apply the frequency that ES originally computed. It could be nice to allow `.frequency(d => d.count)` or similar so that data is not lost, but it's understandable if this is too strange of a use-case.

**Comment by mbostock** [comment]
I’ve removed the *histogram*.frequency flag in [d3-array](https://github.com/d3/d3-array) for D3 4.0. It didn’t really do much: if “frequency” mode was enabled, then *bin*.y was equal to *bin*.length, since it’s just the count of elements in that particular bin, and the bin is represented as an array of elements; if “probability” mode was enabled, then *bin*.y was equal to *bin*.length / *data*.length, where *data* is the array of values you passed to the histogram layout. So it’s easy to reconstruct these values directly from the bins.

Assuming your data is already binned, say like this:

```json
[
  {"value": 0.1, count: 21},
  {"value": 0.2, count: 14},
  {"value": 0.3, count: 3}
]
```

Then you could use a histogram operator like this to re-bin:

```js
var bins = d3.histogram()
    .value(function(d) { return d.value; })
    (data);
```

Then to compute the total count in each new bin, use [d3.sum](https://github.com/d3/d3-array#sum) (or [*array*.reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce), if you prefer):

```js
var counts = bins.map(function(bin) {
  return d3.sum(bin, function(d) {
    return d.count;
  });
});
```

**Comment by tj** [comment]
Ahh right, missed that it holds on to the old values. Thanks man!
