### ISSUE TITLE
transtions memory leak

### ISSUE THREAD

**Issue by mmaracic1** [mbostock/d3#2776]
Hi, 

First off... kudos, I am not worthy.... and probably wrong.

I have been going mad for the past few days coz my labour of love was leaking 10MB every 5 seconds... and after stripping it down to the bone, it seems that transitions are leaking. In particular, the transition on a font-size attribute where you compute the size of the font in a function.

https://jsfiddle.net/dzyxjv5c/

I used one of Mike's [examples](http://bl.ocks.org/mbostock/raw/a8a5baa4c4a470cda598/) and just added two lines of code that were causing havoc in my code...
It starts clocking up private memory (not JS heap) pretty fast on Chrome 49 and FF 43 ... strangely not in IE 11
I tried it on several machines, different versions of windows and the result is always the same... 

Is it me?

Best,

**Comment by mbostock** [comment]
Sorry, but I’m not able to reproduce this. I don’t see any memory leak in when using the Record Heap Allocations feature in Chrome developer tools. I do see memory growth in the Task Manager view, but it’s probably something like the browser caching rendered font glyphs, and not a memory leak per se. Note that when you transition font sizes, you are creating fonts at subpixel values (e.g., 12.123401923px), which could be cached separately from 12px and 13px.

You might consider either using interpolating a transform (either in CSS or SVG) rather than interpolating the font size. In the worst case, you could also consider triggering a CSS transition on a CSS transform rather than using D3 to interpolate the font size.

**Comment by mmaracic1** [comment]
Thanks,

I thought that it might be something along those lines so I tried rounding
the sizes but scoffed at my naive attempt after realizing that
interpolation is to blame and I will still end up with unnecessary precise
size progression.
I will try as suggested...

Thank you for your work... it is impressive and humbling.

Best,

Mario.

P.S. while I have your ear... have you came across anything that could do
edge bundling while avoiding passing through certain defined areas? I would
like to build a graph where nodes would be shapes of different sizes and
bundled connections would avoid passing under the nodes but rather meander
between them?
