### ISSUE TITLE
Setting 'pointer-events' to 'none' during 'mouseover' sends 'mouseleave'

### ISSUE THREAD

**Issue by oguzhanogreden** [mbostock/d3#2781]
[Here](https://jsfiddle.net/oguzhanogreden/07ux9aLw/) is a reproducible example.

I'm not sure if this is an expected behaviour. If so, what is the way to wait for changes/transitions to finalize before other pointer-events trigger other parts of the code?

What I'm trying to achieve is analogous to trying and turning [this](https://jsfiddle.net/oguzhanogreden/n0u44bso/) square into yellow _if the pointer is not on it_ when it finishes fading into green. If one scrolls faster than the fade into green, rest does not follow.

**Comment by mbostock** [comment]
This is the expected behavior. The *selection*.on listeners map directly to the underlying browser API (addEventListener and removeEventListener), so you’re just seeing the native browser behavior here.

(There is a polyfill for mouseenter and mouseleave on old browsers, but that applies to relatively few browsers these days, and I don’t believe it should affect the described behavior.)

You can listen to the transition *end* event if you want to wait for a transition to complete.
