### ISSUE TITLE
d3's interval.offset isn't crossbrowser-standardized whereas d3-time's is

### ISSUE THREAD

**Issue by clementprdhomme** [mbostock/d3#2790]
Hi!

At work I use `d3` and I need to offset a date by a non-integer value to make an animation. The code I use is:
```javascript
/* Simplified version */
let date = new Date();
d3.time.day.offset(date, 0.612);
```

What happens is that in Chrome it effectively computes the offset, but on Safari and Firefox, the returned date is the same as before. I tested on all the latest version of the browsers.

I saw that in issue #2611 @mbostock told that it has been standardized in `d3.time` version `4.0` using `Math.floor`, but as of now (version `3.5.16` of `d3`), the issue is not solved on **this** library.

Could it be merged or documented to prevent errors from people who do not test under different environments?

Thanks!

Clément

**Comment by mbostock** [comment]
Unfortunately due to my limited resources and the need to get D3 4.0 released I am not currently willing to back-port the new implementation of [d3-time](https://github.com/d3/d3-time) for 4.0 back to 3.x. You are welcome to edit the API Reference in D3’s public wiki, but I would also encourage you to consider using [D3 4.0 alpha](https://github.com/mbostock/d3/tree/4)
