### ISSUE TITLE
D3 cluster: can lines make no crossing?

### ISSUE THREAD

**Issue by AppleXiao1995** [mbostock/d3#2800]
Here is an example of d3 clustering:
[bl.ocks.org/mbostock/4063570](http://bl.ocks.org/mbostock/4063570)
We can see the lines cross each other like this：
![2016-04-18 5 44 50](https://cloud.githubusercontent.com/assets/10582911/14603980/bae5326a-05a3-11e6-9f06-7107a18d3d9b.png)
How can it be avoided?

D3 tree layout [http://bl.ocks.org/robschmuecker/7880033](url)can avoid line crossing but the leafs are not finished on one line.

![2016-04-18 5 54 21](https://cloud.githubusercontent.com/assets/10582911/14604010/fd40f73e-05a3-11e6-8d31-6b188f65a61d.png)
Can any layout be modified to satisfy both conditions: 1、no line crossing 2、leafs are on one line

In fact, I want a proper layout to represent a syntax tree.
Thanks!

**Comment by mbostock** [comment]
I recommend taking a look at the more recent [dendrogram example](http://bl.ocks.org/mbostock/ff91c1558bc570b08539547ccc90050b) using [D3 4.0 alpha](https://github.com/mbostock/d3/tree/4). D3 4.0 isn’t required to use the technique in that example, however.

[![screen shot 2016-04-19 at 9 00 32 am](https://cloud.githubusercontent.com/assets/230541/14646126/34d72a10-060d-11e6-89c6-f22ee8eaa05a.png)](http://bl.ocks.org/mbostock/ff91c1558bc570b08539547ccc90050b)

There are two ways that the newer example avoids line-crossing. First, the nodes are sorted by ascending height so that the tallest nodes are placed on the bottom. Second, rather than placing the control points of the cubic Bézier diagonal at the midpoint of the parent and child, the control points are always placed 100px to the right of the parent, like so:

```js
function diagonal(d) {
  return "M" + d.y + "," + d.x
      + "C" + (d.parent.y + 100) + "," + d.x
      + " " + (d.parent.y + 100) + "," + d.parent.x
      + " " + d.parent.y + "," + d.parent.x;
}
```

This tends to have a better result with the dendogram layout since the links can cross multiple levels of the tree.

If you want further assistance, please use Stack Overflow tag d3.js or the d3-js Google group. These issues are primarily for feature requests and bug reports. I’m happy to help here because there’s a readily-available answer, but I often am unable respond to every request for help. Good luck!
