### ISSUE TITLE
d3.layout.force overlap

### ISSUE THREAD

**Issue by wwg88888888** [mbostock/d3#2806]
About d3.layout.force application, I use, the data base for the node and the connection line, and the connection line is more complex,
Expected target is:
1, the distance between the point and the point as close as possible,
2, all the points do not overlap,
3, in accordance with the relationship between the natural growth of the shape of a galaxy.
I tried a lot of methods, can not achieve the expected, and now do the best way code is as follows:

```js
var charge = function (d) {
    return   -Math.pow(d.r, 2.0) *  Math.sqrt(Math.sqrt(d.weight));
}

d3.layout.force()
            .size([width, height])
            .charge(charge)
            .linkDistance(function (d) {
                var s = d.source,
                        t = d.target;
                var r1 = (s.r);
                var r2 = (t.r);
                return (r1 + r2);
            });
```

Is there a better way?

**Comment by mbostock** [comment]
The force layout typically cannot guarantee hard constraints (such as the distance between two points being fixed, or two points not overlapping) because most often the constraints are contradictory when taken together: the force layout must instead find a compromise that the constraints as closely as possible. However, even then, the force layout is just a heuristic and numerical approximation that isn’t guaranteed to do anything…

You can often get better results by tweaking parameters and adding additional forces to the layout, such as in these examples:

https://bl.ocks.org/mbostock/3231298
http://bl.ocks.org/mbostock/1021841
https://bl.ocks.org/mbostock/7881887

Please use Stack Overflow tag d3.js or the d3-js Google group to ask for help. These issues are for feature requests and bug reports only. Thank you!

**Comment by wwg88888888** [comment]
@mbostock I tried to give you an example, the case did not have the concept of connecting line, so the difference is larger than expected, the final structure is not a tree
