### ISSUE TITLE
Bar chart onclick not fired when there are many columns (~4000) 

### ISSUE THREAD

**Issue by Avien** [mbostock/d3#2807]
Works fine if there are around 400-500 columns

**Comment by mbostock** [comment]
Please use Stack Overflow tag d3.js or the d3-js Google group to ask for help. These issues are for feature requests and bug reports only. Thank you!

**Comment by Avien** [comment]
And this not a bug?

**Comment by mbostock** [comment]
It’s not likely to be a bug in D3, no; it’s more likely to be a bug in your bar chart. If you want help debugging, I would strongly recommend posting a link to a running example (say on bl.ocks.org or JSFiddle) that demonstrates the problem. Otherwise, it’s impossible to investigate, regardless of where the bug exists.

**Comment by Avien** [comment]
it can't be a bug in my bar chart since its working when there are 400 columns and not working when there are 4000
Its the same source code
Thanks anyway

**Comment by mbostock** [comment]
There are lots of reasons why it could be a bug in your code, even if the only thing that changes is 400 versus 4,000 columns. But even if I wanted to help, there’s no way I could if you don’t post a link to your running code.

**Comment by pokeball99** [comment]
@Avien exactly as mbostock said, we can't help you to fix it or if its a bug in d3's code itself
