### ISSUE TITLE
camelCase attributes to dashed

### ISSUE THREAD

**Issue by QuinnLee** [mbostock/d3#2808]
Accept dashed svg attributes as camel cased. 
For example
```js
attr({strokeWidth: 2, strokeDasharray: "5, 5" }) 
```
to be equivalent to 

```js
attr({"stroke-width": 2, "stroke-dasharray": "5, 5" }) 
````

**Comment by mbostock** [comment]
Thank you for the suggestion. I don’t think this is a good idea, for a few reasons:

D3 favors parsimony: if there’s already a reasonably good way of doing something, that should be sufficient and we shouldn’t offer several approximately-equivalent ways of accomplishing the same task. In fact, this is why I am extracting support for multi-value maps out of [d3-selection](https://github.com/d3/d3-selection) for D3 4.0 and moving it to an optional plugin, [d3-selection-multi](https://github.com/d3/d3-selection-multi). The new multi-value map methods also have distinct method names, such as *selection*.attrs instead of *selection*.attr, to avoid confusion and allow a cleaner, more consistent implementation.

D3 tries to adhere to standards as closely as possible. So, since *element*.setAttribute automatically convert dashed attribute names to camel-cased attribute names, neither should *selection*.attr. (This is somewhat related to the “D3 is not a compatibility layer” philosophy.) Obviously there’s a continuum here: D3 has to provide *some* functionality on top of the standards or vanilla JavaScript, or there would be no point in providing a library. But there’s also a cost of introducing new APIs, particularly ones that may be confusingly similar to existing standard APIs. I only want to add to D3’s API if it substantially increases utility over the standard APIs, and I don’t feel that converting camel-cased names to dashed names is sufficient.

Lastly, and most importantly, there are cases where you want camel-cased attribute names! For example, SVG’s [viewBox attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) is normally camel-cased. Other non-HTML DOMs may also have case-sensitive attributes. To support this feature, D3 would need to know which attributes should be automatically converted from camel-cased to dashed, and which should not. That goes against the adhering to standards principle described above, and is also tedious to implement.

(And, it’s also bad for performance, since D3 would have to check and possibly re-write attribute names.)

**Comment by QuinnLee** [comment]
Thanks for the feedback!
