### ISSUE TITLE
the d3.mouse need to be rewrite

### ISSUE THREAD

**Issue by Alex--wu** [mbostock/d3#2809]
Obviously the d3.mouse in d3 event is out of date.
The firefox userAgent doesn't include 'WebKit' anymore...
The last change in d3.mouse is 1 year ago!

**Comment by mbostock** [comment]
If there’s a bug you’d like me to investigate, please be specific about what behavior you expect, what behavior you experienced, and include a link to a running example (such as on bl.ocks.org) so that I can reproduce the problem.

The user agent test in d3.mouse isn’t for Firefox; it’s for a bug in Safari that until recently was still present. It was fixed years ago, but Safari updates slowly because it is tied to OS X and iOS releases. (Only recently did Safari start offering a [Safari Technology Preview](https://developer.apple.com/safari/download/) for a more up-to-date version.) In contrast, most other modern browsers update automatically independently of the operating system.

The fact that d3.mouse hasn’t changed in a year (or more) is not an indication that something is wrong. The standard browsers APIs that D3 uses are relatively stable and well-supported across browsers. Furthermore, *D3 is not a compatibility layer*, and does not generally provide workarounds for bugs in browsers.

I’m aware of at least one Firefox bug with getScreenCTM not observing CSS transforms; see #2771 for details, and these bugs:

https://bugzilla.mozilla.org/show_bug.cgi?id=849203
https://bugzilla.mozilla.org/show_bug.cgi?id=972041

If there’s something else you’d like me to investigate, please be specific and I will open a new issue.

**Comment by Alex--wu** [comment]
Hi Mike,
Thank you for your reply, my issue is from the getScreenCTM, see the https://bugzilla.mozilla.org/show_bug.cgi?id=849203
I don't mean that the d3.mouse is not good, as I am a fun of d3.js, I just want it to be perfect :)
