### ISSUE TITLE
d3.mouse returns different values on Chrome and Firefox

### ISSUE THREAD

**Issue by rajgoel** [mbostock/d3#2810]
There seems to be an issue with ```d3.mouse``` returning different values on Chrome and Firefox as can be seen in this example http://maurizzzio.github.io/function-plot/scale.html. On Firefox the point on the curve follows the mouse pointer, however, on Chrome there is a fix delta causing the point on the curve being shown shifted to the mouse cursor.

As discussed at https://github.com/maurizzzio/function-plot/issues/53#issuecomment-180872477 it is not clear how to convert the result of ```d3.mouse``` in such a way that the outcome would show on Chrome as it does on Firefox. 

It feels as if this a bug in ```d3```. However, if there a simple way to convert the result of ```d3.mouse``` appropriately, then a fix for ```function-plot``` be made ...

**Comment by mbostock** [comment]
This is most likely a bug in Chrome’s implementation of getScreenCTM, similar to #766. It sounds related to this (fixed) bug:

https://bugs.webkit.org/show_bug.cgi?id=96361

In testing your example, it appears you can avoid this bug by not applying a CSS zoom style to the chart. (Alternatively, you may be able to correctly for the zoom factor by hand after calling d3.mouse.)

There have been some similar bugs in Firefox’s implementation of getScreenCTM, too, regarding CSS transforms (see also #2771):

https://bugzilla.mozilla.org/show_bug.cgi?id=849203
https://bugzilla.mozilla.org/show_bug.cgi?id=972041

I probably won’t attempt to fix a buggy getScreenCTM implementation in D3. It’s tricky to implement getScreenCTM correctly, as you might guess from the broken implementations in various browsers. And furthermore, D3 is not a compatibility layer; I try to avoid implementing browser-specific workarounds. I simply don’t have the resources.

If you find a simple fix, though, let me know, and I may consider including it. On other hand, if it’s a complicated workaround (like the one proposed in #766), then it might be better to just advocate browsers fixing the problem directly rather than burdening libraries with complications.

**Comment by rajgoel** [comment]
Thanks a lot for the quick response. The links you provided actually helped finding a workaround for my problem with the function-plot library (see https://github.com/maurizzzio/function-plot/issues/53#issuecomment-213981346)
