### ISSUE TITLE
d3.min.js IE8 erroring - Object doesn't support this action

### ISSUE THREAD

**Issue by MarkPieszak** [mbostock/d3#2815]
I have the included `<meta charset="utf-8">` in the `<head>`

As well as the `<script charset="utf-8" ...>` for the actual file. Has something changed, I was under the impression this was the work-around?

> Note: I have all the shims / etc needed to make everything else function.

**Comment by mbostock** [comment]
Sorry, but I don’t have the resources to provide support for IE8. Please try Stack Overflow tag d3.js or the d3-js Google group if you’d like to ask for help. I also strongly recommend posting a link to a running example so that people can reproduce the error and debug it; it’s difficult to speculate the cause knowing only the error message (“Object doesn’t support this action”).

**Comment by MarkPieszak** [comment]
It seems the file itself was causing the issue (I wasn't even using D3 on that page yet).
Oh it's totally fine Mike, I just removed it from the Masterpage, pages that want to use the amazing D3 have to inject it themselves. (We still have some clients on IE8, but IE8-9-10 will be dropped soon, fingers crossed).

Thanks for your response though, take care.
