### ISSUE TITLE
Zoom to Bounding Box II bug

### ISSUE THREAD

**Issue by dylanmac** [mbostock/d3#2819]
https://bl.ocks.org/mbostock/9656675

While trying to convert the Zoom to Bounding Box II to use countries instead, I noticed some erratic zooming in my world map.  I assumed it was something I did in my configuration, but then I started clicking on the states in the example above and I saw there is erratic behavior there as well.  Try clicking on VT and NH and you end up way in the Atlantic Ocean.

**Comment by mbostock** [comment]
Thanks. I’ve fixed the example. In [D3 3.5.7](https://github.com/mbostock/d3/releases/v3.5.7), d3.behavior.zoom was changed to clamp the scale according to *zoom*.scaleExtent if the scale is set programmatically. (Previously, it ignored the scale extent.) As a result, the example you linked wasn’t computing the correct transform.

The fix is to clamp the scale before computing the translation:

```js
scale = Math.max(1, Math.min(8, 0.9 / Math.max(dx / width, dy / height))),
```

http://bl.ocks.org/mbostock/9656675/fc23f845a0ac96e45bc8a25f809eb47b473731e0

**Comment by dylanmac** [comment]
Perfect.  Thanks.
