### ISSUE TITLE
Build documentation out of date

### ISSUE THREAD

**Issue by jsheperd** [mbostock/d3#2820]
The current wiki page has got only a sort sentence about how to use make even makefile was removed from the project.
Can you update the wiki on how can we make the d3.js and d3.min.js builds from the src ?
I have spent 2 hours to find it out, but simple can't solve it.

**Comment by mbostock** [comment]
It’s the prepublish script in package.json, so:

```
npm run prepublish
```

The wiki is publicly-editable, so feel free to make edits. However, I’m not going to be documenting the 3.x build process because 3.x is effectively frozen and all ongoing development is happening in the [D3 4.0 modules](https://github.com/d3) rather than in this repository.
