### ISSUE TITLE
d3.json causes mouse cursor always busy

### ISSUE THREAD

**Issue by stt106** [mbostock/d3#2825]
I am fairly new to d3 and just found that after retrieving some data using d3.json it somehow sets the mouse cursor always busy; it appears as if something is continuously running behind the scene though nothing is running anymore. I have to manually set the cursor back to default. Is this the expected behaviour?

e.g.I have a service in which one of the functions is something like:

```
function getData(callback) {
     d3.json('someUrl', callback)
         .header('content-type', 'application/json')
        .send('POST', someParameters);
}
```

then in my view, I call this getData function passing in a callback which will either give me some data back or an error; my view will then handle either case. When I do get the data back and then load the data into my view, the mouse cursor becomes busy all the time.

**Comment by mbostock** [comment]
d3.json doesn’t set the mouse cursor. Internally d3.json uses XMLHttpRequest. I’ve never heard of that setting the mouse cursor, since requests are typically processed asynchronously in the background and in parallel. It’s possible that you’re asking the browser to load and parse a particularly large JSON file, and since parsing of JSON is processed synchronously (i.e., it stalls the JavaScript thread and the user interface during the call to JSON.parse), that might hang the browser. And of course you can hang the browser in other ways by processing whatever data you load. But these are not issues that are specific to D3, so please try Stack Overflow or the d3-js Google group if you’d like help improving performance and debugging.
